kodadot/nft-gallery

README.md
This pull request updates README file to use urls from kodadot repository
=> Update urls to use kodadot repository

dashboard/src/components/shared/format/Identity.vue, dashboard/src/vuex/IdentityModule.ts
=> Identity resolves a bit faster

dashboard/src/components/Navbar.vue
Fixes #67
Not sure if you want to have a logo inside this container
This pull request also fixes additional space on mobile for navbar links
Before:
After:
=> Add wrapper class, remove white spaces and styles

dashboard/src/router/profile.ts
=> change route from /u to /rmrk/u

dashboard/src/components/rmrk/Gallery/GalleryItem.vue, dashboard/src/components/rmrk/Media/IFrameMedia.vue, dashboard/src/components/rmrk/Media/MediaResolver.vue, dashboard/src/components/rmrk/types.ts, dashboard/src/components/rmrk/utils.ts, dashboard/tslint.json
=> Can show svg games (svg+xml)

dashboard/src/components/shared/format/Money.vue
=> fixed usd value, removed tostring

dashboard/src/components/landing/Landing.vue
=> added identity to landing page

dashboard/src/components/rmrk/Profile/NavbarProfileDropdown.vue
=> Fix account dropdown on scroll

dashboard/src/components/rmrk/Gallery/Search/query.ts
=> Group by image and collection

dashboard/package.json, dashboard/src/components/rmrk/Media/AudioMedia.vue, dashboard/src/main.ts, dashboard/src/vue-audio-visual.d.ts, dashboard/yarn.lock
=> Added waveform component to audio media

dashboard/src/components/landing/Landing.vue, dashboard/src/components/rmrk/Create/CreateCollection.vue, dashboard/src/locales/en.json
=> Changed titles in Create Collection

dashboard/src/components/rmrk/Gallery/Gallery.vue, dashboard/src/main.ts, dashboard/src/utils/filters.ts, dashboard/src/utils/stringUtils.ts
* Fixes #248 
* Complete different solution than #272 
* Full _CSS based_ solution with a little U.I modification
This P.R also contains the `truncateStr` filter you asked in #272
=>  Truncate NFT names after a max number of chars with only CSS

dashboard/src/components/rmrk/Gallery/Gallery.vue, dashboard/src/components/rmrk/Gallery/Search/SearchBar.vue, dashboard/src/components/rmrk/Gallery/Search/SearchSortDropdown.vue, dashboard/src/components/rmrk/Gallery/Search/TypeTagInput.vue, dashboard/src/components/rmrk/Gallery/Search/query.ts, dashboard/src/components/rmrk/Gallery/Search/types.ts, dashboard/src/components/rmrk/service/RmrkService.ts, dashboard/src/components/rmrk/service/scheme.ts, dashboard/src/components/rmrk/utils.ts, dashboard/src/components/shared/AccountSelect.vue, dashboard/src/fetch.ts, dashboard/src/icons.ts, dashboard/src/locales/en.json
We can search more. 
Currently additions.
Sort by something.
Filter by types.
It's not perfect, however a lot of code can be reused
=> great filter

dashboard/src/components/Navbar.vue, dashboard/src/components/rmrk/Profile/NavbarProfileDropdown.vue
Fixes:
- connect button padding on mobile
- avatar/navbar padding/margins
**Connect button**
Before:
After:
**Avatar**
Before:
After:
=> Fix navbar styles

dashboard/public/index.html
My proposition is to change loader styles to center it and fix it on mobile view
=> Change loader styles

dashboard/src/components/Navbar.vue, dashboard/src/components/rmrk/Profile/NavbarProfileDropdown.vue, dashboard/src/components/shared/Avatar.vue, dashboard/src/components/shared/SwitchLocale.vue
=> Add language switcher, adjust styles

dashboard/src/components/rmrk/Gallery/AvailableActions.vue, dashboard/src/icons.ts
=> 283 issue warning for buy

dashboard/src/components/rmrk/Gallery/Item/Facts.vue, dashboard/src/components/shared/format/Money.vue
we should just display only KSM
=> Fixing price calculation

dashboard/src/App.vue, dashboard/src/components/rmrk/Gallery/GalleryItem.vue, dashboard/src/components/rmrk/Pack/PackSaver.vue, dashboard/src/components/shared/Auth.vue, dashboard/src/views/Profile.vue
Expected new features, upgrades and features
=> 7k6 - changelog 

dashboard/src/components/rmrk/Gallery/Item/Sharing.vue, dashboard/src/icons.ts
=> Extend social sharing with new social networks

dashboard/src/components/rmrk/Gallery/GalleryItem.vue, dashboard/src/components/rmrk/Gallery/Item/Name.vue
=> 7k7 - changelog 

dashboard/src/components/rmrk/Gallery/Item/Facts.vue, dashboard/src/components/rmrk/utils.ts
we are hitting rate limiter on public gateways
=> switch to dedicated ipfs gateway

dashboard/src/App.vue, dashboard/src/components/landing/Carbonless.vue, dashboard/src/components/landing/Landing.vue
=> flexing SEO

dashboard/src/App.vue, dashboard/src/components/landing/Carbonless.vue, dashboard/src/components/landing/Landing.vue, dashboard/src/components/landing/Sustainability.vue, dashboard/src/components/rmrk/Create/SimpleMint.vue, dashboard/src/components/rmrk/Gallery/Gallery.vue
=> preparing visual cta for various sub-pages

dashboard/src/components/landing/EsSustainability.vue, dashboard/src/components/landing/Landing.vue, dashboard/src/router/index.ts
This pull request adds the es translation of the sustainability page as mentioned in issue #335.
=> Sustainibility page spanish translation

dashboard/src/components/rmrk/Gallery/GalleryItem.vue
=> Dark mode GalleryItem button

dashboard/src/components/rmrk/Gallery/EmotionList.vue, dashboard/src/components/rmrk/Gallery/Gallery.vue, dashboard/src/components/rmrk/Gallery/GalleryItem.vue
Implemented dark theme for missed out elements and hid ``default view`` button as mentioned in #435.
=> Dark theme for remaining items

dashboard/src/components/landing/About.vue, dashboard/src/components/landing/EsCarbonless.vue, dashboard/src/router/index.ts
Created the Spanish translation of carbonless NFT page using the translation provided by @CdrsAlejandro in #438
=> Spanish translation of Carbonless page

dashboard/src/components/rmrk/Create/AttributeTagInput.vue, dashboard/src/components/rmrk/Gallery/AvailableActions.vue, dashboard/src/components/shared/accounts/Keypair.vue, dashboard/src/components/transfer/TxSelect.vue, dashboard/src/registerServiceWorker.ts, dashboard/src/styles/initial-variables.scss, dashboard/src/styles/variables.scss
Made the ``tags`` in ``simple mint`` to the dark mode.
=> Convert elements to dark theme

dashboard/src/components/Navbar.vue, dashboard/src/components/rmrk/Gallery/Gallery.vue, dashboard/src/components/rmrk/Gallery/Search/SearchBar.vue, dashboard/src/styles/variables.scss
Changed the white shadow to pink glow for cards and search bar in the gallery and for dropdowns in navbar as mentioned in #449.
=> Added Pink glow to elements

dashboard/src/components/landing/Landing.vue, dashboard/src/router/index.ts
=> feat(grants): redirect /grants to feedback form (#447)

dashboard/src/components/rmrk/Create/SimpleMint.vue, dashboard/src/components/rmrk/service/NftUtils.ts, dashboard/src/styles/global.scss
Reverts kodadot/nft-gallery#466
=> Revert "Fixed LIST in Simple mint"

src/components/shared/format/Identity.vue, src/views/OnChainProperty.vue, src/views/Profile.vue
Added to show user on-chain properties as mentioned in #134
=> Added on-chain properties

src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Media/MediaResolver.vue, src/components/rmrk/Media/ObjectMedia.vue, src/components/rmrk/types.ts, src/components/rmrk/utils.ts
=> 213 added support for pdfs

src/views/Profile.vue
closes #465 
Looks like it's working:
[preview](https://deploy-preview-502--nftkodadot.netlify.app/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd)
=> fix(profile): metadata

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/production.md
=> Smol change

.github/PULL_REQUEST_TEMPLATE.md
=> Smol change3

.github/PULL_REQUEST_TEMPLATE.md
=> more warm welcome

src/components/rmrk/Gallery/Gallery.vue
=> fix(gallery): emotes color

src/components/rmrk/Gallery/GalleryCard.vue, src/components/rmrk/Gallery/Item/Sharing.vue, src/views/OnChainProperty.vue, src/views/Profile.vue
=> Changes to User profile

src/components/shared/format/Identity.vue, src/views/OnChainProperty.vue
=> Added watches to view show user properties

.github/PULL_REQUEST_TEMPLATE.md, package.json, yarn.lock
=> Profile has watchers so higher chance it will load on-chain stuff

src/components/rmrk/Gallery/GalleryItem.vue
=> fix(galleryItem): center image preview

src/components/rmrk/Gallery/PaginatedCardList.vue, src/locales/en.json, src/queries/firstNftByIssuer.graphql, src/queries/nftListByIssuer.graphql, src/queries/nftListCollected.graphql, src/queries/nftListSold.graphql, src/views/Profile.vue
=> Profile now shows issued and onwed nfts

src/components/rmrk/Gallery/Item/Sharing.vue
=> quickie sharing button fix

src/components/rmrk/Gallery/GalleryCard.vue, src/views/Profile.vue
=> Fixed few issues in user profile

src/components/rmrk/Gallery/AvailableActions.vue
=> fix(availableActions): remove Buy warning

SECURITY.md, netlify.toml
=> add SECURITY.md and rebuild new pinata keys

src/components/rmrk/Create/CreateItem.vue, src/locales/en.json
- fixes an incorrect field name.
- no bounty
=> fix field label for NFT description

src/components/rmrk/Gallery/GalleryItem.vue
=> fix(galleryItem): don't show null price on image

src/components/rmrk/Profile/ProfileLink.vue, src/components/shared/format/Identity.vue
- closes #552 
Weird solution on conditional rendering but it work
=> fix(identity): conditional rendering twitter 

src/components/rmrk/Gallery/Item/Name.vue
=> 347 add issuer to the nft detail

src/components/landing/Landing.vue, src/components/rmrk/Gallery/Gallery.vue
=> prefetch should be 3s per page now

src-functions/pinPost.js, src/components/rmrk/Create/SimpleMint.vue, src/components/shared/format/Identity.vue
=> Inb4 icecream

src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/History.vue
- closes #570
Extracted the events property from nft object and created a table from its fields.
=> Nft Interaction History

src/components/rmrk/Gallery/GalleryCard.vue, src/components/rmrk/Gallery/GalleryCardList.vue, src/views/OnChainProperty.vue
- Now price of each NFT is displayed in the user profile section just like the gallery.
=> Display price on card on user page

src/utils/WithKeyring.ts
=> Resolving own profile address

src/components/rmrk/Gallery/GalleryItem.vue
=> Show emoji picker only when user is logged in

src/components/rmrk/Gallery/GalleryItem.vue, src/utils/WithKeyring.ts
=> Fixes emoji picker bug

src/components/rmrk/Gallery/Appreciation.vue
=> closes #585 - Emoji picker should have KodaDot colors

src/components/rmrk/Gallery/GalleryItem.vue
Show emojis on Item or hide it on list.
=> Show see emoji on gallery item

src/components/rmrk/Gallery/GalleryItem.vue
Reverts kodadot/nft-gallery#598
=> Revert "Show see emoji on gallery item"

src/components/rmrk/Gallery/Appreciation.vue, src/components/rmrk/Gallery/EmotionList.vue, src/components/rmrk/Gallery/GalleryItem.vue
These will show EmojiPicker Button & EmotionList to disconnected users.
They will not be able to show EmojiPicker unless they're logged in.
=> fix(Appreciation): show Emojipicker only if connected

src/components/Navbar.vue, src/components/landing/Tutorials.vue, src/locales/en.json
https://nft.kodadot.xyz/tutorials
- Create a Polkadot JS Account | Crear una cartera Polkadot JS : https://www.youtube.com/watch?v=iG8iQrONnYo&t=21s
- Get KSM | Obtener Kusama: https://www.youtube.com/watch?v=cYaZWDzU1Yc
- Minting: | Crear un NFT: https://www.youtube.com/watch?v=pPsbQyJRGVQ&t=1s
=> Add link tutorials

src/components/rmrk/Gallery/Appreciation.vue
- Fix Emojipicker button not showing when toggle.
- Minor css change to match ui
=> hotfix(vemojipicker): toggle btn not showing

src/components/rmrk/Gallery/Appreciation.vue
=> fix(appreciation): uppercase emote key

package.json, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/PriceChart.vue
- closes #618 - Fixes the chart resolution problem on loading on mobile devices.
=> Fixed chart resolution problem

package.json, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/PriceChart.vue, src/components/spotlight/SpotlightTable.vue
=> Fixed price chart responsivity 

src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/History.vue, src/components/rmrk/Gallery/PriceChart.vue, tslint.json
=> fix(gallery-item): history & price chart

src/components/rmrk/Gallery/PriceChart.vue
=> fix(gallery): PriceChart yAxis

src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/History.vue, src/components/rmrk/Gallery/Item/Name.vue, src/components/rmrk/Gallery/PriceChart.vue, src/components/rmrk/Profile/ProfileLink.vue, src/components/shared/format/Identity.vue
Some small refactoring over here
compare with deploy preview
=> fix(gallery-item): remove useless div & spacing

src/components/landing/Tutorials.vue, src/components/rmrk/Credit/Credit.vue, src/components/rmrk/Gallery/Item/Facts.vue, src/components/rmrk/Media/Unknown.vue, src/components/rmrk/Profile/NavbarProfileDropdown.vue, src/components/rmrk/Profile/ProfileLink.vue, src/components/shared/Card.vue, src/components/shared/LinkResolver.vue, src/components/shared/accounts/Keypair.vue, src/components/shared/format/ExternalLink.vue, src/components/subsocial/FaucetLink.vue, src/components/transfer/Transfer.vue, src/views/Profile.vue
[Reference](https://web.dev/external-anchors-use-rel-noopener/)
- fixes security issue by adding ```rel="noopener noreferrer"``` to ```target="_blank"``` links.
=> fix(security): rel on target _blank link

src/proxy.ts
=> Fixing slate API!

src/components/FourZeroFour.vue
- closes #<601> - <Added an anchor tag at the end with the url mentioned>
=> Help users easier to report bugs

src/components/rmrk/Create/CreateCollection.vue, src/components/rmrk/Create/CreateItem.vue, src/components/rmrk/Create/CreateToken.vue, src/components/rmrk/Create/DropUpload.vue, src/components/rmrk/Create/SimpleMint.vue, src/components/shared/AccountSelect.vue, src/utils/WithKeyring.ts, src/views/Remark.vue
- Create forms are aligned
- Autologin for extension
- Default values for selects
- Create forms are aligned
- Autologin for extension
- Default values for selects
- Removed ugly tooltip for DropUpload
=> Small fixes

package.json, src/components/Footer.vue, src/components/Navbar.vue, src/components/rmrk/Create/CreateCollection.vue, src/components/rmrk/Create/CreateToken.vue, src/components/rmrk/Create/SimpleMint.vue, src/components/rmrk/Gallery/Gallery.vue, src/components/shared/TxButton.vue, src/components/subsocial/Comment.vue, src/components/subsocial/CreatePost.vue, src/components/subsocial/Reply.vue, src/components/transfer/SignSubmit.vue, src/components/transfer/Transfer.vue, src/fetch.ts, src/utils/formatBalance.ts, src/utils/ipfs.ts, src/utils/mixins/queryMixin.ts, src/views/ChainState.vue, src/views/Extrinsics.vue, yarn.lock
Fixing failed build after updated polkadot-js deps
=> Updated typescript to 4.4

src/components/rmrk/Gallery/History.vue
=> fix(history): undefined on create

src/router/index.ts
=> Do not preserve scroll

README.md
=> updated Quick Start guide

src/components/rmrk/Create/CreateCollection.vue, src/components/rmrk/Create/CreateItem.vue, src/components/rmrk/Create/SimpleMint.vue, src/utils/WithKeyring.ts
=> Fixed money component for classic mint, disabled autologin, pin meta handled under try catch

src/components/rmrk/Gallery/Gallery.vue
=> fix(gallery): pagination mobile

.github/workflows/lgtm.yml
IMO pr-chatter should be removed
- fix lgtm action from workflow
=> fix(workflow): gh action lgtm

src/components/Navbar.vue, src/components/rmrk/Create/PermaMint.vue, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Pack/PackItem.vue, src/components/rmrk/utils.ts, src/proxy.ts, src/router/rmrk.ts
- Batteries included
- Flexed last things
=> permafrost

src/components/rmrk/Create/PermaMint.vue
- Batteries included
- Flexed last things
- Wao merge --vite
- <PR's what's new context goes here>
=> Permafrost 2

src/components/rmrk/Create/PermaMint.vue
=> vite frost

src/components/rmrk/Gallery/GalleryCard.vue, src/components/rmrk/Gallery/GalleryCardList.vue, src/queries/collectionById.graphql
@yangwao could you test it on your collection?
- closes #717
=> feat(collection): show if account is current nft owner

src/components/rmrk/Gallery/GalleryCard.vue
Hotfix errors in console from GalleryCard component
=> fix(collection): errors in console

.eslintrc.js, .github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, src/components/rmrk/Create/PermaMint.vue, src/components/rmrk/Gallery/Gallery.vue, src/components/rmrk/Gallery/GalleryCard.vue
- This PR closes #<issue_number> - <Brief_description_how_I've_fixed_it>
=> Ice Ice baby

src/components/rmrk/Create/DropUpload.vue
- closes #645 
Have added an event listener for paste, fetched the required info and sent it to the common function
=> #645 Paste image from clipboard

src/components/shared/BalanceInput.vue, src/components/shared/ReadOnlyBalanceInput.vue, src/components/transfer/Transfer.vue, src/utils/calculation.ts
- closes #<issue_number> 
Have added an input field for USD, where you can constantly change the values and get KSM price and vice versa.
One issue with this is that the KSM price we fetch is from an API and the value doesn't change unless you reload, that is why I have added an approximate text, so the user knows the value is approximate.
Suggestion: In the future, we can implement polling or sockets so the KSM price changes instantly. 
=> Ksm Usd convertor in transfer

src/components/rmrk/Create/DropUpload.vue, src/components/shared/ReadOnlyBalanceInput.vue
- replace double quotes with single quote
-  use 'const' instead of 'let'
=> chore: fix lint warning

src/components/rmrk/Create/CreateCollection.vue, src/components/rmrk/Create/CreateItem.vue, src/components/rmrk/Create/DropUpload.vue, src/components/rmrk/Create/PermaMint.vue, src/components/rmrk/Create/SimpleMint.vue
- This PR closes #<issue_number> - <Brief_description_how_I've_fixed_it>
=> Image paste text change

src/components/rmrk/Create/AttributeInput.vue, src/components/rmrk/Create/CustomAttributeInput.vue
=> Custom metadata component

src/App.vue, src/components/rmrk/Gallery/Appreciation.vue, src/components/rmrk/Gallery/GalleryItem.vue, src/components/shared/wrapper/IndexerGuard.vue, src/locales/en.json, src/queries/checkIndexer.graphql, src/store.ts, src/utils/mixins/indexerMixin.ts
=> Disable actions if indexer is not working

src/components/transfer/Transfer.vue, src/utils/transactionExecutor.ts
=> Transactions can return hashes

src/App.vue, src/components/Error.vue, src/router/index.ts
Closing #767 
I made also error page, but infinite notification is a bit berrer
=> Handle indexer fail

src/App.vue, src/queries/checkIndexer.graphql
- Closing #771
- Use snackbar instead of notification for failed service
=> In less than 24 hrs someone can change indexer schema

src/views/Profile.vue
- This PR closes #758 
https://kodadot.xyz/transfer/?target= EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU
=> #758 Swapping tab order in creators profile

src/views/OnChainProperty.vue
- This PR closes #760 
- Fill up your KSM address:
=> #760 add mailto: in profile section email

src/components/rmrk/Gallery/Appreciation.vue, src/components/rmrk/Gallery/EmotionList.vue, src/components/rmrk/Profile/ProfileLink.vue, src/components/shared/LinkResolver.vue, src/components/shared/format/Identity.vue
- twitter icon alignement
- remove blank space above title when logged off
- Identity component show icon before text not after
Would be cool to match "Creator"; "Owner" subtitle style betwen Gallery & Collection
=> fix(galleryItem): minor changes

src/views/Profile.vue
=> #783 Fix profile page on mobile

package.json, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Media/ModelMedia.vue, src/components/transfer/DonationButton.vue, yarn.lock
=> We love 3D

package.json, src/components/rmrk/Gallery/PriceChart.vue, yarn.lock
=> Optimize line chart for bundle size

src/components/rmrk/Gallery/Item/Sharing.vue
- This PR closes #731 
Have used share api for all the platforms where its supported
=> #731 Using native webshare API for sharing

src/components/rmrk/Gallery/CollectionItem.vue
Share buttons can be vertical aligned if needed
=> fix(collection): unify label style with gallery

src/components/rmrk/Media/ImageMedia.vue, yarn.lock
=> fixed 1 by 1

src/locales/en.json
=> fix(locale): en.json

.github/workflows/lint.yml, README.md, src/components/toolbox/Toolbox.vue, src/utils/mixins/extrinsicsMixin.ts, src/views/Extrinsics.vue
Github Workflow to lint code
- This PR closes #641
=> chore(eslint): github workflow to lint code 

src/components/rmrk/Gallery/PaginatedCardList.vue, src/components/rmrk/Gallery/Pagination.vue, src/views/Profile.vue
- This PR closes #805 
- https://deploy-preview-828--nftkodadot.netlify.app/rmrk/u/FA3C2e9shL7xYpeA2HN8J2uuxrZ8hRNqKUvKVVyRAAUSfGq?tab=nft&page=7
=> feat(profile): add pagination & current tab on url

src/components/series/SeriesTable.vue
- This PR closes #<issue_number> - <Brief_description_how_I've_fixed_it>
=> fix(series): hotfix series-insights

package.json, src/components/series/SeriesTable.vue, yarn.lock
=> Double fix 🎓 

src/components/rmrk/Create/SimpleMint.vue, src/utils/support.ts
=> Smol fee for the expert mint

src/components/rmrk/Gallery/CollectionActivity.vue, src/components/rmrk/Gallery/CollectionItem.vue, src/queries/collectionById.graphql, src/queries/nftListByCollection.graphql
What was the problem: 
The current stats are calculated from the `collection.nfts` but if you filter them, the stats are broken
=> Fixing stats for the collection

src/components/Navbar.vue
- This PR closes #932 - :close-on-click option wasn't true so I set it true.
=> Mobile menu not opening/closing well #932

src/components/rmrk/Gallery/Item/Sharing.vue
=> Minting success message has correct color

src/components/landing/Spotlight.vue
same size as series
- This PR closes #996
=> fix(spotlight): layout

src/components/rmrk/Gallery/GalleryCardList.vue
I will add ```<ToggleLayout />``` later because I still have a Prop bug
- related to #986
=> fix(toggleLayout): default value incorect

src/components/rmrk/Create/CreateToken.vue, src/components/rmrk/service/NftUtils.ts
=> Added postfix to the classic mint

src/components/rmrk/Create/CreateItem.vue, src/components/rmrk/Create/SimpleMint.vue, src/components/rmrk/Create/mintUtils.ts
- Unknow file type will trigger the second file
- fixed edge case of default state
- Closing #680
=> 680 glb poster

src/components/accounts/utils.ts, src/components/rmrk/Create/SimpleMint.vue, src/locales/en.json, src/utils/mixins/txMixin.ts
- 1046 WIP: sync with airdrop
- 1046 updated translations for finalized tx
- Closing #1046
=> Editions are now synced with the airdrop/distribution list

src/components/landing/Landing.vue
- This PR closes #872 - I added a series link to the homepage because users can know it's a premium feature.
- Fill up your KSM address: https://kodadot.xyz/transfer/?target=<Kusama_Address> 
- [] Are you at KodaDot Discord? yes
=> Add series link to homepage.

src/components/rmrk/Gallery/GalleryItem.vue
This change will disable motion/orientation feature on VIDEO, MODEL, IFRAME & OBJECT.
- This PR closes #1055
=> fix(galleryItem): disable orientation on xr

src/components/rmrk/Gallery/Collections.vue, src/components/rmrk/Gallery/Gallery.vue, src/components/rmrk/Gallery/Pagination.vue, src/components/rmrk/utils.ts
- This PR closes #1036 - Added it for collections and gallery pagination. 
=> #1036 Taking to random pages in pagination component

src/components/rmrk/Gallery/CollectionItem.vue, src/components/rmrk/Profile/ProfileLink.vue, src/router/profile.ts
more like a hotfix
- This PR closes #1027
=> fix(profile): link to subscan on profile page

src/components/rmrk/Gallery/CollectionItem.vue, src/components/rmrk/Gallery/PaginatedCardList.vue, src/components/rmrk/Gallery/Pagination.vue, src/components/spotlight/SpotlightTable.vue, src/views/Profile.vue
👇 Let's do a quick check before the merge. 
)
=> Pagination magic button in collection view, profile and spotlight

src/components/rmrk/Gallery/CollectionActivity.vue, src/components/rmrk/Gallery/CollectionItem.vue, src/components/transfer/DonationButton.vue
👇 Let's do a quick check before the merge.
=> #1037 Put collections status to between artist and actions

src/components/rmrk/Gallery/CollectionItem.vue, src/locales/en.json
=> 1032 description is hidden in the collection detail

src/components/rmrk/Gallery/CollectionItem.vue
👇 Let's do a quick check before the merge.
=> fix(collection): magic btn

src/components/shared/collapse/CollapseWrapper.vue
=> user select is turned off for the collapse wrapper

src/components/rmrk/Gallery/CollectionActivity.vue, src/utils/math.ts
- Closes #1124 fixed distribution count in the collection detail
- Closes #978 show distribution between unique and owners
=> Collection distribution math

src/components/transfer/Transfer.vue
=> #1090 Make copy to clipboard tx link to the Transfer

src/components/landing/Landing.vue, src/components/rmrk/Gallery/Appreciation.vue, src/components/rmrk/Gallery/GalleryItem.vue, src/styles/derived-variables.scss, src/styles/global.scss, src/styles/variables.scss
=> Colors changed

src/components/rmrk/Gallery/Search/query.ts, src/components/series/SeriesTable.vue, src/components/series/types.ts, src/components/series/utils.ts, src/locales/en.json
👇 Let's do a quick check before the merge.
=> Series table

pages/rmrk/admin.vue
👇 Do a quick check before the merge.
=> Nuxt-migration: Fix wrong import for adminPage

icons.ts
=> fix(nuxt): KODA2 missing icons

src/queries/collectionIssuerList.graphql, src/queries/collectionSeriesList.graphql
=> fix(graphql): hide burned nfts

src/queries/nftListCollected.graphql, src/queries/nftListSold.graphql, src/views/Profile.vue
tested on /rmrk/u/CmMkskdeDpSoU2xKnZ214JkgFZKmMCZXoYyJfHYB1X1aihy?tab=sold&search=&listed=true
- PR closes #1170 
- added/fix searchbar on Created/Sold/Collected tab
=> fix(profile): pagination & search

src/components/rmrk/Gallery/CollectionItem.vue
=> #1173 Swap description with tabs on collection

src/components/rmrk/Gallery/Appreciation.vue, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/Gallery/History.vue, src/components/rmrk/Gallery/HistoryPriceChart.vue, src/components/rmrk/Gallery/Item/Detail.vue, src/components/rmrk/Gallery/Item/Name.vue
- [x ] Bugfix
- [x ] Refactoring
- [x ] #958 related
- [ x] My contribution builds **clean without any errors or warnings**
- [ x] I've merged recent default branch -- **main** and I've no conflicts
- [ x] I've tried respect high code quality standards
- [ x] I've didn't break any original functionality
- [ x] I've posted screenshot of demonstrated change in this PR
- Restyling the structure of page.
- Make price chart and history chart as foldable.
- Merge Price box with Actions if it's for Collecting and not the owner of NFT
- When creator, showing rest buttons would be shown.
- [x ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
=> Fixing styles on gallery item page

src/components/rmrk/Gallery/GalleryItem.vue
👇 Do a quick check before the merge.
=> hotfix(GalleryItem): avaible actions not showing

src/components/rmrk/Gallery/AvailableActions.vue, src/components/rmrk/Gallery/GalleryItem.vue, src/components/rmrk/service/scheme.ts, src/main.ts, src/queries/rmrk/verificationGuard.graphql, src/rmrkClient.ts, src/subquery.ts, src/utils/transactionExecutor.ts
:ambulance: half-fix for the random double spend
- :bug: (GalleryItem): removed unsued imports
- :zap: added rmrk grapghql client
- :zap: added Inmemorry cache
- :zap: refactored transaction executor into separated functions
- :zap: added checker before buy
=> Anti-rug mechanism for JPEGs

src/components/rmrk/Gallery/CollectionDetail.vue
=> #1217 Collections on mobile arrangement

src/views/Profile.vue
=> 1120: Hide Created and Sold when collector has 0 created NFTs

src/components/spotlight/SpotlightTable.vue
css is sketchy on spotlight page
=> fix(spotlight): bottom pagination

src/components/rmrk/Gallery/Item/Sharing.vue
=> #1137 Adding webshare api support again

src/views/Profile.vue
=> #1237 Horizontal alignment on profile at collections 

src/components/rmrk/Gallery/GalleryItem.vue
- 👇 Do a quick check before the merge.
=> :fire: Gallery item: it is possible to use actions again

components/shared/SwitchLocale.vue, store/index.ts
🏴‍☠️ La piraterie n'est jamais finie
=> 🏳  sync SwitchLocale

src/components/shared/AddressInput.vue, src/components/shared/DisabledInput.vue, src/components/transfer/Transfer.vue, src/locales/en.json
- Closing #1227
- :egg: Transfer can take any valid address
Closing #1227, #1253
=> 1253 tell your friends about ss58

src/components/rmrk/Gallery/GalleryItem.vue, src/components/transfer/Transfer.vue
=> fix(galleryItem): columns spacing

src/components/rmrk/Gallery/GalleryItem.vue
This change will show fullscreen (larger container) for: VIDEO, MODEL, IFRAME & OBJECT
=> fix(galleryItem): glb & media fullwidth

nuxt.config.js
=> Remove warnings

src/components/rmrk/Gallery/GalleryItem.vue
=> fix(galleryItem): media width

coingecko.ts, components/transfer/Transfer.vue, layouts/default.vue, store/index.ts
=> 🛠  sync coingecko change on main-nuxt

pages/rmrk/u/_id.vue
=> Fix breaking routes in profile when changing tab

src/components/rmrk/Gallery/CollectionItem.vue, src/components/rmrk/Gallery/GalleryItem.vue
#973 support for animated SVG previews
Collections page Vercel preview with amount of collection's item
=> Vercel previews support for collections and svg type

src/components/rmrk/Gallery/GalleryCard.vue
- component could need some rework
=> fix(GalleryCard): resposive nft title

src/components/transfer/Transfer.vue
=> Generate payment link for transfer

Dockerfile, nuxt.config.js, package.json, yarn.lock
- :top: nuxt will be running on the port :9000
- set node engine to 14.17
=> Nuxt on the port :9000

components/rmrk/Create/CreateToken.vue, components/rmrk/Create/PermaMint.vue, components/rmrk/Create/SimpleMint.vue, components/rmrk/Gallery/GalleryCard.vue, components/rmrk/Gallery/GalleryCardList.vue, components/shared/LinkResolver.vue, pages/rmrk/u/_id.vue, yarn.lock
=> 1349 collection navigation issue

components/shared/AddressInput.vue, components/shared/DisabledInput.vue, components/transfer/Transfer.vue, docker-compose.yml
Tested on:
/transfer?usdamount=10&target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU
and it worked well, you need to be logged in.
- Docker-compose port
=> 💸 sync transfer component

Dockerfile, README.md, netlify.toml, nuxt.config.js, src-functions/getKey.js, src-functions/pinFile.js, src-functions/pinHash.js, src-functions/pinJson.js, src-functions/revokeKey.js, src-functions/test.js, src-functions/unpin.js
What's new? 
New build engine for functions - faster, modern approach
We are finally using netlify CLI
New docs
- :zap: updated netlify functions to esbuild
- :compass: 1113 working netlify configuration
- :memo: 1113 ability to run app using netlify CLI
- Haven't updated docker yet
- closes #1113
=> 1113 Netlify functions in Nuxt

netlify.toml
Without this you are unable to visit any subpages directly :)
=> :bug: netlify fails to redirect

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/GalleryItem.vue, docker-compose.yml, pages/rmrk/u/_id.vue
something went wrong on last merge
=> 🐛 a bug's life

components/rmrk/Gallery/GalleryCardList.vue, components/rmrk/Gallery/PaginatedCardList.vue, components/rmrk/Gallery/Pagination.vue, components/rmrk/Gallery/Search/SearchBar.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, components/series/SeriesTable.vue, pages/transfer.vue
Before open issue with bug, be sure to clear your cache.
=> 🐛 router replace path

store/chain.ts
=> 🐛 fix build

components/rmrk/Gallery/Search/SearchBar.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, components/shared/form/BasicSwitch.vue, langDir/en.json, styles/derived-variables.scss, styles/global.scss, styles/initial-variables.scss
=> 1311 change label text and set color to green

components/rmrk/Gallery/CollectionItem.vue, components/shared/view/BasicImage.vue
=> 🐛 sync & fix collectionItem

components/metadata/Metadata.vue
We don't need to watch store state change
=> 🐛 metadata component

src/components/rmrk/Gallery/AvailableActions.vue
- fixing 49a623512af2f108c778ba0a543a7c63dcec6913
=> Boulevard of broken buys

pages/index.vue
=> 🗑  remove prefetch from landing

queries/nftListByCollection.graphql
=> 🔥 hide burned nft from collection stats

.github/workflows/snyk-infrastructure-analysis.yml
=> ⚒️ remove snyk workflow on pull_request

components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Gallery/Item/Detail.vue, components/rmrk/Gallery/Item/Name.vue
- #1426 related
- we need to move _PriceChart_ component outside _History_ component
- don't know what to do with _Facts_ component
- sync GalleryItem
=> 🔄 sync galleryItem

components/shared/Loader.vue, langDir/en.json, utils/calculation.ts
=> 1436 show random fun facts on preloader

components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Gallery/History.vue, langDir/en.json
- some refactoring because monkey brain can't do without copying initial var
=> ✨ rework history component

src/components/rmrk/Media/ModelMedia.vue
=> :zap: #1321 added autoplay for model viewer

src/components/rmrk/Gallery/GalleryCard.vue, src/components/rmrk/Gallery/Layout.vue, src/store.ts
=> :zap: #1467 large display shows 2 items per row small display shows 4

components/shared/Loader.vue
=> 1460  fix: reset funfact each time loader is enabled

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Profile/ProfileLink.vue
=> creator twitter added

components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Gallery/History.vue
=> 1487: Replace facts with chart engine.

components/series/SeriesTable.vue, components/series/types.ts, components/series/utils.ts
- sync series-insights with main
=> 🔄 sync series-insights

components/shared/history/HistoryBrowser.vue, components/shared/history/HistoryBrowserItem.vue, styles/variables.scss
https://user-images.githubusercontent.com/17953978/146058883-0077e920-99b5-4938-97e6-f762ae948680.mov
=> 1509 dont close history browsing on remove

pages/rmrk/u/_id.vue
This is a hot fix.
It happened because page query wasn't initialise after tab change
=> ⚒️  profile route tab change

components/rmrk/Gallery/CollectionPriceChart.vue, components/rmrk/utils.ts
=> 1549 mobile collection price chart size

components/rmrk/Gallery/CollectionPriceChart.vue
=> fix: mobile chart size on landscape mode

components/rmrk/Gallery/Pagination.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, langDir/en.json, pages/rmrk/u/_id.vue
=> #1326 tooltip in profile nuxt

components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Gallery/Item/Navigation.vue, components/rmrk/Media/ImageMedia.vue, components/rmrk/Media/MediaResolver.vue, components/rmrk/Media/ModelMedia.vue, package.json, yarn.lock
https://user-images.githubusercontent.com/17953978/146504501-85c863d1-d338-4f50-8cb4-071ed526cbe3.mov
=> 1245 add poster and description to 3d files in model-viewer

.github/workflows/imgcmp.yml, .github/workflows/reviewdog.yml, .github/workflows/snyk-infrastructure-analysis.yml
=> ⚒️  github workflow

components/rmrk/Faq.vue, langDir/all_lang.json, langDir/en.json, pages/rmrk/faq.vue
=> 1555 link to contributing guide in FAQ

nuxt.config.js
=> 🧼 lint nuxt.config.js

components/rmrk/Gallery/CollectionItem.vue, pages/errorcollection.vue
(https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
=> #1413 Handle non existing collection

components/Navbar.vue, components/rmrk/Create/Admin/AdminPanel.vue, components/rmrk/Create/SimpleMint.vue, components/rmrk/Gallery/Collections.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/rmrk/OnChainProperty.vue, components/shared/Loader.vue, pages/permafrost/create.vue, pages/rmrk/collections.vue, styles/derived-variables.scss, styles/global.scss
=> #1563 NUXT - Make color #d32e79 a scss variable

components/Navbar.vue, langDir/en.json, pages/transform.vue, utils/urlTransformer.ts
=> 🔄 sync Transform

queries/collectionIssuerList.graphql, queries/collectionSeriesList.graphql, queries/nftListWithSearch.graphql
This PR hide burned nfts on /gallery, /spotlight, and /series-insight
#679, #1168 related
closes #1167
=> 🔥 hide burned nfts 

components/rmrk/Gallery/Item/Sharing.vue, components/rmrk/Pack/PackItem.vue, components/unique/Collection/Item/CollectionItem.vue, langDir/en.json, pages/rmrk/u/_id.vue, pages/statemine/u/_id.vue, pages/westmint/u/_id.vue
=> 1462 fix hastags in twitter and facebook sharing

CONTRIBUTING.md
=> Fix minor typographical errors in CONTRIBUTING.md

components/Footer.vue, langDir/en.json
=> 1600 Add link to presskit to the footer

pages/settings.vue
=> #1607 Make advanced settings addressable url

components/shared/Loader.vue, utils/icons.ts
=> #1603 Change background colour for loader

components/rmrk/Gallery/Gallery.vue
=> ⚒️ open in new tab gallery item

components/rmrk/Gallery/GalleryItem.vue, components/unique/Gallery/Item/GalleryItem.vue
Why do we have duplicated component?
=> ⚒️ remove unused css & fix border on qr code

components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/settings/Interface.vue, store/preferences.ts
=> #1585 Hide prices from UI

components/rmrk/Gallery/AvailableActions.vue
=> #1289 Make submit buy direct on Nuxt

components/landing/Landing.vue, pages/index.vue
=> ⚒️ landing layout

components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Media/MediaResolver.vue, components/rmrk/Media/ModelMedia.vue
https://user-images.githubusercontent.com/17953978/147878908-8720c0f9-cc72-4f46-80f3-996e0e5fc381.mov
=> 1656 enable animations in model-viewer

.github/workflows/diagram.yml
=> FEAT: added [skip ci] to repo-visualizer

components/Navbar.vue, components/rmrk/Gallery/Collections.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/rmrk/Gallery/Search/SearchBar.vue, pages/rmrk/collections.vue, styles/global.scss
=> #1669 Remove glowing effect from everywhere

components/spotlight/SpotlightTable.vue, queries/rmrk/subsquid/collectionSeriesList.graphql, queries/rmrk/subsquid/collectionSpotlightList.graphql
Close #1663
- :zap: spotlight shows volumme and unique collectors
- :zap: series shows volumme and total buys
=> We :octopus: stats

pages/rmrk/collections.vue, queries/collectionListWithSearch.graphql
=> 🔄 sync collections search

components/shared/Avatar.vue
=> 1684 :dolphin: identicon returned

.dockerignore, Dockerfile, docker-compose.yml
I'm back (until it break again)
=> ✨ docker magic

package.json, yarn.lock
https://github.com/vue-polkadot/ui/commit/249e8dcce2dfccb1ffd0e64244cae3109f2569f4
Close #1702
=> :electric_plug: 1702 updated subquery autobalance endpoint

components/series/SeriesTable.vue, components/spotlight/SpotlightTable.vue
=> #1667 Add preloader to spotlight & series

components/rmrk/Create/CreateItem.vue, components/rmrk/Create/CreateToken.vue, components/rmrk/Gallery/Collections.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/rmrk/service/NftUtils.ts, pages/rmrk/collections.vue, styles/global.scss
- :bug: NFTUtils now use collectionID instead of symbol
- :bug: correct resolution of collectionId
- :art: #363636 is $grey-darker
- Close #1713
=> 1713 no mint for you

components/rmrk/service/types.ts
Used: [GraphQL Code Generator](https://www.graphql-code-generator.com/)
=> :label: generated GraphQL types

components/rmrk/Gallery/Item/Navigation.vue
=> 1719 fix collection navigation keyevent bug

components/CookieBanner.vue, components/Footer.vue, langDir/en.json, nuxt.config.js, package.json, plugins/vueGtag.ts, tsconfig.json, yarn.lock
continue #1730 
- setup ga4 with vue-gtag
=> ✨ analytics GPDR ready #

components/CookieBanner.vue, components/Footer.vue, langDir/en.json, nuxt.config.js, package.json, tsconfig.json, yarn.lock
=> ✨ analytics GPDR ready

components/rmrk/Profile/ProfileLink.vue
=> #1728 Dotscanner profile missing text

components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/Search/SearchBar.vue
=> 1655 Fix Search input suggestions and search history

components/accounts/AddressParser.vue, components/rmrk/Create/Admin/AdminPanel.vue
=> Admin Panel Fixes

.github/PULL_REQUEST_TEMPLATE.md
Edited PR template to show "What's New" at the top
=> ✨ pr template text

components/rmrk/Media/ImageMedia.vue
=> #1733 NFT item detail extra pixel spacing border

components/rmrk/Gallery/CollectionItem.vue, langDir/en.json, pages/transform.vue
=> Add middleware to redirect transformed link

plugins/vueGtag.ts
=> 📊 implement google analytics env

components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/GalleryItem.vue, styles/global.scss
=> Add 💸 cursor on buy button

components/CookieBanner.vue, nuxt.config.js, package.json, tsconfig.json, yarn.lock
=> 📊 replace nuxt-analytics config with vue-gtag

Dockerfile
=> snyk thinks it has vulnerabilit if not explicitly specified

pages/rmrk/collections.vue
=> #1792 Fix Prefetch warnings on collections page

components/rmrk/Gallery/PriceChart.vue
=> Fixed chart updating error

package.json, yarn.lock
- :test_tube: :construction: configured jest
- fix: navigation errors
- chore: unused PostCSS
- feat: adding rmrk logo
- chore: rmrk logo
- feat: add h1 and h2 to spotlight
- :construction: maaaybe?
- fix: circumvent opengraph namespace caching
- Fixed chart updating error
- Working JEST <3
- :truck: shuffling jest deps
- :bug: added @babel/plugin-proposal-private-property-in-object for the tests
=> :soap: Hyper Hyper

components/rmrk/Profile/IdentityForm.vue, components/rmrk/Profile/NavbarProfileDropdown.vue
=> #1748 adding identity option

static/service-worker.js
=> 🧼 lint service-worker

components/Navbar.vue, components/shared/IdentityPopover.vue, components/shared/SwitchLocale.vue, styles/derived-variables.scss, styles/variables.scss
=> feat: hover card msdos shadow and pink border

components/rmrk/Gallery/Search/SearchBarCollection.vue, components/rmrk/Gallery/Search/SearchSortDropdown.vue
=> #1793 Make dropdown for filter and search bar narrow

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/rmrk/Gallery/GalleryCardList.vue, components/settings/Interface.vue, store/preferences.ts
https://user-images.githubusercontent.com/17953978/149622680-0d1ea104-065c-4b56-a9f6-9c4aa4a51d68.mov
=> fix: reimplement logic when prices are shows and add preference

components/shared/Loader.vue, langDir/en.json
added two facts as well 
https://user-images.githubusercontent.com/39299315/149616278-6eb6289b-e36d-462d-8065-bc0a33bcda22.mp4
=> #1804 Change facts in preloader after 10 seconds

components/rmrk/Create/mintUtils.ts, utils/WithKeyring.ts, utils/api/Query.ts, utils/chain.ts, utils/icons.ts, utils/proxy.ts, utils/teleport.ts
=> evening performance training

components/rmrk/Gallery/GalleryItem.vue, components/shared/AccountSelect.vue, components/shared/Support.vue, utils/groupBy.ts
=> 🧼 room service

components/spotlight/SpotlightDetail.vue
=> ⚒️  spotlight detail

package.json
=> 🚧 lint on commit

components/shared/Auth.vue
=> #1944 Hide Identity popover on Auth

components/rmrk/Create/SimpleMint.vue
=> Hyper Statemine

renovate.json
=> will it work

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/reviewdog.yml, .github/workflows/snyk.yml, nuxt.config.js, package.json
=> 🤖 Build workflow

components/CookieBanner.vue, components/Navbar.vue, components/shared/IdentityPopover.vue, components/shared/Loader.vue
=> #1942 Cookie banner seeking shadow

langDir/all_lang.json, langDir/en.json, pages/rmrk/faq.vue
=> feat: updated faq with new data

pages/transform.vue
https://user-images.githubusercontent.com/17953978/150518583-ae9d9d45-ba08-4c04-99d1-5e32c7784cb4.mov
=> fix: transformer needs to use right url to begin with 😄 

components/Navbar.vue
=> feat: add tooltips to create options

components/accounts/AddressParser.vue, components/rmrk/Create/SimpleMint.vue
=> fix: add more meaningful placeholder to minting process

pages/rmrk/index.vue, pages/statemine/create.vue, pages/statemine/index.vue, pages/westmint/create.vue, pages/westmint/index.vue
Note:
Why can't I resolve my Identity on local environment ?
=> ⚒️  prefix layouts

langDir/en.json, pages/teleport.vue, pages/transfer.vue
- :zap: hide KSM when you are on other chain
- :zap: teleport will tell you where you are sending money
=> Teleport will tell you where are you teleporting money

.github/PULL_REQUEST_TEMPLATE.md
=> Updating typos in PULL_REQUEST_TEMPLATE

components/rmrk/Gallery/History.vue
=> ⚒️  SEND event Amount

components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/Pagination.vue, components/rmrk/Gallery/Search/SearchBar.vue
https://user-images.githubusercontent.com/17953978/151202027-7c809074-b04f-4016-93c5-3010c805a59f.mov
=> fix: rework searchbar to be more space efficient 💻 

nuxt.config.js, package.json, tsconfig.json, yarn.lock
=> chore: remove unnecessary i18n dependencies

static/.well-known/security.txt
=> feat: add security txt file

components/rmrk/Gallery/GalleryItem.vue
=> #2094 - Rework actions component bit

pages/esCarbonless.vue
=> #2050 esCarbonless spanish route not working in about section

pages/esSustainability.vue
=> #2052 esSustainability spanish route not working in about section

components/rmrk/Gallery/Item/Navigation.vue
=> #2088-mobile-dropdown-menu-fix

components/rmrk/Gallery/GalleryItem.vue
Reverts kodadot/nft-gallery#2105
=> Revert "#2094 - Rework actions component bit"

components/Footer.vue, styles/variables.scss
https://user-images.githubusercontent.com/39299315/151707086-847a262b-4d97-40a9-887a-5fea28f08f6f.mov
=> #2117 Add shade to footer by default, show on hover

utils/api/Query.ts, utils/support.ts, yarn.lock
=> :parachute: correct ss58 format is finally correct

components/rmrk/Gallery/CollectionItem.vue, utils/api/Query.ts, utils/support.ts, yarn.lock
=> Hyper Fees

queries/nftListCollected.graphql, queries/nftListSold.graphql, queries/unique/nftListCollected.graphql, queries/unique/nftListSold.graphql
=> ⚒️  profile order by on Sold/Collected tab

components/Navbar.vue, components/rmrk/Create/CustomAttributeInput.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, components/shared/ChainSelect.vue, components/shared/SwitchLocale.vue, components/shared/collapse/CollapseCardWrapper.vue, components/shared/gallery/BaseGalleryItem.vue, components/shared/history/HistoryBrowser.vue, components/unique/Collection/Item/CollectionItem.vue, components/unique/Create/CreateCollection.vue, components/unique/Create/CreateToken.vue, components/unique/Gallery/Item/GalleryItem.vue, components/unique/Gallery/Item/Properties.vue, pages/statemine/u/_id.vue, pages/teleport.vue, pages/transfer.vue, pages/westmint/u/_id.vue, styles/global.scss
=> "Last" bugs for Statemine

components/shared/ChainSelect.vue, utils/mixins/subscribeMixin.ts
- :zap: subscribe mixin wont stop the app
- :lipstick: network change will push you to the landing page
=> random bugs around

middleware/prefix.ts, package.json, tests/prefix.spec.ts, yarn.lock
- :top: updated vuex-options
- :zap: reworked middleware into the v1
- :test_tube: written tests for the prefix middleware
=> 2160 prefixes v1

components/rmrk/Gallery/AvailableActions.vue
=> #2138 Show Tweet about recent purchase with creator Twitter 

components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/GalleryItem.vue
=> #2188 Twitter sharing bugs

components/series/SeriesTable.vue, components/shared/format/Money.vue, components/spotlight/SpotlightTable.vue
thanks @roiLeo for correcting it. 
=> #2156 Remove KSM from Spotlight & Series insight

components/rmrk/Gallery/GalleryItem.vue, queries/nftByIdMinimal.graphql
- :zap: current owner and price is fetched every second
- :mute: remove log from gallery item
=> 2137 auto-polling on the NFT detail

components/rmrk/Gallery/GalleryItem.vue, components/shared/gallery/BaseGalleryItem.vue
=> fix: emit hover event to enable navigation again

package.json, yarn.lock
=> added @babel/plugin-transform-runtime

FIRST_TIME.md
- :memo: updating first time docs
- :docs: grammar magick
=> viki is making docs

components/common/RampCredit.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, package.json, yarn.lock
At the moment it's for KSM but it could be done depending on the choice of the indexer/prefix
=> ✨ Ramp Credit KSM account

components/rmrk/Gallery/CollectionItem.vue, components/shared/collapse/DescriptionWrapper.vue
=> #2208 Show only first row from description at collection

components/base/CarouselCardList.vue, components/rmrk/Gallery/Appreciation.vue, components/rmrk/Gallery/LatestSales.vue, components/rmrk/Gallery/Pagination.vue, components/shared/collapse/DescriptionWrapper.vue, components/shared/format/Identity.vue
In general: 
- Refactored Emoji Picker with minimark
- Added types to component's props
- Fine tuned @roiLeo 's carousel so it won't throw error
- EmojiPicker has now simple option // Send ❤️ directly
=> Hyper refactoring

components/base/CarouselCardList.vue, package.json
- :bug: default height on description wrapper was incorrect
- :zap: refactored appreciation
- :technologist: added types to the pagination
- :lipstick: can now directly send heart from main screen
- :technologist: Appreciation is using minimark
- :bug: pagination err on latest sales
- :bug: appreciation is going away
- :art: terrible css fix
- :art: two plus one free
- :wrench: prettier semiqoute true
=> HyperCSS Wao

nuxt.config.js
=> ⚒️ remove dev warning

.github/renovate.json, components/rmrk/Gallery/CollectionActivity.vue, components/rmrk/Gallery/CollectionDetail.vue, components/rmrk/Gallery/CollectionItem.vue, queries/collectionStatsById.graphql
I rewrote the query using aggregation
- :alien: query for collection stats
- :zap: CollectionActivity is using new query
- :technologist: CollectionDetail was missing a name
- :bug: totalListed was throwing an apollo err
- :mute: removed console.log
=> (#1850) Aggregating Collection data

nuxt.config.js, plugins/globalVariables.ts, plugins/icons.ts
=> 🧹 move icons to plugins

nuxt.config.js, plugins/globalVariables.ts, utils/WithKeyring.ts, utils/directUpload.ts, utils/extension.ts, utils/mixins/queryMixin.ts
=> fix: Invalid Promise-like handling.

plugins/endpoint.ts, plugins/keyboardEvents.ts, plugins/polkadot.ts, utils/empty.ts, utils/mixins/keyboardEventsMixin.ts
=> chore: add function return types

components/rmrk/Gallery/Search/SearchBar.vue
=> #2100 - search url doesn't update

components/series/SeriesTable.vue
=> ⚒️ owners column in series

components/Navbar.vue
=> ✨ better navbar search design

.github/workflows/build.yml, .github/workflows/reviewdog.yml, FIRST_TIME.md, package.json
=> ⚒️ github workflow node version

components/rmrk/Gallery/GalleryItem.vue
=> ⚒️ galleryItem id with hash

components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/Search/SearchBar.vue
=> #2385 Remove extra search bar at gallery feed

LEADERBOARD.md
=> [skip netlify] update_leaderboard

.eslintrc.js, README.md
=> feat: added readme link to storage article

components/rmrk/utils.ts, middleware/prefix.ts, plugins/keyboardEvents.ts, plugins/seoMetaGenerator.ts, store/indexer.ts, tests/prefix.spec.ts, utils/fetch.ts, utils/filters.ts, utils/ipfs.ts, utils/mixins/queryMixin.ts, utils/seoImageGenerator.ts
=> fix: template literal expression having a non-string type.

components/rmrk/Gallery/CuratedList.vue
=> ✨ landing UI carousel update

components/landing/Landing.vue
=> ⚒️ landing prefix

components/rmrk/Gallery/CuratedList.vue
=> fix: b-carousel prop error and cls issue

components/Footer.vue
=> #2018 Removing from landing page footer

langDir/pt.json
=> Updating portuguese Language

components/Footer.vue, components/accounts/AddressParser.vue, components/base/CollectionSelect.vue, components/common/FrequentlyAsked.vue, components/rmrk/Create/Admin/AdminPanel.vue, components/rmrk/Create/AttributeTagInput.vue, components/rmrk/Create/CreateCollection.vue, components/rmrk/Create/CreateItem.vue, components/rmrk/Create/SimpleMint.vue, components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/History.vue, components/rmrk/Gallery/Pagination.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, components/rmrk/Profile/ProfileDetail.vue, components/series/SeriesTable.vue, components/series/utils.ts, components/shared/Auth.vue, components/shared/Loader.vue, components/spotlight/SpotlightTable.vue, components/spotlight/utils.ts, components/unique/Create/CreateItem.vue, nuxt.config.js, utils/config/i18n.ts
=> refactor: streamline and cleanup i18n 📦 

components/rmrk/Gallery/Search/SearchBar.vue, components/rmrk/Gallery/Search/types.ts
https://user-images.githubusercontent.com/38389586/155739763-b35b3cc0-50e1-4dd2-9a39-e1c79a4e88d8.mp4
=> feat(SearchBar): Categorize search results in search bar

package.json
👇 \_ Let's make a quick check before the contribution
My internet connection is a bit poor right now. So testing via netlify ;D
=> :top: updated sub-api to rc.3

utils/config/wallets.ts, utils/extension.ts
=> ✨ mobile wallet connect

components/base/BaseCollectionForm.vue, components/base/BaseTokenForm.vue
=> :zap: limit chars for collection/token name to 60 chars

components/rmrk/Profile/ProfileDetail.vue
=> :bug: fix broken artist detail

components/rmrk/Gallery/Search/SearchBar.vue
=> fix[#2447]: optimize replaceUrl of SearchBar

components/shared/gallery/BaseGalleryItem.vue, plugins/icons.ts
=> feat: add tile art mode to item page

components/series/SeriesTable.vue
=> #2489 Sticky header broken at Series Fix

CONTRIBUTING.md
=> Update Contributing.md with PR update strategy

components/rmrk/Create/SimpleMint.vue
https://user-images.githubusercontent.com/38389586/156399796-b38935a7-3524-424d-9a2e-52b0fdd69731.mp4
=> feat: Generate symbol at simple mint from name

components/common/WalletModal.vue, components/rmrk/Collection/List/CollectionList.vue, components/rmrk/Gallery/Collections.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryCard.vue, components/shared/Loader.vue, styles/variables.scss
=> fix: hover aero style

pages/transfer.vue, store/index.ts, utils/network.ts
=> fix: disable submitting before RPC api connected

components/shared/collapse/DescriptionWrapper.vue
https://user-images.githubusercontent.com/31397967/158065737-4cf0dcc1-bc79-40a9-9fd0-3d9954a1c881.mp4
=> fix: link unclickable on ios safari

components/rmrk/Gallery/CollectionItem.vue, utils/sorting.ts
How someone has managed to bypass husky pre-commit hook?
=> ⚒️ linting errors

CONTRIBUTING.md
I took my friend (Grammarly) for a short walk and we tackled a ton of typos in CONTRIBUTING.md.
Moreover, we clarified the urgency with the p1 issues
=> :memo: fixing typos through the document and clarifying p1 labels

plugins/keyboardEvents.ts, tests/keyboardEvents.spec.ts, utils/keyboardEvents.ts, utils/mixins/keyboardEventsMixin.ts
=> fix: ignore keyboard event in input

components/rmrk/Gallery/History.vue
=> #2582 Pagination on history collection component fix on mobile

components/rmrk/Profile/IdentityForm.vue, components/rmrk/Profile/ProfileDetail.vue
=> #1262 Nudge to set on-chain identity on profile 

tests/keyboardEvents.spec.ts, utils/keyboardEvents.ts
=> fix: keyboard shortcut on creat page

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/History.vue, queries/rmrk/subsquid/allCollectionSaleEvents.graphql
https://user-images.githubusercontent.com/734428/158996881-4e396c85-7b23-46ee-a327-f05233a6fafe.mov
=> #2561 add name and id in collection history

components/rmrk/Gallery/Search/SearchBar.vue
=> fix: searchbar at index page wont redirect to search result

components/rmrk/Collection/List/CollectionList.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/Pagination.vue
=> fix: Sharing search url with page number is broken

utils/sorting.ts
=> #2599 Sort ascending

components/rmrk/Profile/ProfileDetail.vue
=> fix: showing name instead of address

components/rmrk/Collection/List/CollectionList.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, components/rmrk/Gallery/Search/SearchSortDropdown.vue
=> fix: remove price sort in collection

components/rmrk/Gallery/CollectionItem.vue
=> fix: Collection pagination

components/common/WalletModal.vue
=> ffix: subwallet account does not work

store/preferences.ts
=> :eyes: default view in the NFT detail

components/spotlight/SpotlightTable.vue
=> #2604 Spotlight Magic button seems to overlap Pagination buttons fix

langDir/en.json
=> #979 Sort NFT by most sales asc/dsc

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/History.vue
=> #2667 Remove top-border on history component when used in collection

components/rmrk/Gallery/Gallery.vue, components/shared/Error.vue, layouts/centered-half-layout.vue, layouts/default.vue, layouts/full-width-layout.vue, pages/error.vue
Refs: #2249
[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://vimeo.com/691279398/57ca12d273)
=> feat: handle offline screen

components/Footer.vue, langDir/en.json
=> add contribution to footer

components/rmrk/Gallery/LatestSales.vue, components/rmrk/Gallery/NewestList.vue, nuxt.config.js
=> :bug: adding legacy subsquid because 005 is currently not working

langDir/en.json, langDir/id.json
=> swap text in sort by price

components/base/CarouselCardList.vue
=> fix: remove scroll bar

components/series/SeriesTable.vue
=> fix abnormal sorting  arrow

components/rmrk/Gallery/History.vue
=> :bug: isOpen property was set badly in History

components/rmrk/Gallery/GalleryItem.vue
=> update cached name on 3d assets

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/Holder/Holder.vue, components/rmrk/Gallery/Holder/helper.ts
=> feat: add collection holder tab

components/shared/gallery/BaseGalleryItem.vue
https://user-images.githubusercontent.com/31397967/160280712-c78c5824-a1f3-46b3-ab9a-ebb1ea73cff7.mov
=> fix: disable theater mode on mobile

components/settings/Interface.vue, components/shared/gallery/BaseGalleryItem.vue, langDir/en.json, store/preferences.ts
=> #2656 Adding enabling gyro effect to preferences

components/shared/IdentityPopover.vue
=> #2735 Show user Twitter on hover card

components/rmrk/Gallery/Holder/Holder.vue
=> Implement sorting by date under holders address

CONTRIBUTING.md
=> docs(CONTRIBUTING): update how to receive rewards

components/rmrk/Profile/ProfileDetail.vue
in profile page
the address show `undefined` when have not add on-chain recognition.
for example: https://kodadot.xyz/rmrk/u/ErQqbvyhYWe4h4GiK6eUhNsfBpemVZU8jkNPRp5ZEz5XpbN
no identity:  
has identity:
=> add fallback user name

components/rmrk/Gallery/CollectionActivity.vue, langDir/en.json
=> justify collection stats with max buy

components/series/SeriesTable.vue
=> #2767 Link from series insight to collection chart fix

components/Navbar.vue, components/landing/Landing.vue
=> ⚒️ mobile landing

components/rmrk/Gallery/Holder/Holder.vue, components/rmrk/Gallery/Holding.vue, components/rmrk/service/scheme.ts, components/shared/format/Identity.vue, queries/rmrk/subsquid/allNftSaleEventsByAccountId.graphql
1.  add hover artist card to holdings
2. refactor: remove `any` type on holder\holding component  cc @roiLeo
=> Add hover artist card to holdings 

queries/rmrk/subsquid/collectionEntityById.graphql
=> #2774 Extended number of items from collection at item

queries/rmrk/subsquid/allCollectionSaleEvents.graphql, queries/rmrk/subsquid/lastNftListByEvent.graphql
=> #2738 Hiding the burned nfts

.github/renovate.json
=> Adjust renovate with minor/patch only

components/Navbar.vue, components/rmrk/Gallery/Appreciation.vue, components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/Item/Navigation.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, components/shared/gallery/BaseGalleryItem.vue, styles/global.scss, styles/variables.scss
1px on buttons
2px on buy button
=> justify border style

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/Flipper.vue, components/rmrk/Gallery/Holder/Holder.vue, components/rmrk/Gallery/Holder/helper.ts, components/rmrk/Gallery/Holding.vue, utils/filters.ts
=> feat: Add Flippers to Collection

components/rmrk/Gallery/Holder/Holder.vue
=> add average gain on flippers

components/series/SeriesTable.vue
=> #2489 Sticky header broken at Series

components/rmrk/Collection/List/CollectionList.vue
=> ⚒️ collections listed filter

.github/renovate.json, package.json, pnpm-lock.yaml
=> renovate bot - unify minor and patch

.github/workflows/diagram.yml
=> fix: diagram workflow issue

.github/workflows/diagram.yml
=> fix: using different branch to PR

components/rmrk/Gallery/CuratedList.vue
=> ✨ Kusama Bot on landing curated list

nuxt.config.js, package.json, pnpm-lock.yaml
=> chore: bump model-viewer and transpile via babel

components/Footer.vue, plugins/icons.ts
=> #2886 instagram link on landing page

components/rmrk/Collection/List/CollectionList.vue
=> ⚒️ collections filter align

langDir/en.json, langDir/id.json
=> fix typo signer

ACTIVITY.md, README.md
- [x ] Refactoring
- [ x] PR closes #2899 >
=> cleaned readme added activity

components/rmrk/Gallery/Search/SearchBar.vue
=> feat: show popular collections as default suggestions

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/PaginatedCardList.vue, queries/collectionById.graphql, queries/nftListByIssuer.graphql, queries/nftListCollected.graphql, queries/nftListSold.graphql
=> ✨ show emoteCount & sort by most reacted 

components/Footer.vue, langDir/en.json, langDir/id.json, langDir/pt.json
=> chore: update footer links

components/rmrk/Gallery/History.vue, components/rmrk/Profile/ProfileDetail.vue, queries/rmrk/subsquid/allEventsByProfile.graphql
1. Fix naming from `profil` to `profile` 
2. delete some unused functions and variables
walk through any page index without error
=> bugfix and refactor: History tab at Profile

components/rmrk/Profile/NavbarProfileDropdown.vue, langDir/en.json
=> ⚒️ teleport page name

components/rmrk/Gallery/Search/query.ts, components/series/SeriesTable.vue, components/series/types.ts, langDir/en.json, langDir/id.json, langDir/pt.json, queries/rmrk/subsquid/seriesInsightList.graphql
=> feat: emoteCount

components/rmrk/Gallery/History.vue
=> fix: unlist event does not display emoji at history

components/rmrk/Profile/ProfileDetail.vue, langDir/en.json, queries/nftListByIssuerAndOwner.graphql
=> feat: Show whale collected nfts from particular creator

CONTRIBUTING.md
=> feat: contributing.md updated (assign bot change)

components/rmrk/Gallery/Search/SearchBar.vue
=> fix: Relocate first page query in searchbar

.deepsource.toml, components/Navbar.vue, components/common/WalletModal.vue, components/rmrk/Create/SimpleMint.vue, components/rmrk/Gallery/CollectionItem.vue, components/settings/KeyboardShortcuts.vue, utils/mixins/infiniteScrollMixin.ts
=> 🧹 deepsource issues

components/rmrk/service/NftUtils.ts, components/rmrk/utils.ts, pnpm-lock.yaml
=> ⚒ unwrap warning & pnpm outdated

styles/global.scss
=> fix contrast after mint

README.md
=> chore: updated readme with public good writing

utils/mixins/txMixin.ts
=> fix: Missing translation at loader

components/common/RampCredit.vue, components/rmrk/Gallery/Item/Facts.vue, nuxt.config.js, pages/rmrk/collection/_id.vue, pages/westend/collection/_id.vue, src-functions/getKey.js, src-functions/pinFile.js, src-functions/pinHash.js, src-functions/pinJson.js, src-functions/revokeKey.js, src-functions/test.js, utils/cloudflare.ts, utils/coingecko.ts, utils/constants.ts, utils/directUpload.ts, utils/pinata.ts, utils/pinning.ts, utils/proxy.ts, utils/seoImageGenerator.ts
=> Add global urls list to constants file to have it in one place

components/rmrk/Gallery/LatestSales.vue, components/rmrk/Gallery/NewestList.vue
=> #3086 show passion in landing length check

components/common/WalletModal.vue, langDir/en.json
=> #2615 Adding nudge in wallet auth

components/rmrk/Profile/ProfileDetail.vue
=> fix: responsive design for Artist profile

components/rmrk/Profile/ProfileDetail.vue, queries/nftListByIssuerAndOwner.graphql, queries/subsquid/general/nftListByIssuerAndOwner.graphql
- :alien: response from nftListByIssuerAndOwner aliased to nftList
- :alien: nftListByIssuerAndOwner in subsquid
- :zap: resolve query path for nftListByIssuerAndOwner
=> 3119 franks favourite color is sky blue

components/bsx/Gallery/Item/GalleryItem.vue
=> bugfix(bsx): fix metadata error

components/shared/IdentityPopover.vue
- [x ] I've posted a screenshot of demonstrated change in this PR
=> fix: IdentityPopover component show 0 

components/rmrk/Gallery/Item/Name.vue
=> 🔧 improve seo in galleryItem

components/bsx/Gallery/Item/GalleryItem.vue, components/unique/Gallery/Item/Properties.vue
=> fix: Traits table broken

components/Navbar.vue
https://user-images.githubusercontent.com/38389586/173215112-f8cee62f-e45f-4f5f-a7e9-c9430c924b59.mp4
=> bugfix(navbar): show all tabs when switching to mobile version(low width)

components/rmrk/Gallery/CollectionItem.vue
- Go to beta.kodadot.xyz
- click on any collection in curated list
- fail to retreive collection data
=> 🔧 rmrk collection item

package.json, pnpm-lock.yaml
=> 3162 Adjust Basilisk to Basilisk (testnet)

components/rmrk/Gallery/Search/SearchSortDropdown.vue
=> fix: SearchSortDropdown Invalid default value for prop

components/shared/IdentityPopover.vue, queries/subsquid/general/userStatsByAccount.graphql, queries/userStatsByAccount.graphql, utils/queryPathResolver.ts
=> fix: import unimplemented query error on bsx

components/rmrk/Gallery/Search/SearchBar.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue, components/rmrk/Gallery/Search/SearchSortDropdown.vue
the problem came from  PR #3172 and I found a better solution to deal with it.
=> fix: remove useless params on url

components/rmrk/Gallery/Holding.vue, components/rmrk/Gallery/UserGainHistory.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, components/rmrk/Profile/ProfileDetail.vue, components/shared/BalanceInput.vue, langDir/en.json, pages/transfer.vue, queries/subsquid/general/nftListWithSearch.graphql
=> fix: snek bugs

queries/subsquid/general/firstNftByIssuer.graphql, queries/subsquid/general/nftListByIssuer.graphql, queries/subsquid/general/nftListCollected.graphql, queries/subsquid/general/nftListSold.graphql
=> fix: fix tabs at profile detail

components/bsx/Gallery/Item/Properties.vue, components/bsx/Offer/OfferList.vue, langDir/en.json
=> 🇬🇧  missing translation

components/bsx/Offer/OfferList.vue, components/bsx/specific/DestroyCollection.vue, components/rmrk/Gallery/CollectionItem.vue, queries/subsquid/general/collectionBurnableStats.graphql
=> :snake: Last Snekmass

components/rmrk/Gallery/GalleryItem.vue, queries/nftById.graphql
=> 🔧 GalleryItem collection link

utils/constants.ts
https://user-images.githubusercontent.com/22471030/174808107-52c387f0-6363-47c8-8467-4310ec321fab.mov
=> :coffin: Sunset rubick 004

components/rmrk/Gallery/CollectionItem.vue
=> fix collection names

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/History.vue, components/rmrk/Profile/ProfileDetail.vue
=> Add item into history events of collection

components/bsx/Gallery/Item/GalleryItem.vue, components/rmrk/service/scheme.ts, components/shared/format/Money.vue, langDir/en.json, queries/subsquid/general/nftById.graphql, utils/royalty.ts
=> feat: show nft royalties on basilisk

utils/gallery/media.ts
=> Audio NFT player

CONTRIBUTING.md
=> chore: link to tech stack article

pages/bsx/index.vue, pages/rmrk/index.vue, pages/statemine/index.vue, pages/westend/index.vue, pages/westmint/index.vue
=> #3237 Redirecting routes to index

components/bsx/Gallery/Item/GalleryItem.vue, utils/gallery/media.ts
=> fix unsupported file on bsx

components/rmrk/Gallery/History.vue, langDir/en.json, utils/historyEvent.ts
=> feat: Show royalties in History component for bsx

components/bsx/Create/RoyaltyForm.vue, components/shared/form/BasicSlider.vue, langDir/en.json
=> feat: better tooltip for royalty slider

components/bsx/Offer/OfferStats.vue, components/bsx/Offer/OfferTable.vue, components/bsx/Offer/StatsOverview.vue, langDir/en.json, queries/subsquid/bsx/offerList.graphql
> - I guess adding sorting default by recent on top would be best
> - Add headline/title that it's "Basilisk Marketplace Statistics"
> - resize columns, so date & item don't create new line
=> feat: Add ability to sort bsx marketplace stats

components/rmrk/Gallery/CollectionItem.vue
=> fix: BUY now switch is disabled on /collection/{id}

components/bsx/Gallery/Item/AvailableActions.vue, components/bsx/Gallery/Item/GalleryItem.vue, components/bsx/Offer/OfferList.vue, components/rmrk/Gallery/Item/ActionList.vue, components/rmrk/Gallery/LatestSales.vue, langDir/en.json, styles/global.scss
=> #3202 Disable make offer button after offer was made

components/landing/CuratedList.vue, utils/support.ts
=> 🧹 remove kusamurai & fix ts error

components/rmrk/Gallery/History.vue, pnpm-lock.yaml
=> fix: Relative time link on BSX

components/rmrk/Gallery/LatestSales.vue, components/rmrk/Gallery/NewestList.vue, queries/rmrk/subsquid/lastNftListByEvent.graphql
=> feat: support passion feed searching

components/bsx/Create/RoyaltyForm.vue, langDir/en.json
=> modify unclear text about royalty

components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/Item/ActionList.vue, langDir/en.json, utils/shoppingActions.ts
=> #3276 Minor change in label of make offer

components/bsx/Create/CreateToken.vue, langDir/en.json
=> feat: List NFT for sale switch

components/bsx/Offer/OfferTable.vue
=> feat: no wrap for each column in `bsx marketplace stats`

components/shared/format/Money.vue
=> format price on bsx

components/bsx/Offer/OfferTable.vue
=> feat: calculate 14days expiration for `offer`

components/bsx/Gallery/Item/GalleryItem.vue
=> Show available balance at gallery item at Basilisk

components/bsx/Gallery/Item/AvailableActions.vue
=> Make sure if user has enough funds to make offer

queries/subsquid/bsx/offerList.graphql
=> fix: BSX stats currently showing burned NFTs

components/bsx/Offer/OfferStats.vue, components/bsx/Offer/OfferTable.vue, pages/bsx/stats.vue
=> Center table at BSX stats and handle longer item names

components/rmrk/Collection/List/CollectionList.vue, components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/Search/SearchBarCollection.vue
https://user-images.githubusercontent.com/17953978/178101881-d75753fa-7f3b-4d93-8844-c90f63580a19.mov
=> fix: buy now switch in searchbar

components/rmrk/Gallery/CollectionItem.vue, components/rmrk/Gallery/Gallery.vue, queries/subsquid/general/collectionById.graphql, queries/subsquid/general/nftListWithSearch.graphql
=> fix: Pagination and infinity scrolling is broken on Basilisk & Moonsama

components/bsx/Gallery/Item/AvailableActions.vue
=> fix: unable to click submit button on bsx

components/bsx/Offer/OfferTable.vue
=> fix: I can accept my own offer for nft Ive bought

components/rmrk/Profile/ProfileDetail.vue
=> :bug: disabled heavy queries for profile

components/rmrk/Gallery/Search/SearchBar.vue
=> :snake: Searching in bsx wont teleport you to rmrk

pages/bsx/index.vue, pages/moonsama/index.vue, pages/rmrk/index.vue, pages/statemine/index.vue, pages/westend/index.vue, pages/westmint/index.vue
=> #3430 curated list doesnt change with chain/prefix change

components/bsx/Gallery/Item/GalleryItem.vue, components/moonsama/Gallery/Item/GalleryItem.vue, components/unique/Gallery/Item/GalleryItem.vue
=> fix: Wrap long description on gallery item

components/bsx/Gallery/Item/AvailableActions.vue, components/bsx/Offer/OfferTable.vue, utils/format/time.ts, utils/gallery/abstractCalls.ts
=> feat: calculate 14days expiration for offer

components/spotlight/SpotlightTable.vue
=> fix: Spotlight doesnot work

components/rmrk/Gallery/CollectionItem.vue
=> fix: request error from sort by condition

components/rmrk/Collection/List/CollectionList.vue
https://user-images.githubusercontent.com/9987732/179990787-828f2cff-67c7-481a-ac2d-1b64e83db7ee.mov
=> 🔧 collections cards hover

components/base/CollectionSelect.vue, components/bsx/Create/CreateToken.vue, components/rmrk/Create/CreateToken.vue, components/unique/Create/CreateToken.vue, queries/collectionForMint.graphql, queries/subsquid/general/collectionForMint.graphql, queries/unique/collectionForMint.graphql
=> fix: incorrect number of NFTs in collection

components/shared/BalanceInput.vue
=> refactor: change `balance` to `amount`

components/bsx/Gallery/Item/GalleryItem.vue, queries/subsquid/bsx/itemEvents.graphql
=> feat: history component for item

langDir/en.json, utils/mixins/offerMixin.ts
=> fix: Wrong text after accepting incoming offer

.npmrc, package.json, pnpm-lock.yaml
=> Disable strict-peer-dependencies and pin Vue version

components/rmrk/Gallery/Gallery.vue
=> fix: search gallery on bsx

.npmrc
=> disable prefer-symlinked-executables

components/bsx/Create/CreateToken.vue
=> fix: cant mint if I dont want to put NFT on sale

components/bsx/Offer/MyOffer.vue
=> Add ability to sort by time in incoming offers

components/rmrk/Gallery/PaginatedCardList.vue
=> #3576 Fixed: Duplicate nfts in user profile created section

components/bsx/Gallery/Item/AvailableActions.vue
=> fix: balanceInputComponent.checkValidity is not a function

components/bsx/Offer/OfferList.vue
=> fix: offer withdrawal (3513) 

components/bsx/Offer/OfferTable.vue, utils/mixins/offerMixin.ts
=> bugfix: hide pagination when item amount is small

components/bsx/Offer/OfferTable.vue
=> fix: Can not see other columns at certain width

components/bsx/Gallery/Item/AvailableActions.vue, components/shared/BalanceInput.vue
=> fix: balanceInput is broken

utils/format/time.ts
=> fix: Optimize expiration time for shorter format

components/bsx/Offer/OfferTable.vue
=> fix: remove bar from empty table

components/bsx/Offer/OfferList.vue, queries/subsquid/bsx/offerListByNftId.graphql
[beta](https://beta.kodadot.xyz/bsx/gallery/3888932818-1)
local:
=> feat: Hide own offer afterwards I bought item

components/rmrk/Collection/List/CollectionList.vue, components/rmrk/Create/CreateToken.vue, components/rmrk/Create/SimpleMint.vue, components/rmrk/ExploreLayout/ExploreLayout.vue, components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/Gallery.vue, components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Profile/ProfileActivity.vue, components/rmrk/Profile/ProfileDetail.vue, components/rmrk/service/scheme.ts, queries/fragments/event.graphql, queries/rmrk/subsquid/nftByIdMinimal.graphql, queries/subsquid/general/eventListByNftId.graphql, queries/subsquid/rmrk/collectionForMint.graphql, queries/subsquid/rmrk/nftById.graphql, queries/subsquid/rmrk/usedCollectionSymbolsByAccount.graphql, utils/mixins/infiniteScrollMixin.ts
This PR replaces magick (SubQuery) with rubick (SubSquid).
It is a step towards more reusable / chain agnostic components.
Hope not that's why we have @kodadot/qa-guild
Yes I skipped some components. 
- :alien: collectionFor mint for RMRK
- :zap: CreateToken is using subquery
- :bug: :label: scroll mixin should return boolean | undefined
- :zap: using this.client instead of ternary op
- :coffin: removed dead getter
- :zap: Gallery is using :squid:
- :coffin: passion feed can come later again
- :bug: profile activity shows NaN if no NFT was sold
- :broom: optimize imports
- :alien: query to get only symbols for user
- :zap: simplemint is using :squid:
- :bug: WARNING: heuristic fragment matching going on!
- :alien: :squid: nftById for RMRK
- :alien: query all events by nftId
- :zap: …
=> Replace Magick with Rubick for RMRK

pages/transfer.vue
=> fix: set api connected on transfer page

components/bsx/Offer/OfferTable.vue, utils/datetime.ts, utils/format/time.ts, utils/mixins/offerMixin.ts
https://user-images.githubusercontent.com/11361147/182155614-6b082128-24ab-4dd3-b708-d66c4ce2eff1.mov
=> feat: add tooltip for expiration on offer table

components/rmrk/Gallery/CollectionItem.vue
=> :bug: collection detail was fetched from magick

components/base/BaseTokenForm.vue, components/base/CollectionSelect.vue, components/bsx/Create/CreateToken.vue, langDir/en.json, pages/bsx/create.vue
=> #3333 Add explainer text in create nft

components/bsx/Gallery/Item/ActionList.vue, components/bsx/Gallery/Item/AvailableActions.vue, components/bsx/Gallery/Item/GalleryItem.vue, components/rmrk/Gallery/AvailableActions.vue, components/rmrk/Gallery/GalleryItem.vue, langDir/en.json, utils/shoppingActions.ts
=> RELIST + UNLIST Action Button

components/bsx/Gallery/Item/GalleryItem.vue
=> Feat: Add arrows on image detail for Basilisk

components/shared/AddressInput.vue
- [ x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
=> fix_prefix_gift

components/base/CarouselCardList.vue
=> fixed carousel linking 

components/bsx/Create/CreateToken.vue
It prevents the app from crashing on prod :)))
=> fix(CreateToken): Unable to mint NFT on BSX

components/rmrk/Gallery/Search/SearchBar.vue
=> #3716 Focus on Search bar while pressing K

components/bsx/Gallery/Item/GalleryItem.vue, components/rmrk/Gallery/GalleryItem.vue, components/rmrk/Gallery/GalleryItemCarousel.vue, queries/rmrk/subsquid/collectionEntityById.graphql, utils/carousel.ts
=> feat: More from the same collection

components/base/CarouselCardList.vue, components/landing/Landing.vue, components/rmrk/Gallery/PriceChart.vue, styles/themes/light.scss
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> 🌞 identitypopover, footer, card, box, carousel, wallet btn, chart axis fix

components/landing/Landing.vue
=> #3737 landing css issue

nuxt.config.js
=> 🔧 remove unused materialDesignIcons imported from buefy

queries/rmrk/subsquid/lastNftListByEvent.graphql, utils/carousel.ts, utils/types/types.ts
=> fix: 3d objects are not showing on landing

components/Navbar.vue, components/rmrk/Gallery/Search/SearchBar.vue
https://user-images.githubusercontent.com/38389586/185686589-347678fd-64ba-40e0-8eb5-2d27b1645af9.mp4
=> bugfix: Weird border on burger menu on mobile in light mode

components/base/CarouselCardList.vue
=> 🔧 carousel large screen responsive

.github/renovate.json
=> renovate: check deps every monday

plugins/pwa.ts
=> fix: flush indexed db on service-worker

components/rmrk/utils.ts, utils/gallery/media.ts
https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download
Tested on https://deploy-preview-3833--koda-nuxt.netlify.app/bsx/gallery/3400610063-1
=> fix: unknown content type

tests/cypress/e2e/components/media.cy.ts
=> test: adjust media e2e timeout

components/identity/module/IdentityPopoverHeader.vue
=> fix: Identity popover - copy to clipboard broken

styles/themes/_dark.scss, styles/themes/_light.scss
=> fix: add hover color on navigation bar on light mode

components/identity/module/IdentityPopoverHeader.vue, components/identity/utils/useIdentityStats.ts, tests/cypress/e2e/components/identity.cy.ts
=> test: copy address in identity component

components/rmrk/Profile/utils.ts, components/shared/BlockExplorerLink.vue, pages/transfer.vue, utils/config/chain.config.ts
=> Add Rococo Basilisk & Basilisk explorer

components/landing/Landing.vue
=> feat: Migrating Latest Sales + Newest List to /snek

components/Navbar.vue, components/bsx/Asset/AssetList.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, locales/en.json
=> feat: add route to snek/assets

tests/cypress/e2e/components/identity.cy.ts, tests/cypress/e2e/components/media.cy.ts
=> test: increase requestTimeout and fix identity test

tests/prefix.spec.ts
=> fix: skip statemine test

components/common/WalletModal.vue
=> 🔧 hotfix wallet connect

utils/api/bsx/query.ts
=> 🔧 hotfix getAssetBalance

tests/cypress/e2e/components/media.cy.ts
=> skip-media-tests

components/common/WalletModal.vue, utils/config/wallets.ts
cc @roiLeo I just have seen your fix #3957 so please choose ;)
=> :bug: ability to correctly resolve mobile device

components/Navbar.vue, components/search/Search.vue
=> hotfix: broken on mobile

package.json, pnpm-lock.yaml
=> New URL for Snek

styles/components/_search.scss, styles/themes/_dark.scss
=> 🔧 fix global scss import

queries/rmrk/subsquid/hotNfts.graphql, queries/rmrk/subsquid/seriesInsightList.graphql, queries/rmrk/subsquid/spotlightList.graphql
=> fix: adjust query on series, spotlight, and hot nfts

tests/cypress/e2e/rmrk-simple-mint.cy.ts
removing fee check until #3966 gets fixed
=> [skip netlify] temporary disable fee check

components/search/SearchSuggestion.vue, styles/components/_search.scss
=> fix(search): price is missing on search suggestion

components/search/SearchBar.vue, components/search/SearchCollection.vue
=> fix: invalid component name

components/Navbar.vue, components/landing/SearchLanding.vue, styles/components/_search.scss, styles/global.scss, styles/layouts/_main-navigation.scss
=> feat: search bar with suggestion on mobile

components/bsx/Offer/OffersUserTable.vue, utils/mixins/offerMixin.ts
=> fix: loader

components/bsx/Create/RoyaltyForm.vue
original issue: https://github.com/kodadot/nft-gallery/pull/4008#issuecomment-1259520681
=> chore: enable royalty to be zero

components/rmrk/Profile/utils.ts, utils/config/chain.config.ts
bsx subscan link
https://basilisk.subscan.io/block/1879043
=> fix: Incorrect currency shown at /bsx

components/landing/LandingPage.vue
=> ✨ hotfix display top collection

components/rmrk/Collection/List/CollectionList.vue, queries/subsquid/general/collectionListWithSearch.graphql, utils/constants.ts, utils/prefix.ts
=> 🔧 denyList for bsx

utils/constants.ts
```json
{
"id": 2623,
"name": "002",
"squidName": "click",
"status": "SYNCING",
"syncStatus": {
"totalBlocks": 2716061,
"currentBlock": 683980
},
"api": {
"status": "AVAILABLE"
},
"deploy": {
"status": "DEPLOYED"
},
"processor": {
"status": "SYNCING",
"syncState": {
"totalBlocks": 2716061,
"currentBlock": 683980
}
},
"deploymentUrl": "https://squid.subsquid.io/click/v/002/graphql"
}
```
=> EVM on MoonBeam for one batch brew.

nuxt.config.js
- disable reporting to sentry.io on localhost/development
=> disable sentry on development

components/rmrk/Gallery/CollectionItem.vue
preview link: https://deploy-preview-4093--koda-nuxt.netlify.app/movr/collection/0xb6e9e605aa159017173caa6181c522db455f6661?page=23
=> fix: Remove infinity scroll on collection on the top

components/landing/SearchLanding.vue, components/shared/ChainSelect.vue, package.json, pnpm-lock.yaml, utils/constants.ts
=> fix: Hide testnet, movr & glmr on production

utils/config/wallets.ts
=> feat: show only installed wallets

components/landing/FeaturedArticles.vue, components/landing/LandingPage.vue, locales/en.json, styles/components/_article.scss, styles/index.scss
=> feat: add featured articles

components/rmrk/Gallery/CollectionItem.vue
https://user-images.githubusercontent.com/11361147/194735034-c978f3fa-9962-4711-b37b-b5937ffab36b.mov
=> fix: keep desc while loading

pages/transfer.vue
=> fix: Transfer copy link & view transaction

components/bsx/Asset/AssetList.vue
=> TNKR as an asset on KodaDot

styles/themes/_dark.scss, styles/themes/_light.scss
=> #4116 Search shadow fix

components/landing/SearchLanding.vue, styles/components/_search.scss
=> fix: Mobile landing on new neobrutalism design

components/TheFooter.vue
=> feat: replace substack input placeholder

components/carousel/module/CarouselInfo.vue, utils/carousel.ts
=> fix: More from this collection chain name

components/search/SearchSuggestion.vue
=> fix: load more

Dockerfile, docker-compose.yml
=> fix: run kodadot with docker-compose up --build

components/carousel/utils/useCarouselSpotlight.ts
=> ✨ Quakz Music Box in spotlight rmrk

styles/components/_search.scss
=> fix: Overlay of networks while searching on landing

components/search/SearchBar.vue
=> fix: Missing browser history on search

components/search/SearchSuggestion.vue, styles/components/_search.scss, styles/themes/_dark.scss
=> #4181 fix typo

components/rmrk/Gallery/History.vue
=> 🔧 History component Amount token

components/rmrk/Gallery/CollectionActivity.vue
=> 🔧 Collection Activity token

components/rmrk/Gallery/GalleryCard.vue
=> fix: wrong token money on collection details

styles/layouts/_footer.scss
=> #4219 footer overflow fix

styles/components/_carousel.scss
=> #4247 hidden search dropdown

components/landing/LandingPage.vue, components/landing/TopCollections.vue, components/landing/TopCollectionsItem.vue, styles/components/_top-collections.scss, styles/themes/_dark.scss, styles/themes/_light.scss
=> ✨ bsx landing top collection

components/search/SearchSuggestion.vue, styles/components/_search.scss
=> fix: Rankings & See All in search bar outside of landing page doesnot follow design

components/carousel/CarouselIndex.vue, components/carousel/CarouselTypeSpotlight.vue, components/carousel/module/CarouselAgnostic.vue, layouts/centered-half-layout.vue, layouts/default.vue, layouts/full-width-layout.vue
=> fix: layout shift on spotlight carousel

components/landing/TopCollections.vue
=> ✨ top collection skeleton

components/bsx/Gallery/Item/GalleryItem.vue, utils/config/permision.config.ts
- :ambulance: disable bsx minting
- :ambulance: disable bsx actions
=> :snake: Stuck Snek

components/bsx/Offer/OffersUserTable.vue, components/bsx/Offer/StatsOverview.vue, components/rmrk/Profile/ProfileActivity.vue
=> 🔧 profil wrong currency

styles/global.scss
=> #4314 Height issue in create, teleport, transform , transfer 

styles/themes/_light.scss
BEFORE : 
AFTER:
:camera_flash:  hover over tab link (NFT)
:camera_flash:  hover over navbar link
=> fix links hover color

components/bsx/Gallery/Item/GalleryItem.vue, utils/config/permision.config.ts
- once Basilisk will be unbricked
- check for status https://kusama.polkassembly.io/referendum/245
Reverts kodadot/nft-gallery#4298
- maybe we need rotate snek indexer 
Seems 7h if I read right?
=> Revert ":snake: Stuck Snek" 

styles/themes/_dark.scss
Didn't catch it on my screen
Should we remove focus background color too?
=> 🔧 navbar item dark mode hover state

components/shared/Loader.vue
=> #4334 loader overflow issue

components/search/SearchBar.vue
=> fix: remove placeholder text on focus

styles/themes/_light.scss
=> fix landing page broken colors

components/carousel/CarouselTypeSpotlight.vue, components/carousel/module/CarouselInfo.vue
=> 🔧 carousel spotlight revert

components/landing/TopCollectionsItem.vue, components/rmrk/Profile/NavbarProfileDropdown.vue, plugins/icons.ts, styles/themes/_dark.scss, styles/themes/_light.scss
Note:
- Wallet icon is not present in FontAwesome 5 pack
=> ✨ navbar icons

components/rmrk/Create/DropUpload.vue, locales/en.json, utils/constants.ts
=> ✨ dropUpload file size limit

styles/themes/_dark.scss
=> fix: Wallet selection darkmode

components/rmrk/Gallery/GalleryCard.vue
=> :fire: green glow begone!

styles/components/_price-chart.scss, styles/components/_search.scss, styles/layouts/_footer.scss, styles/layouts/_main-navigation.scss, styles/themes/_dark.scss, styles/themes/_light.scss
=> fix: Text link hover state

components/gallery/GalleryItem.vue, styles/components/_price-chart.scss, styles/layouts/_main-navigation.scss
>On cover screen (narrow one), would be nice to put creator and owner under each other
> On cover screen, can't log in because connect button/profile is below viewport and can't scroll there
As I could not reproduce this bug on my iphone device and also the devtool, I do some fix but have no idea if it work well. 
So, let me know if this fix could help or not.
> On chart time range select, dropdown appears at different location
Because every dropdown on mobile would place at the center position on the viewport, I fix the dropdown position as like this.
=> fix: New item redesign on foldable phone

components/rmrk/Profile/ProfileAssetsList.vue, locales/en.json
continue https://github.com/kodadot/nft-gallery/pull/4476#discussion_r1047279041
=> 🔧 en translation keyword

components/identity/module/IdentityPopoverFooter.vue
=> :bug: correct url for highest sales popover

components/search/Search.vue
https://user-images.githubusercontent.com/73316633/207708892-9cb7b394-e088-4fef-829f-a51789820ac5.mp4
=> :bug: repeated search works

components/teleport/Teleport.vue, package.json, pnpm-lock.yaml
- update syntax for ParaToRelay scenario
=> Bump ParaSpell version

components/carousel/module/CarouselInfo.vue
=> fix: Cut text at some length on landing page

utils/config/wallets.ts
=> ✨ Subwallet mobile app

components/chart/PriceChart.vue, libs/ui/src/components/NeoDropdown/NeoDropdown.scss, libs/ui/src/components/NeoDropdown/NeoDropdown.vue, libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue, styles/components/_price-chart.scss
no scroll bar when time frame dropdown is open:
=> fix : scroll bar when timeframe dropdown is open in price chart

components/landing/FeaturedArticles.vue
=> :broom: update landing articles

components/collection/CollectionList.vue
=> :construction: collection grid temp fix

styles/layouts/_main-navigation.scss
=> fix: SearchBar in Navbar vertical-align
