kodadot/nft-gallery

dashboard/src/components/rmrk/Create/CreateCollection.vue
dashboard/src/components/rmrk/Gallery/Gallery.vue
dashboard/src/components/rmrk/Gallery/GalleryRare.vue
dashboard/src/components/rmrk/Gallery/Search/query.ts
dashboard/src/main.ts

201 same images are grouped

---

dashboard/src/components/shared/format/Money.vue

Fixes #239
Looks like formatBalance doesn't work with bigger numbers
There is and error `Error in render: "Error: Assertion failed"` when the price in USD is >= 10 000
However it works well with string values so I've just added `.toString()` and it works

Pass string value to a formatBalance filter

---

dashboard/src/components/rmrk/Gallery/GalleryItem.vue

This P.R fixes #24 
Markdown rendering is done using the already imported `markdown-it-vue` dependency.

Markdown render description text

---

dashboard/package.json
dashboard/src/colors.scss
dashboard/src/components/rmrk/Gallery/Item/Sharing.vue
dashboard/src/icons.ts
dashboard/src/main.ts
dashboard/yarn.lock

Related to #161
My proposition is to add vue-social-sharing package. I've added `ShareNetwork` component which helps share link to a facebook.
Twitter, Telegram, Line can be added too. With this plugin you can share content without leaving kodadot page.
More details here: https://github.com/nicolasbeauvais/vue-social-sharing
You can see new facebook icon in the nft detail page

Add vue-social-sharing plugin

---

dashboard/src/components/rmrk/Gallery/Gallery.vue
dashboard/src/components/rmrk/Gallery/Search/query.ts

Hey, added requested styles (issue [#230](https://github.com/kodadot/nft-gallery/issues/230)).
This is currently mock Price and EMOTE. Is it possible to add from back-end next params: `hasPrice`, `price` and number for EMOTE (this is amount of likes or so?). Implemented without  https://vuesax.com/docs/components/Card.html#default. Check plz styles and let me know what do you think. I've added zoom animation for video previews as well to be consistent.

Gallery card update

---

dashboard/package.json
dashboard/src/views/Profile.vue

From issue #287. og:image was missing from link cards shown on social media platforms. Added og:image meta property in which displays the user's latest NFT that is an image.

Showing last NFT mint from user profile in OG:image

---

dashboard/src/components/rmrk/Gallery/GalleryItem.vue

Here image preview should already work. 
But to make it really nice, I will require some help, probably from @vikiival 
1. How can I get `nft.price` in the same view as <money> component returns but I need only value as string.
2. Is it possible to get `width` and `height` attributes for images? This will allow me to build previews based on image sizes and not with fixed dimensions.

Generate social cards on the fly with NFT name, price and KodaDot branding

---

dashboard/src/components/rmrk/Gallery/GalleryItem.vue

Added the ability to minimize a fullscreen NFT image by hitting ```esc``` as requested by @yangwao in #443.

Added return to original view-port after pressing esc

---

src/components/rmrk/Gallery/CollectionItem.vue

#486 related
Looks like it's working:
[preview](https://deploy-preview-500--nftkodadot.netlify.app/rmrk/collection/900D19DC7D3C444E4C-AIW)

fix(collection): metadata

---

src/components/Footer.vue
src/icons.ts

adding youtube and substack link to footer

---

src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/utils.ts

fix(media): image theatre preview

---

src/components/rmrk/Create/SimpleMint.vue
src/locales/en.json
src/locales/fr.json

closes #477 
Button "CLICK TO CREATE NFT(s)" is disabled when ToS is unchecked.
Maybe it need something to tell user which are required fields.

fix(mint): ToS switch

---

src/components/rmrk/Gallery/GalleryItem.vue

- [x ] Code builds clean without any erros or warnings
- [ x] Merged recent default branch -- **main** and I've no conflicts
- [ x] Didn't break any original functionality
- [x ] Bugfix
- closes #445  - Changed the width to 100% and set the height to auto to keep the aspect ratio of the original image.
Small window:
Medium window:
Large window (1920x1080):

set aspect ratio to be consistent when changing browser size

---

src/components/rmrk/Gallery/Pagination.vue

- closes #567  - Added scroll top on page change

Scroll to top on page change

---

src/components/landing/Spotlight.vue

OG for spotlight

---

package.json
src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/Gallery/History.vue
src/components/rmrk/Gallery/PriceChart.vue
src/icons.ts
src/views/OnChainProperty.vue

Price history chart

---

src/components/spotlight/SpotlightTable.vue

By default show all spotlight
#606 related
- closes #603 
- closes #610

feat(spotlight): show users with identity & skelton while loading

---

src/components/rmrk/Gallery/Gallery.vue

This small change align pagination in gallery to the right.

fix(gallery): align pagination right

---

src/styles/global.scss

- closes #619 
I added a color to the active class in the navbar, so that it gets applied when the route is active even when you reload and hence it persists. **router-link-active** and **navbar-start** are buefy class names and I am scoping it within the navbar with the navbar-start class, so that it doesn't affect the router link anywhere else.

#619 Tell user where is located in app in navbar

---

src/components/rmrk/Profile/NavbarProfileDropdown.vue

- closes #615 - <Added - check polkadot.js extension on the login page (if you've installed polkadot.js in your browser then when you click the 'Login' button, they should be showing a dropdown to login but if you didn't install polkadot.js then should be showing the dropdown to install polkadot.js )>
-

615 check extension

---

src/components/rmrk/Gallery/AvailableActions.vue
src/components/rmrk/Gallery/GalleryItem.vue
src/components/shared/Auth.vue

- closes #644 - 
I have focused on how the margins and padding was looking off and fixed that. Other than this, focusing on the UX, I have removed the collapsible dropdown and added the content directly under the actions heading, so in this way one step is reduced for the user. I have also changed the button design and effects have been added on hover.

Actions component redesigned

---

src/components/rmrk/Gallery/AvailableActions.vue
src/components/rmrk/Gallery/GalleryItem.vue

- closes #611 - I have added an Unlist button Alongside price. I have used refs, so that the common function from Actions component can be reused. 
- [x
]
Whenever your fix will change **something** on UI, a screenshot is more than welcome

#611 Unlist button in NFT

---

src/components/transfer/Transfer.vue
src/store.ts

- closes #675 -  For opening ksm transactions, I have added a button and have found the transaction id using `blockHash.toHex();`
For showing current price of KSM, have used state variable `fiatPrice`. 

#675 Open ksm transaction and view current price of KSM

---

src/components/rmrk/Gallery/CollectionActivity.vue
src/components/rmrk/Gallery/CollectionItem.vue
src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/service/Consolidator.ts
src/components/rmrk/service/NftUtils.ts
src/components/shared/format/Money.vue
src/queries/collectionById.graphql

Tested on:
- /rmrk/collection/800f8a914281765a7d-KITTY
- /rmrk/collection/466e8b6338599eaf1e-GAVS371
- /rmrk/collection/900D19DC7D3C444E4C-KSMG22
1. When collection doesn't have floor price
2. When there is multiple "BUY" events on one single NFT
- This PR closes #703 
In this PR i've edited some typescript file to fix building errors/warnings and I don't know if it break something.
24h volume traded feels weird :/

feat(collection): status signaling

---

src/components/rmrk/Gallery/CollectionActivity.vue
src/components/rmrk/Gallery/CollectionItem.vue

Small PR before diving back to /rankings
- This PR closes #738 
- changed "Owners" to "Owned" : 
> The numbers of owners isn't displaying properly. It displays total NFT in wallets that have been sold but doesn't register owners with multiple NFT's.

feature(collection): ui changes

---

src/components/rmrk/Gallery/CollectionItem.vue

I need to add skelton next when collection is loading.
- This PR closes #747 
t

fix(collection): collection avatar size

---

src/components/transfer/DonationButton.vue
src/components/transfer/Transfer.vue
src/icons.ts
src/views/Profile.vue

- This PR closes #457 
I have added a 'Gift 10$' button in artist's profile and on clicking that I take them to /transfer with values pre filled. I have also added profile information for artist so the user knows who he is paying.

#457 Adding tip in user profile

---

src/components/rmrk/Gallery/GalleryCard.vue

- proper link (replace ```<div>``` by ```<a>```) to NFT when on collection page

hotfix(card): change div to a link

---

src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/Gallery/Item/Sharing.vue
src/views/Profile.vue

#752 Unified button for sharing and linking

---

src/components/rmrk/Gallery/History.vue

Last point on Price Chart is hard coded to show today date and current nft value.
Remove it 😄 because it will be the same as the last nft interaction.
- This PR closes #780

fix(priceChart): remove last point on graph

---

src/components/rmrk/Gallery/EmotionList.vue
src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/Gallery/PriceChart.vue
src/components/rmrk/Media/ImageMedia.vue

App should correctly show fullscreen

---

src/components/rmrk/Gallery/PriceChart.vue

This quickfix will hide overlapping label on x axis in price chart
- This PR closes #811

fix(pricechart): hideoverlapping label on x axis

---

src/components/rmrk/Gallery/CollectionItem.vue
src/views/Profile.vue

- removed wide container size on Profile & Collection (is-fluid)
- add section class to keep gutter on mobile (responsive)
- This PR closes #969

fix(page): layout

---

src/components/rmrk/Gallery/Item/Sharing.vue

fix(sharing): active

---

src/components/rmrk/Gallery/GalleryItem.vue
src/components/rmrk/Gallery/History.vue
src/components/rmrk/Gallery/HistoryPriceChart.vue
src/components/rmrk/Gallery/PriceChart.vue
src/components/rmrk/utils.ts
src/components/transfer/Transfer.vue

- :bug: added types to the price chart component
- :bug: fixed price chart for gallery item
- :zap: HistoryPriceChart is now auto collapsible
- :bug: History table now shows the data
- :zap: Date in the History table links the block on subscan
- :zap: added return types to the Transfer
This PR closes #952

fix(GalleryItem): Fixing the data in the price table and history chart

---

store/index.ts

Fix collection detail layout

---

src/App.vue
src/coingecko.ts
src/components/transfer/Transfer.vue
src/store.ts

in the future we could move coingecko api calls to a new vuex module
- refactoring code

fix(coingecko): move api call to Transfer page

---

src/components/Navbar.vue
src/components/shared/DisabledInput.vue
src/locales/en.json
src/router/index.ts
src/utils/urlTransformer.ts
src/views/Transform.vue
tests/unit/urlTransform.spec.ts
yarn.lock

- :top: updated can-i-use
- :tada: url transformer is working correclty
- :white_check_mark: updated tests for url transformer
- :lipstick: Disabled input can accept readonly prop
- :rocket: added Tranform component
- :earth_americas: added translation for the transform
- :zap: added translations, added transform to navbar, added ?url param
- closes #966

966 Transform URL from other galleries into kodadot

---

components/rmrk/Create/ArweaveUploadSwitch.vue
components/rmrk/Create/CreateCollection.vue
components/rmrk/Create/CreateToken.vue
components/rmrk/Create/SimpleMint.vue
components/shared/Support.vue
components/shared/Tooltip.vue
langDir/en.json

https://user-images.githubusercontent.com/17470909/143064724-f146c99e-260f-4b2f-b82d-35b15335a94f.mp4
-------------
There's an edge case on the carbonless NFT tooltip wherein we have a hyperlink inside but currently we aren't able to click it since the tooltip closes immediately when hovering away from the button. Another solution for this is to make the tooltip trigger on click instead of hover and tracking the active state of the tooltip. What are your thoughts?

feat: add tooltip to explain switches during minting

---

src/components/rmrk/Gallery/Collections.vue
src/components/transfer/Transfer.vue
src/queries/collectionListWithSearch.graphql

I didn't find a way to remove empty collections from query yet

feat(collections): filters

---

pages/index.vue

- [ []](url) My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

added link to NFT wiki on home page

---

components/shared/format/Identity.vue

Fixed whitespace between twitter icon and name

---

components/shared/Avatar.vue

:construction: disabling Identicon because it is unstable on Nuxt

---

components/shared/format/Identity.vue
pages/transfer.vue

fix: add on-chain identity after destination address

---

langDir/all_lang.json
langDir/de.json
langDir/en.json
langDir/hi.json
langDir/ko.json
langDir/nl.json
langDir/ua.json
langDir/ur.json

https://kusama.subscan.io/extrinsic/0x5ed57a0226431c48c28904bfcd1e813a047d3e06755e5c5d14f332e9a3c1bf69
https://kusama.subscan.io/extrinsic/0xe1dd6a684f3c1a9e5f8238327efa30f45f6a886a1cd90b4a6effacd252acc807
https://kusama.subscan.io/extrinsic/0xd5b25af23ec4c0a219c62ea0dbe9900d56a1cf514b2e55f7a1432d062ce05c30

chore: add minimum minting fee to faq

---

components/rmrk/Create/CreateToken.vue
components/rmrk/Create/SimpleMint.vue
components/rmrk/Gallery/Gallery.vue
components/rmrk/Gallery/History.vue
components/rmrk/Gallery/Item/Detail.vue
components/spotlight/SpotlightTable.vue
nuxt.config.js
pages/index.vue
pages/permafrost/create.vue
pages/rmrk/detail/_id.vue

_Tous les chemins mènent à Rome_
Now I understand why @dezine2dev rewrote all the routes.
[Nuxt i18n](https://i18n.nuxtjs.org/strategies#configuration) had bad configuration. 
Should we keep _/gallery/{id}_ ?
no more missing path

⚒️ route & i18n compiled route

---

components/shared/IdentityPopover.vue
queries/nftStatsByIssuer.graphql

fix: reverse order to fetch first nft mint date

---

components/shared/Loader.vue

1460 fix: center preloader status text

---

components/rmrk/Gallery/CollectionItem.vue

**Browser's cache has been cleared**
https://user-images.githubusercontent.com/17470909/145608750-81f11029-8c0f-45f7-b72c-2564941285c7.mp4

#1486 fix: turn off skeleton while paginating on collection

---

pages/index.vue
pages/rmrk/collection/_id.vue
pages/rmrk/detail/_id.vue
pages/rmrk/gallery/_id.vue
pages/rmrk/gallery/index.vue
pages/rmrk/pack/_id.vue
pages/rmrk/u/_id.vue

Fix: Invalid component name

---

layouts/centered-half-layout.vue
layouts/default.vue
layouts/full-width-layout.vue
styles/global.scss

https://user-images.githubusercontent.com/17953978/147363395-9ca2e3ba-a442-4a33-99e9-90faed76b90f.mov

1442 add transition between pages

---

components/rmrk/Gallery/AvailableActions.vue
components/rmrk/Gallery/Search/SearchBar.vue
components/rmrk/Gallery/Search/SearchBarCollection.vue
components/settings/Interface.vue
store/preferences.ts

#1417 Add YOLO to user preference

---

components/rmrk/Gallery/Item/Sharing.vue
pages/rmrk/u/_id.vue

https://user-images.githubusercontent.com/17953978/147501757-7fb501b6-aa6b-49e5-907b-21bd7f8ec29d.mov

1618 galleryitem in collection tab should link to collection

---

store/preferences.ts

1628 set new default interface settings

---

components/Navbar.vue

⚒️ unused css & logo padding desktop

---

components/rmrk/Gallery/GalleryItem.vue
components/rmrk/Gallery/History.vue
components/rmrk/Gallery/PriceChart.vue
styles/global.scss

I'm the one to blame, continue #1100 & #1631
gallery-item page is supercharging some default css

⚒️  border on galleryItem

---

components/rmrk/Gallery/Gallery.vue

We don't need to link to `/collection` as we introduce in user preferences to show a certain amount of nfts in page.

⚒️ gallery link in card text

---

components/landing/Landing.vue

#1642 continue, side gutter were missing

⚒️ landing layout bis

---

components/rmrk/Gallery/Search/SearchBarCollection.vue
components/shared/form/BasicSwitch.vue

Close #1683
- :zap: BasicSwitch now takes tooltip as parameter
- :bug: Buy now is correctly centered in searchbar collection

1683 Centering Buy now button

---

components/rmrk/Gallery/Layout.vue
store/preferences.ts

Meh. 
UI is not rendering full cards, it feel too big on Macbook (14")

🔄 sync layout

---

nuxt.config.js

Fonts have never been loaded...
Instead of loading them from the google cdn we could includes fonts in `assets` directory.
For the moment we load the "bold" (600, 700 font weight) versions because the result is better, let me know if you want to test with ligth version.
(bold)
(medium)
(normal)

✨ fira-code font config

---

components/rmrk/Gallery/CollectionItem.vue
components/rmrk/Gallery/Collections.vue
components/rmrk/Gallery/Gallery.vue
pages/rmrk/collections.vue
pages/rmrk/u/_id.vue
styles/global.scss
styles/mixins.scss

#1652 Wider items in feeds

---

components/shared/IdentityPopover.vue

⚒️ typo identityPopover text

---

.dockerignore
Dockerfile
README.md
docker-compose.yml
nuxt.config.js

- Implemented an easy to use docker setup for KodaDot.
- Supports Hot Module Replacement.
- Updated docs.

#1635 FEAT: Set Docker image building process

---

pages/teleport.vue
pages/transfer.vue

#1749 Fixing transfer and teleport

---

components/rmrk/Gallery/CollectionItem.vue

Load collection detail chart data when activity tab is clicked

---

pages/carbonless.vue
pages/contact.vue
pages/partnership.vue
pages/permafrost/create.vue
pages/rmrk/admin.vue
pages/rmrk/collection/_id.vue
pages/rmrk/collections.vue
pages/rmrk/detail/_id.vue
pages/rmrk/gallery/_id.vue
pages/rmrk/gallery/index.vue
pages/rmrk/mint.vue
pages/rmrk/u/_id.vue
pages/series-insight.vue
pages/spotlight.vue
pages/statemine/collections.vue
pages/statemine/create.vue
pages/statemine/u/_id.vue
pages/sustainability.vue
pages/westmint/collections.vue
pages/westmint/create.vue
pages/westmint/u/_id.vue

fix: circumvent opengraph namespace caching

---

pages/rmrk/collection/_id.vue
utils/seoImageGenerator.ts

Refactoring of og:image. 
Added image sizes as recommended by FB.
Changed verbal generated image format to jpeg. (smaller file)
Related to issue #1766

Image preview size

---

components/shared/Loader.vue

#1902 fix preloader height issue

---

components/shared/history/HistoryBrowser.vue
components/shared/history/HistoryBrowserItem.vue

https://user-images.githubusercontent.com/39299315/149898691-afb5ad30-6e36-4ff7-88b8-00abad4a5d09.mp4

#1814 History component refactors

---

components/spotlight/SpotlightTable.vue

- `unique` => message: "syntax error at or near "ASC"" (reserved sql term)
- `uniqueCollectors` => message: "column \"uniquecollectors\" does not exist"
- `count` => message: "column "count" does not exist"

✨ spotlight unsortable column

---

.github/workflows/reviewdog.yml

Should we keep this dog? as we now have pre-commit hook with husky

🦮 reviewdog need some assist

---

components/spotlight/SpotlightTable.vue

We will still need to fix `unique` column sort

✨ spotlight backend sorting

---

components/rmrk/Gallery/Gallery.vue
nuxt.config.js
plugins/endpoint.ts
plugins/polkadot.ts
plugins/vuex-persist.ts
store/index.ts
utils/api/general.ts

We had vuexPersist in the old spa which was resolved incorrectly so it connected by default to Kusama but it showed that settings.apiUrl is statemine. [YOLO]
- Close #2058
- :zap: api will await for readyness
- :bug: forgot to remove vuex plugin from store
- :clown_face: Workaround for unique nfts without metadata

I spent whole day trying to find an issue

---

components/rmrk/Create/SimpleMint.vue
components/shared/BalanceInput.vue

Show transaction fees denomination in KSM and dollars without clicking

---

components/rmrk/Create/SimpleMint.vue

feat: use simple text instead of b-message warning

---

components/rmrk/Gallery/Search/SearchBarCollection.vue
components/rmrk/Gallery/Search/SearchSortDropdown.vue
styles/variables.scss

#2053 Unify collection detail and collections view with $primary

---

components/rmrk/Gallery/GalleryItem.vue

A) -> bought NFT view
B) -> listed NFT view
C -> unlisted NFT view

#2094-rework-actions-B

---

components/rmrk/Media/VideoMedia.vue

We'll need to verify how are audio and object displayed in `/galley`

⚒️  video gallery wrapper

---

components/rmrk/Gallery/Item/Navigation.vue

https://user-images.githubusercontent.com/17953978/152405384-f06ad148-8dcd-4b57-8684-1412d2a9ef99.mov

fix: block navigation if certain elements are being focused

---

components/rmrk/Profile/ProfileDetail.vue

fix: if user is only collector set tab to collected

---

jest.config.js

Fixed test workflow with `testPathIgnorePatterns` so Jest won't try and run the Cypress spec files.

🤖 remove cypress tests from test workflow

---

components/rmrk/Gallery/AvailableActions.vue
components/shared/AddressInput.vue
components/shared/BalanceInput.vue

https://user-images.githubusercontent.com/17953978/153437783-4f39198b-7d72-4f79-bca5-6ebe0ccbd4c7.mov
1.  use Refs to access child methods
2. Refs cant be used with dynamic components -> since its only 2 cases just write them plain in template -> **better readability and code comprehension anyways** (not the case if it would be 3+ components i think
3. Refs can't be used with v-if (DOM elements dont exist on component init) -> use v-show instead
4. also prevent second key from shortcut from being handled (as it would fill the focused element with 2nd key stroke from shortcut)

fix: focus input element after keyevent

---

components/series/SeriesTable.vue
components/spotlight/SpotlightTable.vue

https://user-images.githubusercontent.com/17953978/153388974-56932d2f-3c03-4f87-9a39-057f3743ac35.mov

fix: set sorting to desc by default on spotlight and series

---

utils/mixins/extrinsicsMixin.ts
utils/mixins/keyboardEventsMixin.ts

fix: call unbound methods with expected scope

---

components/Navbar.vue
components/rmrk/Gallery/Search/SearchBar.vue

#2344 Rework navbar

---

components/rmrk/Gallery/CollectionItem.vue

I find it annoying to have an empty box

⚒️ increase nfts displayed in collection

---

pages/teleport.vue
pages/transfer.vue
utils/api/Query.ts

It will now show avaibleBalance in Teleport/Transfer/CreateCollection

⚒️ account avaible balance 

---

package.json
utils/mixins/singleSubscribeMixin.ts

This feature is needed for #2292 
The base is that when you component need to flexibly subscribe to single subscription with the flexible arguments
- :zap: added singleSubscribe Mixin
- :bug: linter fails if you have newer node than 16.13.2

single subscribe

---

components/Navbar.vue

fix: remove scoped for now to restore old searchbar

---

components/shared/Loader.vue
components/shared/modals/ModalWrapper.vue
components/shared/modals/keyboardShortcutsModal.vue
langDir/en.json

feat: add hints on how to open shortcuts overview

---

components/rmrk/Gallery/AvailableActions.vue

⚒️ galleryItem isAvailableToBuy

---

components/shared/gallery/BaseGalleryItem.vue

App prevents user to do a right click on the image element in the gallery item.
This was raised as a security concern by a community

:zap: disable right click on the image in gallery item

---

components/Navbar.vue

https://user-images.githubusercontent.com/73316633/155882716-fdafa04d-1603-4e07-968d-b801a2fbe7c2.mp4

#2341 - Navbar transformation during scrolling

---

components/rmrk/Gallery/Search/SearchBar.vue

feat(SearchBar): add price show with hiden filter icon

---

components/settings/KeyboardShortcuts.vue
components/shared/modals/keyboardShortcutsModal.vue
styles/keyboard-shortcut.scss

change keyboard-shortcut to <kbd>

issue_2467：Use <kbd> tag in KeyboardShortcuts component

---

components/rmrk/Gallery/AvailableActions.vue

Disable button when address is invalid
https://user-images.githubusercontent.com/38389586/156304236-c2cd1e44-c0e4-4882-8e10-26565e4a4436.mp4

fix: KSM address prefix does not match but sent successfully

---

components/rmrk/Gallery/CollectionItem.vue

fix: use totalcount of nfts for vercel image rendering

---

components/rmrk/Gallery/History.vue
components/shared/format/Identity.vue

#2539 Post fixes in sales feed of collection

---

components/Navbar.vue
components/rmrk/Gallery/Item/Sharing.vue
components/rmrk/Gallery/Layout.vue
components/rmrk/Gallery/Pagination.vue
components/rmrk/Gallery/Search/SearchBar.vue
components/rmrk/Profile/NavbarProfileDropdown.vue
components/rmrk/Profile/ProfileDetail.vue
components/shared/ChainSelect.vue
components/shared/ConnectWalletButton.vue
components/shared/SwitchLocale.vue
components/shared/history/HistoryBrowser.vue
components/shared/modals/ShowQRModal.vue
components/transfer/DonationButton.vue
styles/global.scss

#2578 Keep only top-border on pagination and sharing buttons

---

components/shared/gallery/BaseGalleryItem.vue

It does not work when press tile view button after  entering the theatre view.
As in the video：
https://user-images.githubusercontent.com/31397967/159155276-791c119f-6e0f-43b1-9cd1-1bd14809e6c8.mp4
url: https://kodadot.xyz/rmrk/gallery/11864295-362f7ac490f5168342-VALENTINO_VIBES-RICH_VALENTINO_FELL_IN_LUV_SINGLE-0000000000000036
After fixing the bug:  
https://user-images.githubusercontent.com/31397967/159155620-09104abf-98be-469c-bc27-0ec71513c8de.mp4

🐛 fix: tile view does not work after entering theatre view

---

components/common/WalletModal.vue
utils/extension.ts

What: the previous implementation relies on the fact that we support only one extension.
Since our wallet model changed: App checked if the address is in the polkadot-js (false) fallback was keypair (false) so it threw error.
ht/ @roiLeo for the nice wallet impl :)

:bug: ability to sign transactions with any extension

---

components/rmrk/Profile/ProfileDetail.vue

fix: profile tabs not working properly sometimes

---

components/unique/Gallery/Item/Detail.vue

https://kodadot.xyz/rmrk/detail/11904483-800f8a914281765a7d-DREAMS-DREAM_6_OR_UNITY-0000000000000006

display collection name in detail page

---

components/rmrk/Gallery/Item/Navigation.vue
components/unique/Gallery/Item/Detail.vue

button isn't clickable on nft of vedio
what's more, switch button is hidden when a video is playing.
https://user-images.githubusercontent.com/31397967/161480622-581ccdd6-7968-4db5-8486-554daea70b4a.mp4

fix: switch button broken at some video nft on mobile

---

CONTRIBUTING.md
STYLE_GUIDE.md

- covers Vuex, SFCs, Naming Conventions, nuxt property decorators, how to create and use custom components

feat: add first version of kodadot style guide 💅 

---

components/Navbar.vue

Navbar breakpoints to hide tab

---

components/Navbar.vue

Keep the width of the search bar at release 350px.

nav bar display on different width

---

components/rmrk/Gallery/Flipper.vue
components/rmrk/Gallery/Holder/Holder.vue

sorted by highest percentage in flippers

---

components/rmrk/Gallery/GalleryCard.vue
components/rmrk/Gallery/GalleryItem.vue
components/rmrk/service/scheme.ts

⚠️ need to be tested, page with multiple media video is slow

⚒️ missing mediaUri meta

---

components/rmrk/Gallery/Search/SearchSortDropdown.vue
langDir/en.json
utils/constants.ts

✨ gallery order by Most emoted

---

components/shared/gallery/BaseGalleryItem.vue

display long size image/nft

---

components/rmrk/Gallery/EmotionList.vue
styles/global.scss

before:  
ui problems:  
1. Arrows in gallery are overlapping
2. emotion modal is not align center. 
3. extral close button at the top right corner.
after:

fix: modal ui justify on mobile

---

components/rmrk/Gallery/GalleryItemCarousel.vue
queries/rmrk/subsquid/nftEntitiesByIDs.graphql
tests/sorting.spec.ts
utils/sorting.ts

fix: Sort visited NFTs by time user has visited them

---

components/rmrk/Gallery/History.vue

https://www.nhc.noaa.gov/aboututc.shtml#:~:text=Prior%20to%201972%2C%20this%20time,%22%20or%20%22Zulu%20Time%22.

fix: replace gmt with umt in history date column

---

components/Navbar.vue
components/sales/SalesTable.vue
components/sales/types.ts
components/shared/view/BasicPopup.vue
langDir/en.json
pages/sales.vue
queries/rmrk/subsquid/salesFeed.graphql

- feat: page for sale engagement
- feat: saels feed query
- feat: init page for sales
- refactor: update time format
- refactor: using basic image
- feat: popup for larger nft image
https://user-images.githubusercontent.com/11361147/168977069-7b0001b9-cfca-4a2f-97fc-84d920dbfd29.mov

feat(1818): sales table for better engagement

---

.github/PULL_REQUEST_TEMPLATE.md
components/rmrk/Gallery/Search/SearchBar.vue
components/rmrk/Gallery/Search/SearchBarCollection.vue

fix: remove search query from url when empty

---

components/rmrk/Gallery/Gallery.vue
queries/subsquid/general/nftListWithSearch.graphql
utils/formatBalance.ts

- :bug: multiple sort options were killing the app
- :mute: warnings in format balance

3116 fast serpent

---

components/shared/Loader.vue
langDir/en.json

#3124 Add nudge on preloader to sign the transaction

---

nuxt.config.js

Fix: falls back to english on navigate #3131

---

pnpm-lock.yaml
store/index.ts

https://github.com/kodadot/nft-gallery/issues/3169

fix(3197, 3220) - stuck chains

---

queries/subsquid/general/userStatsByAccount.graphql
queries/userStatsByAccount.graphql

#3225 Fixing wrong numbers

---

components/rmrk/Profile/ProfileActivity.vue
queries/profileStatsById.graphql
queries/subsquid/general/profileStatsById.graphql
utils/math.ts

test on `/bsx/u/bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW`
**before**
**after**

🔧 stats by profile Id (bsx)

---

components/rmrk/Gallery/History.vue
components/rmrk/Gallery/Holder/Holder.vue
components/rmrk/Profile/Sales.vue
components/sales/SalesTable.vue
components/shared/BlockExplorerLink.vue
tsconfig.json

RMRK:
history\holder\filppers...
BSX:
history\holder\filppers...

refactor: BlockExplorerLink component

---

components/bsx/Offer/OfferTable.vue

fix: missing token symbol in offers table

---

components/shared/format/Identity.vue

related to https://github.com/kodadot/nft-gallery/pull/3357

fix: Identity at item is shown twice

---

components/bsx/Create/CreateCollection.vue
components/unique/Create/CreateCollection.vue

chore: hide attributeinput on collection creation for now

---

components/bsx/Create/CreateToken.vue
components/unique/Create/CreateToken.vue

- [y] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

fix: wrap transition-group element to prevent race condition

---

components/rmrk/Gallery/Search/SearchBar.vue

#3433 Search bar suggestions changes

---

components/bsx/Create/CreateCollection.vue
components/bsx/Create/CreateToken.vue
components/bsx/Gallery/Item/GalleryItem.vue
components/rmrk/Gallery/GalleryItem.vue
components/shared/AccountBalance.vue
components/shared/MyBalance.vue
pages/teleport.vue

Show user balance at minting screen

---

components/shared/ChainSelect.vue
nuxt.config.js
utils/constants.ts

according to env variables, to determine whether show these two test chains.
- development env
- production env

feat: hidden `westend` `westmint` in production env

---

components/bsx/Create/CreateToken.vue

fix: The asset instance ID has already been used for an asset

---

components/bsx/Create/CreateToken.vue

I emit a mock error while minting, and it could retry to mint again successfully.

Retry on the minting in case of errors

---

langDir/en.json
utils/mixins/metaMixin.ts

Change the appearance when cancelling a transaction

---

components/bsx/Offer/StatsOverview.vue
langDir/en.json

fix: misleading number on stats page

---

package.json
patches/vuex@3.6.2.patch
pnpm-lock.yaml

fix: patch vuex deprecation warning

---

pages/e2e-login.vue

E2E login was returning address in 42 prefix

fix: correct prefix for E2E tests

---

components/rmrk/Profile/NavbarProfileDropdown.vue
package.json
pnpm-lock.yaml

- :snake: snek is a default prefix
- :bug: unable to fetch balance for tokens
The issue was caused by me :) i changed the const to getter and forgot to check the implementation 😢 

fix(#4043): Ability show balance in navbar dropdown

---

components/rmrk/Gallery/Item/Navigation.vue
components/shared/ScrollTopButton.vue
components/shared/gallery/BaseGalleryItem.vue
styles/components/_modal.scss
styles/layouts/_main-navigation.scss

https://user-images.githubusercontent.com/17953978/192858453-9583686c-66fe-4140-b188-85c81ddbf8ca.mov

fix: snackbar index order 🔢 

---

nuxt.config.js
pages/glmr/create.vue
pages/glmr/explore.vue
utils/constants.ts

- :bug: correct path for seo
- :wrench: added antick as indexer for glmr

where is my glmr

---

utils/carousel.ts

fix: Incorrect url of nft on More From This Collection

---

components/carousel/utils/useCarousel.ts

fix: make event passive to fix sluggish vertical scroll

---

components/Navbar.vue
components/rmrk/Profile/NavbarProfileDropdown.vue
components/shared/ConnectWalletButton.vue
styles/abstracts/_variables.scss
styles/themes/_dark.scss

#4161 fixes with drawer, colors // connect wallet on mobile

---

components/rmrk/ExploreLayout/ExploreLayout.vue
components/rmrk/Gallery/History.vue
components/rmrk/Gallery/Holder/Holder.vue
components/rmrk/Gallery/Layout.vue
components/rmrk/Gallery/PriceChart.vue
components/search/SearchSortDropdown.vue
components/series/SeriesTable.vue
locales/en.json

#4004 covering missing strings

---

components/Navbar.vue
components/TheFooter.vue
components/landing/SearchLanding.vue
components/landing/TopCollectionsItem.vue
styles/components/_search.scss
styles/global.scss
styles/layouts/_footer.scss
styles/themes/_dark.scss

fix: Neobrutalism landing page release UI

---

queries/subsquid/general/collectionCuratedList.graphql

fix: make sure spotlight name not null

---

queries/subsquid/general/collectionCuratedList.graphql

fix: dont show empty string on spotlight

---

components/shared/ScrollTopButton.vue
styles/components/_scroll-to-top-button.scss
styles/index.scss
styles/themes/_dark.scss

feat: Redesign scroll up button

---

components/carousel/CarouselIndex.vue
components/carousel/CarouselTypeSpotlight.vue
components/carousel/module/CarouselAgnostic.vue
styles/components/_carousel.scss

Changes:
1. "Spotlight" title now is white
2. All cards are visible on all sliders. Off main screen cards are faded
3. Arrows are hidden if there is no more cards that way

#4153 redesign spotlight leftovers

---

components/rmrk/Gallery/History.vue
utils/historyEvent.ts

/rmrk/gallery/9691296-b2ed7a9394517e712d-EBY6M-YG-0000000000000040

fix: GalleryItem Chart wrong y axis label scale and number

---

components/bsx/Gallery/Item/GalleryItem.vue
components/shared/Sharing.vue

might need to rework this message design 
ping 🖼️ @exezbcz

🔧 display congrats on bsx after create

---

components/Navbar.vue
components/landing/SearchLanding.vue

fix: Dark mode explore leftover occasionally

---

components/search/SearchBar.vue

#4284 Show trending collection in SearchSuggestions if *urlPrefix* either *rmrk* or *bsx*

---

libs/ui/package.json
package.json
pnpm-lock.yaml

fix: bump vue@2 and pin vue-audio-visual version

---

styles/components/_top-collections.scss

- [ x I've tested it at </bsx/collection>

fix: remove black drop shadow on default state (dark mode)

---

styles/components/_search.scss

fix: remove transparent color from focused placeholder on darkmode 

---

components/search/Search.vue

The validation on the `updateSearch` function also fixes the duplicated navigation console error, so i went ahead and removed it (Hope its ok)
In addition to the fixed bug, i added the search string after a reload (on the explore route) to the searchBar, like this:
Let me know if you want this reverted as it was my intuition that made me change it and didnt want to open a new fresh bug just for it.

Fix: Search reload explore

---

components/bsx/Create/CreateCollection.vue
components/unique/apiConstants.ts

When Basilisk got stuck, they upgraded the code with new version that renamed call from `createClass` to `createCollection`. So than app was unable to find that call

:bug: unable to create collection in Basilisk

---

components/Navbar.vue
components/landing/SearchLanding.vue

update search bar visibility and disable scroll on burger menu

---

components/identity/IdentityIndex.vue
components/identity/utils/useIdentity.ts

fix the issue where IdentityIndex did not show latest address when changing wallets
reported in #4449 
affecting wallet dropdown and tansfer page 
https://user-images.githubusercontent.com/22791238/206836186-fd8693c7-c17a-4c74-992b-67feb00cb53d.mp4

:bug: :wrench: make identityIndex respond to address change

---

components/TheFooter.vue
styles/global.scss
styles/layouts/_footer.scss
styles/themes/_dark.scss
styles/themes/_light.scss

fix: Landing page visual change footer part

---

package.json
pnpm-lock.yaml
store/identity.ts

Next step could refactor fetchBalance:
```ts
const api = await ApiFactory.useApiInstance(endpoint)
const identityBalance = await balanceOf(api, address)
```
- new issue on wallet Identity Name maybe related with #4476

⬆️ upgrade sub-api dependencies

---

components/gallery/GalleryItemTabsPanel/GalleryItemChart.vue
components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue

fix: bring back galleryItem price chart data

---

components/generative/promptBuilder.ts
components/identity/IdentityIndex.vue
components/identity/utils/useIdentity.ts

make identity reactive
address and on-chain identity updates without needing to refresh page

:zap: fix identity reactivity

---

styles/components/_o-tabs.scss

fix: Gallery item tab typeface

---

components/common/WalletModal.vue

I've deleted few lines that were marked for deletion by a comment
I'm not sure what's the purpose of these lines
but deleting them fixed the bug and everything seems working fine
both for nova and math wallets
before:
https://user-images.githubusercontent.com/22791238/208300749-a7dd4c81-43de-496d-8175-60bb99c27b27.mp4
https://user-images.githubusercontent.com/22791238/208301043-f28f70ec-4d9b-4324-9ea9-f4aaa7969f3c.mp4
after:

fix: content dissapears after few seconds in walletModal in mobile devices

---

components/identity/IdentityIndex.vue

fix: missing user address in profile hover card

---

libs/ui/src/components/NeoTooltip/NeoTooltip.scss
libs/ui/src/scss/variable.scss

:bug: increase tooltip trigger area

---

components/Navbar.vue

Fix disabled scrolling on mobile

---

components/bsx/Offer/MyOffer.vue
components/bsx/Offer/OfferList.vue
components/bsx/Offer/OfferTable.vue
utils/mixins/offerMixin.ts

I had difficulty testing it on Rococo.
IMO, Offer features need a slight rework.

:wrench: bsx withdraw offer as owner

---

components/shared/MessageNotify.vue
components/shared/Sharing.vue
components/shared/modals/ModalWrapper.vue
components/shared/modals/ShowQRModal.vue

:bug: sharing buttons touchup + reusability

---

nuxt.config.js

previously https://github.com/kodadot/nft-gallery/pull/4671/files#diff-65d5d69bb59dcc81ad971719549cdee5018f0a240add8b7ef5c65bee3e73dae0R323-R324 I put the wrong logic. with this, forked repository doesn't need to add additional env in their github

fix: enable sourcemap if token exists

---

components/gallery/GalleryItem.vue
libs/ui/src/components/IdentityItem/IdentityItem.vue

🔧 IdentityItem spacing issue

---

components/navbar/MobileLanguageOption.vue
components/navbar/ProfileDropdown.vue
components/shared/SwitchLocale.vue
store/lang.ts
utils/config/i18n.ts

fix: i18n config cache on vuex

---

components/gallery/GalleryItemDescription.vue

fix: Description more important than Properties

---

components/gallery/GalleryItemAction/GalleryItemActionSlides.vue

There was a case that wasn't solved in the original pr #4758. Now fixed. 
Disabled buy button:

fix: disable buy button

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
locales/en.json

fix: missing BURN event in GalleryItem Activity tab

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
styles/themes/_dark.scss

🐛 list button for unlisted owned items

---

styles/abstracts/_theme.scss
styles/components/_o-tabs.scss

tested at /rmrk/gallery/16113219-DE15C1BA39DDD3C94B-FLW-LILIES-0000000000000001

fix: tabs covered background

---

components/collection/CollectionList.vue
components/rmrk/Gallery/CollectionItem.vue
components/rmrk/Gallery/PaginatedCardList.vue
components/rmrk/Profile/ProfileDetail.vue
components/shared/gallery/Gallery.vue
utils/mixins/infiniteScrollMixin.ts

feat: add prefetch to all pages using infinite scroll

---

services/replicate.ts

I just realized that I can fine tune waifu images by putting negative prompt there

:zap: add negative_prompt to the replicate model

---

components/shared/form/BasicInput.vue

upper input: space
lower input: empty

fix: 5014 Disable Mint for {{space}} only input

---

components/rmrk/Create/CreateCollection.vue
components/shared/form/BasicInput.vue

- :ambulance: BasicInput does not emit any function
- :bug: disable collection mint if name, symbol or image is not provided
- :bug: Spaces are illegal in names
Before 
After 
My bet is that it was broken by 3b018a32c51b40c4c151e8c6d862d71f32684943

:ambulance: MINT Does not work correctly

---

components/rmrk/Create/CreateCollection.vue

🔧 disabled submit button

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue

fix: 5103 add back mintnft activity

---

components/explore/MobileFilter.vue
components/explore/SidebarFilter.vue
components/search/Search.vue
components/shared/gallery/BreadcrumbsFilter.vue
components/shared/gallery/NeoTag.vue
layouts/explore-layout.vue
locales/en.json

Redesign breadcrumbs

---

libs/ui/src/components/NeoNftCard/NeoNftCard.scss
libs/ui/src/components/NeoNftCard/NeoNftCard.vue

fix: Explore gallery cards have unequeal height

---

components/collection/CollectionList.vue
components/shared/DynamicGrid.vue
components/shared/gallery/Gallery.vue

feat: use dynamic grid on existing explorer

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
composables/transaction/transactionBuy.ts
composables/transaction/types.ts
composables/useTransaction.ts
locales/en.json
vue-shim.d.ts

This feature will handle `BUY` tx from one single point
- `LIST` 0.0010
- `BUY` 0.0009
- ???

✨ transaction execBuy

---

components/rmrk/Gallery/PaginatedCardList.vue

Sorting in my profile not working properly

fix: Sorting in my profile not working properly

---

libs/ui/src/components/NeoSidebar/NeoSidebar.scss

seems it's a Apple's Safari related render issue, I didn't find another good way to fix it. It's just a hack and if anyone find better solution please remove my code here, also test on Chrome and Firefox and works well

fix(ui): fix sidebar issue in safari

---

components/explore/tab/TabOnExplore.vue

> when you click item again when you are on the items already, the buy now filter disappear

fix: filter disappear when click the same tab

---

components/gallery/GalleryItem.vue

change the breakpoint for mobile up to 930px

fix: gallery item break point set to 930px

---

components/bsx/Create/CreateToken.vue
components/rmrk/Create/SimpleMint.vue
components/settings/Minting.vue

tested on /bsx/gallery/290618266-2

fix: My non-carbonless NFT is carbonless

---

components/shared/DisabledInput.vue
pages/transfer.vue

**From url we checked usd amount, multiplied with ksm value (which is 0 when component is created)
the result of multiply was `Infinity` and that failed to sign the transaction.**
- :bug: making props in disabled input optional
- :label: properly typed
- :poop: resolve usd value to KSM
**BETA:**
**PR:**

5316 payments

---

.gitignore
locales/sk.json
package.json
script/checkLocale.mjs

anyone has idea on how to integrate to CI? 🤔️
what this script do:
- sort the locale json keys by alphabet
- check other locales missing keys compared with base locale (I set `en` as default)

chore: add locale sort/check script

---

components/landing/SearchLanding.vue
components/navbar/ChainSelectDropdown.vue
components/navbar/CreateDropdown.vue
components/navbar/NavbarExploreOptions.vue
composables/useChain.ts
middleware/prefix.ts
package.json
plugins/vuex-persist.ts
pnpm-lock.yaml
utils/chain.ts

fix: remove cache for chain list

---

components/collection/CollectionInfo.vue
libs/ui/src/components/NeoButton/NeoButton.scss
libs/ui/src/types.ts
locales/en.json

As we also have a markdown format of the description, I have to put the see more button under the description section.

feat: Collection description long text wrap

---

libs/static/README.md
libs/static/package.json
libs/static/src/indexers.ts
libs/static/src/types.ts

Seems like rubick@009-rc.0 can't recover from the issues, it is going super slow
Here I propose new indexer for rmrk2 called `marck` (Mark from Remark)
It's running on [new dedicated infra by subsquid](https://docs.subsquid.io/deploy-squid/deploy-manifest/) so should be insanely fast, will see

New endpoint for RMRK2

---

libs/static/package.json
libs/static/src/indexers.ts
libs/static/src/types.ts
utils/constants.ts

Since Hyper-jpeg does not have @kodadot1/static I need to manually add enpoint
Ref:
- #5425

:wrench: new apollo endpoint to rmrk2

---

app/router.scrollBehavior.js

fix: Scrolling in profile always kicks me back to top when loading

---

components/collection/CollectionInfo.vue

fix: collection on mobile is broken

---

components/collection/activity/events/eventRow/EventRowTablet.vue

Regarding the feature of displaying "--" when the amount is empty: I only removed it in tablet mode. Because in desktop mode, activity events are presented in table form, and it seems reasonable to display "--" in the table cell when the amount is empty.

fix: collection activity event row

---

libs/static/src/names.ts
libs/static/src/types.ts

#5435 rmrk label

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue

https://user-images.githubusercontent.com/128157824/230698150-ec93b8a1-6d40-43d1-b28b-3576573e9628.mp4

feat: make only 2 filters active by default

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue

In the SEND event, the meta represents the person receiving the nft.
After fix:

fix: empty `to` in SEND event

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue

> @leo-anderson-x I would lower the padding a bit - mby something like 16, just on top, keep the padding between the elements.
> _Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/5612#issuecomment-1505260335_
Removing the extra padding above makes this place look a little more compact.

feat: removing the extra padding above the first event on mobile

---

queries/subsquid/ksm/nftById.graphql
queries/subsquid/rmrk/nftById.graphql

- before: [canary.kodadot.xyz](https://canary.kodadot.xyz/ksm/gallery/16859826-4036da32f78754d408-J66M9-MANTA_SEA_RED_DEVIL-00000017)
- after: [deploy-preview-5674--koda-canary.netlify.app](https://deploy-preview-5674--koda-canary.netlify.app/ksm/gallery/16859826-4036da32f78754d408-J66M9-MANTA_SEA_RED_DEVIL-00000017)

fix: not showing royalties in gallery detail

---

components/common/ConnectWallet/useConnectWallet.ts
components/common/NotificationBox/useNotificationBox.ts
styles/components/_modal.scss

Changes
1. `autoFocus` causes `document.documentElement.scrollTop` to always be reset to 0, so I disabled it first.
2. The changes above may cause the modal-background to go out of view, because the default position of modal-background was previously based on document.body instead of window. Therefore, I changed it to fixed so that no matter where the scrollbar is, it can ensure that the modal-background covers the entire screen.
https://user-images.githubusercontent.com/128157824/232310538-8fadad96-742b-437a-9412-bbbb8f33511b.mp4

fix: opening sidebar resets scroll position

---

components/items/ItemsGrid/ItemsGridImage.vue
components/shared/gallery/NftCard.vue
libs/ui/src/components/NeoNftCard/NeoNftCard.vue

- :technologist: neo-nft-card takes custom link component
- :zap: use nuxt-link for neo-nft-card
I've seen in the PR that @roiLeo asked @praachi00 to replace nuxt-link with a in NeoNftCard
The problem is that it was doing ugly reloads.
The fix is really hacky but serves the purpose 
Commit: 6c05aecc81a14442d9dfe72074afd8fe3f67dd2f

Custom Link component for NeoNftCard

---

components/shared/filters/modules/constants.ts

fix: Add Mushroom Topia to sidebar in explorer

---

utils/api/bsx/query.ts

👇 \_\_ Let's make a quick check before the contribution.
- If new chain is added we should expect that default payment method is system token 
- Fix bugs with 'Unit' text

:wrench: for any chain use system token if not specified

---

components/collection/unlockable/UnlockableContainer.vue

fix: Unlockable change text in How unlockable item works

---

components/navbar/NotificationBoxButton.vue

hotfix https://github.com/kodadot/nft-gallery/pull/6170#issuecomment-1589443325

🔧 notification icon regular

---

components/explore/FilterMenuButton.vue
libs/ui/src/components/NeoIcon/NeoIcon.scss

closes #6216 
- remove NeoIcon forced size px... (please use `customSize` if you want to set custom size)
- small refactor component
- fix icon alignment
- fix icon pack

🔧 explore filterMenuButton size and pack

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue

Something that has been bothering me for some time
I've increase padding in action slide buttons
**beta**
**preview**

🔧 slider input number padding

---

components/base/SubmitButton.vue
libs/ui/src/components/NeoButton/NeoButton.vue

Same as #6170 but for `NeoButton` component
⚠️ some buttons might have icon changed, ping me if you see something strange

🔧 NeoButton icon pack

---

nuxt.config.js

- fix error in console `Uncaught ReferenceError: G is not defined`

🔧 Uncaught ReferenceError: G is not defined

---

composables/useNft.ts

🔧 getProcessMetadata (useNft)

---

middleware/redirects.ts

fix: make kodadot.xyz/drops working again

---

components/Navbar.vue
components/navbar/NotificationBoxButton.vue
components/navbar/ProfileDropdown.vue

- goes after #6382 
- close #5672 
- close #6413

🔧 overlapping modal

---

components/Navbar.vue
components/navbar/ExploreDropdown.vue
components/navbar/NavbarExploreOptions.vue
libs/ui/src/components/NeoDropdown/NeoDropdown.scss

fix: Explore hover dropdown doing weird things

---

components/gallery/useGalleryItem.ts

encountered this bug while working on shopping cart

resource.meta null check

---

pages/blog/index.vue

could be related with #6474
- fix main title
- fix hero-card tag color
- fix hero-card title line-height
- truncate card text
- fix some sizes

🔧 blog page refacto

---

nuxt.config.js

<details><summary>screenshot</summary>
<p>
</p>
</details>

build: temporary disable source-map

---

CONTRIBUTING.md
REWARDS.md

This PR should provide a fix for #6567

fix: typo, grammar issues in documentation

---

components/common/ConnectWallet/WalletAssetPortfolio.vue
components/common/NotificationBox/NotificationBoxModal.vue
components/massmint/ChooseCollectionDropdown.vue
components/massmint/Massmint.vue
components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
components/massmint/uploadDescription/UploadDescription.vue
libs/ui/package.json
libs/ui/src/components/NeoIcon/NeoIcon.scss
libs/ui/src/components/NeoIcon/NeoIcon.vue
libs/ui/src/histoire.scss
package.json
pnpm-lock.yaml
styles/index.scss

- In preparation of #5611 
- `@oruga/oruga-ui` is now under `libs/ui` workspace
- fix `NeoIcon` size prop/class

🔧 migrate oruga package to lib/ui

---

components/base/BaseTokenForm.vue
components/base/CollectionSelect.vue

- rewritte `CollectionSelect` vue3 composition api
- fix message label on select
- fix emit event
**before**
**after**

🔧 select collection on create nft page

---

components/shared/PulseChart.vue

🔧 PulseChart vue3

---

components/shared/collection/PriceChart.vue

🔧 PriceChart vue3

---

components/rmrk/Gallery/GalleryCard.vue

🔧 GalleryCard vue3

---

components/shared/Loader.vue

🔧 Loader vue3

---

components/shared/ReadOnlyBalanceInput.vue

🔧 ReadOnlyBalance vue3

---

components/shared/DropUpload.vue

- ref #4750 
<s>⚠️ didn't test</s>
🧪 on `/snek/gallery/3124270296-9`

🔧 DropUpload vue3

---

components/carousel/utils/useCarousel.ts
composables/useSearchNfts.ts

fix: adjust query in landing page

---

composables/transaction/mintToken/transactionMintBasilisk.ts

sry my bad error in export constant naming. just a quick small pr to fix this one so i do not use the common pr template.
@yangwao @vikiival  @Jarsen136 
> <img width="456" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/c10b8a2d-a754-4f03-8cc6-d8a42e971983">
> 
> @floyd-li Hey, there is something broken here.
_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/6928#issuecomment-1694393635_

fix: export const name issue

---

components/Navbar.vue
components/TheFooter.vue
components/blog/BlogPost.vue
components/buy/Buy.vue
components/carousel/module/CarouselAgnostic.vue
components/collection/CollectionGridWithBreadcrumbs.vue
components/common/IdentityForm.vue
components/drops/Drops.vue
components/items/Items.vue
components/massmint/Massmint.vue
components/poap/claim/ClaimForm.vue
components/shared/AddressInput.vue
components/shared/Error.vue
components/shared/TransactionLoader.vue
components/teleport/Teleport.vue
components/transfer/Transfer.vue
composables/useBlockTime.ts
composables/useTransactionStatus.ts
content/blog/first-time.md
libs/ui/src/components/NeoModal/NeoModal.vue
libs/ui/src/components/NeoSteps/NeoSteps.scss
libs/ui/src/components/NeoSteps/NeoSteps.vue
locales/en.json
nuxt.config.js
pages/cookie-notice.vue
stores/assets.ts
utils/config/types.ts

🔧 nuxt.config & assets store

---

components/common/listingCart/ListingCartMini.vue
styles/global.scss

🔧 k-grey background

---

components/collection/CollectionGrid.vue
components/search/types.ts

- ref #7375 
> Sort by on Profile collections tab does nothing ([How to reproduce](https://github.com/kodadot/nft-gallery/assets/36627808/9c116fd8-7bcb-4862-9e2e-668022535933))

🔧 collections sort by reactive

---

utils/gallery/media.ts

Reverts kodadot/nft-gallery#7280
Reasoning:
this "fix" tries to show any `text/html` as image
Is this like saying about this turtle that's clown
Needed for:
- https://github.com/kodadot/nft-gallery/issues/7495#issuecomment-1744959543
- #7248

Revert "fix: mimetype text/html should be image"

---

components/gallery/GalleryItemAction/GalleryItemActionSection.vue

🔧 galleryItem price

---

components/collection/activity/ownerInsightsTabs/HolderTab.vue
composables/collectionActivity/useCollectionActivity.ts

- closes #7519 
⚠️ we will have some issue with large collection

🔧 Holders activity tab

---

components/gallery/GalleryItemAction/GalleryItemActionSection.vue

TESTED on `/bsx/gallery/282897835-6`
**before**
**after**

🔧 highest offer

---

components/drops/useDrops.ts

ref #7375 
>  clicking on Drops link and then going to another page and clicking the drops link again shows no active drops
- click on drops in navbar
- click on any link
- click on drops in navbar again
- content empty

🔧 drops watcheffect

---

composables/useTheme.ts

- close #7571 
- https://github.com/kodadot/nft-gallery/pull/7572#pullrequestreview-1666521167

🔧 isDarkMode

---

components/gallery/GalleryItem.vue
utils/seoImageGenerator.ts

- ref #7375 
Tested on `/ksm/gallery/16759320-8453d0ccb4cb7e9e59-A51-THE_FOUNDRY-00000246`

🔧 GalleryItem SEO

---

components/shared/DropUpload.vue
components/shared/view/BasicImage.vue

- ref https://github.com/kodadot/nft-gallery/pull/7583#issuecomment-1755458189

🔧 BasicImage placeholder

---

components/collection/CollectionDetail.vue

- closes #7529
⚠️ this will round number (2 after comma) on all chains

🔧 round 2 collection card number

---

stores/preferences.ts

🔧 default carbonless false

---

components/collection/drop/Generative.vue

fix: Mint phase time is off for generative drop

---

libs/ui/histoire.config.ts
libs/ui/src/components/NeoSwitch/NeoSwitch.scss
libs/ui/src/scss/tailwind.scss

- ref #8222
- migrate neoSwtich to use tailwind class
- fix darkmode toggle in histoire preview
- fix darkmode vars
- remove unecessary css class

🔧 switch to tailwind & fix histoire darkmode

---

components/collection/CollectionInfo.vue
components/collection/utils/types.ts
components/collection/utils/useCollectionDetails.ts
locales/en.json
queries/subsquid/general/collectionStatsById.graphql

💅 collection max supply

---

composables/transaction/transactionBurn.ts
package.json
pnpm-lock.yaml

⬆️ minimark package

---

components/drops/DropCard.vue

fix: Different number of items in drops page and drop iteself

---

components/collection/drop/HolderOfGenerative.vue

🔧 drop responsive

---

components/drops/DropCard.vue
utils/drop.ts

Drop was marked as ended when it is just disabled

:bug: drop is not ended when drop is disabled

---

queries/subsquid/general/collectionForMint.graphql
queries/subsquid/rmrk/collectionForMint.graphql

Since collection was migrated (using rmrk migrator?), issuer !== current_owner
- close #8151

🔧 create collection for mint

---

components/shared/filters/modules/StatusFilter.vue

fix: Offer.status in burger menu collection

---

components/landing/topCollections/TopCollectionsItem.vue
components/shared/format/Money.vue
utils/format/balance.ts

Reverts 
- kodadot/nft-gallery#8903
- https://github.com/kodadot/nft-gallery/issues/8901
Now it does show price

Revert "fix: One decimal in top collections should be enough"

---

components/landing/topCollections/TopCollectionsItem.vue
components/shared/format/Money.vue
utils/format/balance.ts

Revert "Revert "fix: One decimal in top collections should be enough""

---

components/profile/CollectionFilter.vue
libs/ui/src/components/NeoDropdown/NeoDropdown.scss
libs/ui/src/components/NeoDropdown/NeoDropdown.vue

with #9080 stroke fix 
no stroke fix

feat: Bigger collection filter in profile

---

components/common/ChainDropdown.vue
components/landing/topCollections/TopCollections.vue

fix: top collection mobile chain dropdown

---

assets/styles/components/_connect-wallet.scss

fix: Weird hover in connect wallet 

---

components/chart/PriceChart.vue

access chart instance as per [docs](https://vue-chartjs.org/guide/#access-to-chart-instance) 
also I didn't notice any difference between before and after the fix  [docs](https://www.chartjs.org/docs/latest/developers/api.html#resize-width-height)
did we need it to begin with?
`responsive` is set to `true` 

fix: Price chart on resize error 

---

utils/drop.ts

:wrench: alchemy drop

---

components/teleport/Teleport.vue

as with convo with @dudo50
- #9073
- paritytech/polkadot-sdk#3050

:ambulance: max on XCM results in loss of funds

---

assets/styles/components/_carousel.scss
components/carousel/module/CarouselAgnostic.vue
components/carousel/module/CarouselInfo.vue

feat: More cards on mobile carousels 

---

components/collection/activity/Activity.vue
components/collection/drop/GenerativeLayout.vue
components/collection/drop/HolderOfCollection.vue
components/gallery/GalleryItemHolderOf.vue
components/landing/HeroBanner.vue
components/migrate/steps/SignLoader3.vue
components/profile/CollectionFilter.vue
components/teleport/EDWarningModal.vue
components/teleport/FundsAtRiskWarning.vue

- replace `is-justify-content-center` and `is-align-items-center`
- replace `is-justify-content-space-between`
- replace` is-flex` and `is-flex-direction-column`

replace `is-flex-*` with tailwind equivalent 

---

assets/styles/components/_tippy.scss
components/collection/CollectionInfo.vue
plugins/vueTippy.ts

The issue stems from the Oruga tooltip component's lack of support for properties such as "close delay," which prevents the tooltip from auto-closing when hovered over. The PR resolved this by switching our implementation from Oruga to Tippy, which supports this feature.

Replace the implementation of royalty tooltip with tippy

---

components/teleport/Teleport.vue

fix:  disable teleport on AHK <> KSM

---

assets/styles/global.scss
components/shared/OnRampModal.vue

add funds not opening 
transak overlay

fix: on ramp modal issues

---

assets/styles/components/_nft-card.scss

🔧 nft-card border color

---

components/items/ItemsGrid/utils/useSearchParams.ts
tests/e2e/collection.spec.ts

`sq_contains` is not  present in **speck** using `sq_eq` instate 

fix: Search by #number in  collections not working

---

libs/static/src/indexers.ts

fix: typo prefix endpoints

---

components/common/ChooseCollectionDropdown.vue
components/create/CreateCollection.vue
components/create/CreateNft.vue
components/massmint/Massmint.vue
locales/en.json
tests/e2e/createcollection.spec.ts
tests/e2e/createnft.spec.ts

maybe not the best solution, let me know

Disable RMRK1/2 Minting

---

components/collection/drop/GenerativePreview.vue

fix: generate variants on fails base64 image

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
components/items/ItemsGrid/ItemsGridImage.vue
components/shared/BreadcrumbsFilter.vue
components/shared/filters/modules/StatusFilter.vue
locales/en.json

no buy now on hovering cards when exploring, also changed buy now to listed on kusama: 
Buy button disabled and cart button hidden on gallery item:

Disable buy on RMRK1/2

---

components/collection/drop/modal/paid/MintOverview.vue

remove funds warning from overview modal

---

components/shared/SigningModal/SigningModal.vue
composables/autoTeleport/useAutoTeleportTransactionActions.ts

https://github.com/kodadot/nft-gallery/assets/44554284/75e645aa-9d15-4fad-85a4-efda1b0410fd

fix: Retry transaction is not displayed after canceling signing

---

components/buy/SuccessfulBuyModal.vue
components/collection/drop/Generative.vue
components/collection/drop/PaidGenerative.vue
layouts/generative-mint-layout.vue

`<ListingCartModal />`  is already present in the explore layout and profile page
- open the listing modal in the explore page or profile page , now only one will be opened 
https://github.com/kodadot/nft-gallery/assets/44554284/dc654a4a-b534-4d50-acf7-ef5e58b6c8b5

fix: Multiple listing modals being opened at once

---

components/common/listingCart/ListingCartModal.vue
layouts/generative-mint-layout.vue
layouts/unlockable-mint-layout.vue

* #9650
removed `<ListingCartModal />` from `Generative` and `PaidGenerative`
but did not replace it with   `<ListingCartModal />` in  `unlockable-mint-layout`

add modal to layout

---

tests/e2e/footer.spec.ts

issue was happening because the https://hello.kodadot.xyz/tutorial page has a hydration problem: 
https://github.com/kodadot/nft-gallery/assets/36627808/23019dff-b631-4fe1-9fde-6849a25b2778

Footer test fix

---

composables/drop/massmint/useDropMassMintUploader.ts
composables/transaction/mintToken/constructDirectoryMeta.ts

fix: preheat on massmint

---

components/common/listingCart/shared/ListingCartItemDetails.vue
components/common/shoppingCart/utils.ts
composables/drop/massmint/useDropMassMintListing.ts
composables/useListingCartModal.ts
stores/listingCart.ts

fix until https://github.com/kodadot/private-workers/issues/87 is implemented and  "setMetadata" is done earlier  as @preschian  mentioned
> But, I think it can solve the problem if we also put metadata in our minting step. Since it works on the "success modal". In https://github.com/kodadot/private-workers/issues/87#issuecomment-1997444473, I put "setMetadata" in the steps 2 and 6
https://github.com/kodadot/nft-gallery/assets/44554284/1b84cd9e-203e-42af-acd5-72b796794fa8

fix: At Success modal is a preview of iterated art (good), and on the listing is the default. (bad)

---

components/drops/BasicDropCard.vue
components/drops/CreateCalendarEventModal.vue
components/drops/DropsGrid.vue
components/drops/calendar/DropPreviewModal.vue
components/drops/calendar/DropsCalendar.vue
components/drops/utils.ts
locales/en.json

can be tested after https://github.com/kodadot/private-workers/pull/96

fix: drop calendar small visual things

---

components/collection/drop/MintButton.vue

fix: Clicking on connect wallet on old drops redirects you to collection

---

components/collection/drop/modal/paid/MintOverview.vue
composables/drop/massmint/useDropMassMint.ts
composables/drop/massmint/useDropMassMintPreview.ts
composables/drop/massmint/useDropMassMintState.ts

>maybe if it would not be all at once?
added a max of 3 at once 

fix: Hung up on slow rendering arts

---

queries/subsquid/general/topCollections.graphql

The `owner` number on the search bar is now close to the one on the collection page. There will still be a little difference because the indexer and the front-end calculate the owner differently.
ref: https://github.com/kodadot/stick/blob/f7d0084453bf98017521ed85e5b84384df1c8608/src/mappings/utils/helper.ts#L143

fix: Numbers in search bar are bit off

---

components/shared/BreadcrumbsFilter.vue
pages/[prefix]/explore/items.vue

Multiple searches would run one with `listed = false` and then another one with `listed = true` after the query param was added and then a watcher would tiggers a `resetPage(1)`
now that the `listed` is added inside the middleware only one call is made

fix: Buy now stops working after a few redirects

---

assets/styles/layouts/_main-navigation.scss
components/Navbar.vue

fix: Mobile menu gone on 640-1024px

---

components/collection/drop/modal/DropConfirmModal.vue

free mint would get stuck on the first step after adding your email and pressing confirm 
it wouldn't move to the next step (confirm email)
https://github.com/kodadot/nft-gallery/assets/44554284/f07666ad-0a83-438d-8e83-4f70dc848223
https://github.com/kodadot/nft-gallery/assets/44554284/1f6a0902-801e-4e45-8fae-a3533bd9edce

fix: free mint stuck on the first step 

---

libs/static/src/chains.ts

I have a "poor" account (sub 1 DOT)
and basically everytime I am trying to do a drop I will have an autoteleport that is asking me to get all my balance from Polkadot to AssetHub.
This fix basically decreases ED so cases like that are not triggered

:wrech: trigger of XCM autoteleport on ill-logical cases

---

components/collection/CollectionHeader/CollectionBanner.vue

Related: https://github.com/kodadot/nft-gallery/issues/9937
| before | after |
| <img width="2168" alt="Screenshot 2024-04-03 at 21 06 07" src="https://github.com/kodadot/nft-gallery/assets/734428/08e242e7-5d0f-4075-b4a3-dd9fc45df8c6"> | <img width="2168" alt="Screenshot 2024-04-03 at 21 06 45" src="https://github.com/kodadot/nft-gallery/assets/734428/a86222ba-eed2-42d5-b9a9-1bbfbc2d35f4"> |

refactor: remove migrate button on collection page

---

components/explore/ExploreSort.vue
components/landing/topCollections/TopCollections.vue
components/search/Search.vue
composables/useHasRoute.ts
composables/useRouteSortByOptions.ts
locales/en.json

@prury this also touches sorting on both items and explore page, pls also check that sorting works as expected on those pages , thanks 
1 - sortby filters working from `view all` button
2 -  can enter an valid url  with  sort by filters inside the collection page  
https://github.com/kodadot/nft-gallery/assets/44554284/58395896-a2c3-4a01-b5e2-d2beaebc7d9b

feat: View all - top collections

---

components/gallery/GalleryItem.vue
composables/useNft.ts

- Fix #9987
`nft.metadata` and `nft.meta.id` return different results:
```json
{
"data": {
"nftEntityById": {
"id": "115-2404377033",
"metadata": "https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404377033&metadata=ipfs:%2F%2Fbafybeid6qweu5csznxnfa26aundrrdejg3l3sfiyhotpbokbt5hvm347ze%2F2.json",
"meta": {
"id": "ipfs://bafkreih2bq7dqqmtz4xqhfdjbo6wsyr6ozfhtvn4dyqkeokggmtrrrrw3i"
}
}
}
}
```
the correct one is `nft.metadata`. in this PR prioritize fetch `nft.metadata` instead of `nft.meta.id`

fix: prioritize nft.metadata rather than nft.meta.id

---

components/base/MediaItem.vue
components/common/successfulModal/MultiItemMedia.vue

fix: Bigger previews in the success modal

---

composables/drop/massmint/useDropMassMintListing.ts

Fix #9971 
| set price | after set price |
| ![Capture-2024-04-06-211834](https://github.com/kodadot/nft-gallery/assets/734428/99b3ebb0-82af-4157-93d5-a9b543461ec0) | ![Capture-2024-04-06-212010](https://github.com/kodadot/nft-gallery/assets/734428/7723bc6c-b95a-4436-be77-5de80542afdd) |

fix: show sn in drops listing

---

components/drops/DropCardSkeleton.vue

fix: Mobile SkeletonDropCard doesnt match normal DropCard

---

components/items/ItemsGrid/ItemsGrid.vue
components/shared/nftCard/NftCardSkeleton.vue

https://github.com/kodadot/nft-gallery/assets/16473062/40fc9e4b-e645-4f64-b6d9-a886fc9fa13d

fix: grid item skeleton cards size issue

---

components/collection/drop/MintStepper.vue
utils/drop.ts

>  limit tilescapes drop to max 4 pieces 

fix: Unable to mint Tilescapes: Stuck on loading to ipfs

---

components/gallery/useGalleryItem.ts

fix: gallery item genart animation not working

---

components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue
components/collection/drop/modal/PaidMint.vue

- @prury-temporary please review
https://github.com/kodadot/nft-gallery/assets/44554284/1dbc2bb7-445f-4539-8c8c-65fa9fad52ec

fix: Paid mint modal can't `try again` after transaction error 

---

components/codeChecker/PreviewCard.vue
components/codeChecker/SandboxIFrame.vue
libs/ui/src/components/MediaItem/type/IFrameMedia.vue

@prury pls test both `/gallery` and `/code-checker`
https://github.com/kodadot/nft-gallery/assets/44554284/95ff37ad-278b-45dc-906d-795689964bef

fix: Make fullscreen iframe to fit on code-check page

---

.github/PULL_REQUEST_TEMPLATE/QUICK_PULL_REQUEST_TEMPLATE.md

As we have deleted two kinds of PR templates by #10147, it's better to have a screenshot option for the quick PR template

chore: add screenshot to PR template

---

components/common/autoTeleport/AutoTeleportModal.vue

Clicking outside to close the modal will only work if all steps are completed 
https://github.com/kodadot/nft-gallery/assets/44554284/b99abc15-56ee-47a5-a87c-67e472196a0a

fix: Autoteleport modal closing when clicking outside

---

package.json
pnpm-lock.yaml

- 
-
This PR features the latest version of the ParaSpell package. In the latest version, we introduced fully custom multilocation support as well as custom fee asset selection. The **next version** will include the **assetClaim** function that will allow users to recover assets they lost during issues with XCM. We will contact the Kodadot team about the implementation then.

Update ParaSpell to v5.2.1

---

components/collection/drop/modal/PaidMint.vue
components/collection/drop/modal/utils.ts
composables/useAsyncRetry.ts

Couldn't reproduce but this should fix it
https://github.com/kodadot/nft-gallery/assets/44554284/d8e940db-642a-4fc7-aca4-8e3f23916992

fix: 0 nfts in congrats modal

---

components/profile/create/Modal.vue
components/profile/create/stages/Form.vue
services/profile.ts

Make possible it possible not to be necessary to enter all fields on Profile & handler profile error

---

components/profile/follow/Tab.vue
components/profile/follow/UserRowSkeleton.vue
libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue

fix: Loaders and skeletons for new profile

---

components/profile/follow/UserRow.vue

fix:Truncation in followers/following tab

---

components/common/ConnectWallet/WalletAssetIdentity.vue
components/identity/IdentityItem.vue
components/navbar/ProfileDropdown.vue
components/shared/ProfileAvatar.vue
composables/useFetchProfile.ts

feat: Replace icons with uploaded profile picture

---

components/collection/activity/events/Events.vue
components/collection/utils/useCollectionDetails.ts
components/drops/useDrops.ts
composables/collectionActivity/useCollectionActivity.ts
composables/drop/useGenerativeDropMint.ts
composables/useFetchProfile.ts
composables/useUnlockable.ts

Before:  https://canary.kodadot.xyz/ahp/drops/aeroloom
There are three invalid requests with empty id and also two duplicate requests. It takes about 1~2 seconds to load these unnecessary requests.
After fix: 
Remove all invalid requests.

Perf: avoid invalid requests when loading drop page

---

components/carousel/CarouselTypeRelated.vue
components/collection/drop/GenerativeLayout.vue
components/common/LoadLazily.vue
components/common/LoadLazly.vue
composables/useOnceIsVisible.ts
pages/[prefix]/drops/[id].vue

- fetching the drop a little before inside the `setup` 
- made some components lazy 
- drop gallery item is loaded once the divider is seen  

perf: improve drop first load speed

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
services/profile.ts
utils/coinprice.ts

There are still two issues related to the indexer side for Base. @vikiival 
1. incorrect price amount 
2. missing from/to address

fix: Activity table does not work on Base

---

components/codeChecker/CodeChecker.vue
components/codeChecker/issueHint/KodaHashCalledOnce.vue
components/codeChecker/types.ts
locales/en.json

fix(code-checker): Problematic art passing

---

components/collection/drop/CollectedByAvatar.vue
components/shared/ProfileAvatar.vue

feat: Profiles: Show on Drops profile pictures instead of polkadot wallet

---

components/identity/module/IdentityPopover.vue
components/identity/module/IdentityPopoverFooter.vue
components/identity/module/IdentityPopoverHeader.vue
components/identity/utils/useIdentityStats.ts
components/profile/ButtonConfig.vue
components/profile/FollowButton.vue
components/profile/ProfileDetail.vue
locales/en.json
stores/identityMint.ts

feat: Hover card changes

---

components/profile/ProfileDetail.vue
components/profile/create/Modal.vue
components/profile/follow/UserRow.vue
composables/useVerifyAccount.ts
services/profile.ts
stores/wallet.ts
utils/constants.ts

[ Currently, only support Polkadot address ]
Add verified process before the below action: create profile / edit profile / follow / unfollow
It would ask for signing a message on the wallet extension before action. The verified message would be saved on localstorage forever unless you disconnect wallet / switch account.

feat: verification for Polkadot address

---

utils/ipfs.ts

fix(ipfs): remove dynamic metadata check from sanitizeIpfsUrl

---

components/gallery/useGalleryItem.ts

fix: Wrong size of NFT preview

---

components/collection/drop/GenerativePreview.vue
components/shared/SkeletonLoader.vue
locales/en.json

The iframe is taking some time to load, a loader will help giving the user feedback about what's going on. 

fix: Drop page does not work on mobile

---

composables/autoTeleport/useAutoTeleportTransitionDetails.ts

There is a small difference of amount arriving , seems some extra fee was added , increasing the buffer percent fee fixed the issue.
@dudo50 any idea , is this related to the delivery fee that we were talking about a couple of month ago?
[failed tx](https://assethub-polkadot.subscan.io/extrinsic/0xc26ed36a3139f7bcd5338275c60315eeae2512a5773bb8ae3574b915e315bf8d)
https://github.com/kodadot/nft-gallery/assets/44554284/85e49933-471a-4bf8-9f51-a5e02b7e4dfa
https://github.com/kodadot/nft-gallery/assets/44554284/314b396d-6f0f-4f78-a368-4e4fa25f683a

fix: Rift: Minting 4 items - error

---

libs/ui/src/components/NeoModal/NeoModal.vue

fix: attach fall through attributes to teleport component

---

components/profile/create/stages/Form.vue
locales/en.json

feat: Markdown supported copy in offchain profile text fields

---

components/profile/create/Modal.vue
composables/useModalIsOpenTracker.ts

issue: initial step was being set on modal close on not when opening the modal
https://github.com/kodadot/nft-gallery/assets/44554284/de16b582-7c1d-454c-bb25-9d4a1993af38

fix: Clicking on `edit existing profile` opens  wrong modal state

---

utils/constants.ts

Deny list is for entities that did not accepted ToC of Koda.
Currently on the deny list are entities that:
- Manipulated market
- Were unable to provide correct metadata - minting outside of KodaDot
- Minting NSFW content
This removes @AshutoshSingh00001 from the deny list as we were finally noticed that he fixed metadata for the Polkadot Punks :)
Related issues:
- https://github.com/kodadot/nft-gallery/issues?q=is%3Aissue+author%3AAshutoshSingh00001+is%3Aclosed
Original comes from commit - https://github.com/kodadot/nft-gallery/commit/14cc741ba120a310754bfc3e4e56322b87de741f
PR - #9110
- **Revert ":wrench: add new bad boyz to deny list"**
- **:wrench: return market manipulator to deny list**

:wrench: Remove people from AssetHub deny list 

---

components/carousel/CarouselTypeGenerative.vue
components/landing/LandingPage.vue
components/navbar/ProfileDropdown.vue
components/profile/ProfileDetail.vue
components/profile/create/Modal.vue
components/profile/create/openProfileModal.ts
components/profile/create/stages/Success.vue
composables/useFetchProfile.ts
composables/useProfile.ts
stores/profileOnboarding.ts

feat: Profiles: Popup to create profile

---

components/shared/Avatar.vue

fix: The default avatars of EVM addresses would overlap each other

---

components/drops/Drops.vue
components/drops/calendar/DropsCalendar.vue

- When there is no oncoming drop calendar, it only shows title and separator line.
hide empty drop calendar section

fix: hide empty drop calendar section on drops page

---

components/drops/Drops.vue
components/drops/DropsGrid.vue

negative skeleton count was breaking the grid
https://github.com/user-attachments/assets/e145e315-2d37-4d17-adcd-a1efad2a0532

fix: base `/drops` grid not loading

---

components/create/CreateCollection.vue
components/create/CreateNft.vue

fix: Hide immutable, Base in Create

---

components/collection/drop/PartyModal.vue
composables/useWallet.ts

1. modal close did not accept `party mode`
2. chatted with @exezbcz  and preferences should be kept between sessions
https://github.com/user-attachments/assets/78105e9e-785c-43d6-87b3-ad50944d399a

fix: Party kit popup does not remember the state

---

composables/useProfile.ts

if all requirements are met (interacting with landing carousel and sidebar) and then we connect a wallet (with a profile), once we start fetching the profile the modal is shown
@Jarsen136  what case is having `isLoading` inside `hasProfile`  covering. don't wanna break something else, asking since this was added here #10707

fix: Landing create modal still appearing with a profile

---

components/drops/Drops.vue

fix: Drops on Base show AHP drops

---

components/collection/drop/MintButton.vue
locales/en.json

feat: Mint not started yet

---

components/profile/FollowButton.vue
components/profile/create/Modal.vue
components/profile/follow/UserRow.vue
components/shared/modals/keyboardShortcutsModal.vue
composables/useVerifyAccount.ts
services/profile.ts

Reverts kodadot/nft-gallery#10555
There is something wrong happen on worker side. https://github.com/kodadot/private-workers/pull/192

Revert "feat: advance verify for profile changes"

---

components/profile/ProfileDetail.vue

fix: Profile picture size crippled 

---

tests/e2e/collection.spec.ts

replace collection with one with send events, the other test it's failing because of #10930

fix: Collection interactions test

---

components/common/ConnectWallet/WalletAsset.vue
composables/useBalance.ts
composables/useMultipleBalance.ts
composables/useToken.ts
stores/identity.ts
stores/wallet.ts

- if sub wallet is connected and user lands on `/base` the address is not formatted correctly   
https://github.com/user-attachments/assets/b368d495-7858-4fc5-88bd-c9bcfcdd1865
covers case where wallet vm and current chain's vm do not match, since prefix is unknown at that moment we are resorting to a fallbacks instate of not making a balance fetch
evm wallet is connected , chain is ahp , navbar makes a balance fetch
this happens in the navbar and sidebar, in these scenarios what prefix should be fetched ?
@kodadot/internal-dev  pls feel free to suggest any other solution.
https://github.com/user-attachments/assets/0c8d1f72-a3e4-4653-9c55-5804c6665a4a

fix: balance fetching bugs

---

components/offer/OfferExpirationSelector.vue
libs/ui/src/components/NeoDropdown/NeoDropdown.vue

fix: Offer expiration dropdown moving on scroll

---

components/common/ConnectWallet/ConnectEvm.vue
composables/useWallet.ts

- add: make sure to close any active connections before opening  web3modal
- fix: use async version of `disconnect` method

fix: Talisman EVM wallet connect failing

---

components/profile/utils.ts
tests/farcaster.spec.ts

fix: Profile weird link formating from warpcast

---

composables/useListingCartModal.ts

fix: Listing cart cleared before modal is fully closed

---

pages/drop-checker/[chain]/[collection-id].vue

wrapped `<tr>` with `<thead>` and `<tbody>`

fix: Warning <tr> cannot be child of <table>, according to HTML specifications.

---

components/collection/drop/ItemsGrid.vue
components/items/ItemsGrid/ItemsGrid.vue
components/items/ItemsGrid/ItemsGridImage.vue
components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
layouts/unlockable-mint-layout.vue

- listing from the nft grid should not be possible in the drop page 
- removed listing cart mini in the drop page
https://github.com/user-attachments/assets/b580e3ad-7e09-4cad-b317-062ba5ad8eae

fix: Listing popup displayed with listing modal

---

components/collection/drop/GenerativePreview.vue

Slider Bar should not render when drop.count is infinite

conditionally rendering slider

---

components/drops/BasicDropCard.vue
components/drops/calendar/DropPreviewModal.vue
components/drops/utils.ts

fix: Drop calendar: Collection with price that is not set should be TBA

---

composables/useUpdateProfile.ts

upload profile images in parallel

feat: faster profile creation

---

assets/styles/pages/create.scss
components/create/CreateNft.vue

fix: Create NFT - adjust font

---

components/offer/MakeOffer.vue
locales/en.json

0.05dot + tx fee  
0.0005 KSM + tx fee

feat: offer fees displayed in the modal

---

components/shared/SkeletonLoader.vue

if you open the signing modal the **second time**, that section is not fixed starts "dancing"
````
<template>
<SigningModal
:title="'asd'"
:is-loading="isLoading"
:status="status"
/>
<NeoButton @click="open">
open
</NeoButton>
</template>
<script lang="ts" setup>
import { NeoButton } from '@kodadot1/brick'
import type { TransactionStatus } from '@/composables/useTransactionStatus'
definePageMeta({
layout: 'no-footer',
})
const isLoading = ref(false)
const status = ref(TransactionStatus.Unknown)
const opened = ref(false)
const sleep = (ms: number) => {
return new Promise(resolve => setTimeout(resolve, ms))
}
const open = async () => {
isLoading.value = true
status.value = TransactionStatus.Casting
await sleep(400)
status.value = TransactionStatus.Broadcast
await sleep(1000)
status.value = …
```

fix: Minting NFT - "dancing"

---

composables/autoTeleport/useAutoTeleportTransitionDetails.ts
composables/useMultipleBalance.ts

reviewers could you guys also test, thanks
https://github.com/user-attachments/assets/539607c6-7bad-4877-bb5c-a0ea884a7725
https://github.com/user-attachments/assets/62160e21-46cb-4cea-b116-14e34168e9f8

fix: waiting times for mint

---

components/common/ChooseCollectionDropdown.vue
components/create/CreateNft.vue
composables/massmint/useMassMint.ts
stores/wallet.ts

https://github.com/user-attachments/assets/ab1765ce-a9d0-46e4-9694-9fc4d7238efb

fix: Create NFT empty collection list

---

components/collection/CollectionHeader/CollectionBanner.vue
queries/subsquid/general/collectionByIdMinimal.graphql
queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql

feat: collection banner use `banner` field

---

components/common/autoTeleport/AutoTeleportActionButton.vue
components/common/itemTransfer/ItemTransferModal.vue
components/transfer/TransferConfirmModal.vue
composables/useKeyboardKeys.ts
libs/ui/src/components/NeoButton/NeoButton.vue
utils/shortcuts.ts

continue #10306
@Jarsen136 let me know if you find anything, this approach seems to fix the issues that had previously and it's simpler imo

feat: Control return to confirm action

---

components/collection/utils/useCollectionDetails.ts

https://github.com/user-attachments/assets/f2d657a2-2767-4aad-9930-ba5deb7e5fa4

fix: Collection Explorer details not loading when going back

---

components/codeChecker/CodeChecker.vue
components/codeChecker/codechecker.config.js
components/codeChecker/utils.ts
components/codeChecker/validate.ts

Arkain faced some issues doing his drop 
- add: check if `p5.min.js` file is present, will show 
- add: check if `postMessageKoda` is called , will show 
@JustLuuuu would you want a separate check ? or is this clear enough? or we can change the copy to include 
postMessageKoda() is not called at the end of the draw() function
````
function draw() {
background(bg)
// Once the drawing is done, we can send the image to the parent window
postMessageKoda()
}
````

feat: code checker more validation

---

components/drops/Drops.vue
locales/en.json

fix: Remove "every Thursday" from Drops

---

package.json
pnpm-lock.yaml

The following PR features the latest version of ParaSpell XCM SDK.
We introduced many new features since v6 such as:
- Multilocation asset selection
- Advanced symbol selection
- Support for new nodes and new complex scenarios
- Support for PAPI version (You do not need to install both packages. Just one package of your choice.)
And many more. Feel free to explore changelogs:
https://github.com/paraspell/xcm-tools/releases
- tested and all works on dev version in localhost.

Update ParaSpell to v7.2.0

---

components/common/EditNftModal.vue
components/common/NonRecommendFieldNotification.vue
locales/en.json

feat: Item Edit: Limit Name and Image Update

---

components/collection/EditModal.vue

feat: collection Edit - Limit Name and Image Update

---

components/create/CreateNft.vue
composables/massmint/useMassMint.ts
composables/transaction/mintToken/utils.ts
composables/transaction/types.ts
queries/subsquid/general/collectionForMint.graphql

- minting nft did not work ❌
- minting collection worked ✅
https://github.com/user-attachments/assets/f6f63d79-e82f-4e3d-b6ee-814c20006e5d

fix: NFT minting error

---

components/buy/Buy.vue
components/codeChecker/issueHint/CodeBlock.vue
components/collection/CollectionHeader.vue
components/collection/HeroButtonRefreshMetadata.vue
components/collection/HeroButtons.vue
components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue
components/collection/drop/modal/shared/SuccessfulDrop.vue
components/common/ConnectWallet/ConnectSubstrate.vue
components/common/ConnectWallet/WalletAssetIdentity.vue
components/common/ShareDropdown.vue
components/common/successfulModal/ShareSocialsSection.vue
components/common/successfulModal/TransactionSection.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
components/identity/module/IdentityLink.vue
components/identity/module/IdentityPopoverHeader.vue
components/profile/FollowButton.vue
components/profile/ProfileDetail.vue
components/profile/follow/UserRow.vue
components/shared/TransactionLoader.vue
components/transfer/Transfer.vue
composables/useToastOruga.ts
utils/copyToClipboard.ts

chore: rename useToast()

---

components/profile/ProfileDetail.vue

fix: profile page `swaps` tab is always visible

---

components/common/ChainDropdown.vue
composables/usePrefix.ts
tests/e2e/redirect.spec.ts
utils/chain.ts

I can't recall what `useRoute` does on `usePrefix`. Did I break something with these changes?

fix: remove useRoute warning

---

composables/transaction/mintToken/transactionMintStatemine.ts

fix: Mass mint with one nft would lead to wrong metadata

---

.github/workflows/playwright.yml
libs/static/src/endpoints.ts

ci: adjust assethub endpoint

---

components/massmint/OnBoarding.vue

fix: switch button on mass mint onboarding

---

components/MessageNotify.vue
components/base/MediaItem.vue
components/blog/BlogPost.vue
components/collection/CollectionHeader/CollectionBanner.vue
components/collection/HeroButtons.vue
components/collection/drop/AddFundsModal.vue
components/collection/unlockable/CountdownTimer.vue
components/collection/unlockable/UnlockableTag.vue
components/collectionDetailsPopover/CollectionDetailsPopover.vue
components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
components/common/listingCart/ListingCartMini.vue
components/drops/TimeTag.vue
components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
components/gallery/UnlockableTag.vue
components/massmint/Massmint.vue
libs/ui/src/scss/tailwind.scss

refactor: remove some import abstracts/variables

---

netlify.toml
package.json

ci: adjust netlify deployment memory size

---

components/items/ItemsGrid/ItemsGrid.vue
components/items/ItemsGrid/ItemsGridImage.vue
components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
components/shared/nftCard/NftCard.vue
components/swap/GridList.vue

Click nft would open new tab on these pages
1. select others swap items
2. select my swap items
3. review swap

fix: clicking on item in atomic swap should open new tab

---

components/shared/Markdown.vue

`/ahp/collection/244`
`/ahp/collection/281`

fix: Not recognising links in collection description

---

components/common/ConnectWallet/WalletMenuItem.vue

fix: warning message on empty accounts

---

components/collection/drop/GenerativeLayout.vue
components/collection/drop/ItemsGrid.vue
components/collection/drop/RefreshMetadata.vue
components/items/ItemsGrid/ItemsGrid.vue
composables/useNft.ts
services/oda.ts

| before | after |
| <img width="2032" alt="Screenshot 2025-02-07 at 14 22 19" src="https://github.com/user-attachments/assets/62608bdc-a303-4246-a5f3-b3df33ca5be9" /> | <img width="2032" alt="Screenshot 2025-02-07 at 14 22 21" src="https://github.com/user-attachments/assets/64cfa3df-cd22-47b6-af92-b6f86198280c" /> |

feat: fetch oda on drops page

---

components/collection/CollectionTrades.vue
components/swap/CreateCollectionSwapButton.vue
components/trade/makeOffer/CreateCollectionOfferButton.vue
components/trade/makeOffer/MakeOfferModal.vue
components/trade/makeOffer/MakeOfferSingleItem.vue
components/trade/types.ts
composables/useTradeActionClick.ts
i18n/locales/en.json
queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql
queries/subsquid/general/highestOfferByCollectionId.graphql

feat: Create Collection Atomic Offer
