kodadot/nft-gallery

components/collection/CollectionDetail.vue
components/collection/CollectionList.vue
components/shared/gallery/Gallery.vue
tests/cypress/support/commands.ts

test: adjust e2e test for collection and gallery

---

components/series/SeriesTable.vue

:bug: fix urlPrefix on SeriesTable

---

components/TheFooter.vue
styles/abstracts/_derived-variables.scss
styles/layouts/_footer.scss
styles/layouts/_main-navigation.scss
styles/themes/_dark.scss
styles/themes/_light.scss

#4570 all landing color to black

---

components/search/SearchSuggestion.vue
styles/components/_search.scss

:bug: search history alignment + clickable area 

---

styles/layouts/_main-navigation.scss
styles/themes/_dark.scss

#4569 hover state of connect button

---

components/common/ColorModeButton.vue
styles/layouts/_main-navigation.scss
styles/themes/_dark.scss
styles/themes/_light.scss

#4566 Hover effect on links in navbar

---

libs/ui/src/components/CardArticle/CardArticle.scss
libs/ui/src/components/NeoNftCard/NeoNftCard.scss
libs/ui/src/scss/animation.scss
libs/ui/src/scss/variable.scss
styles/abstracts/_animations.scss
styles/components/_carousel.scss
styles/components/_collection-card.scss
styles/components/_top-collections.scss
styles/themes/_dark.scss
styles/themes/_light.scss

fix: hover transition effect on cards

---

components/Navbar.vue

:bug: make color mode navbar item

---

components/carousel/utils/useCarouselSpotlight.ts
components/collection/CollectionList.vue
components/rmrk/Gallery/CollectionItem.vue
components/rmrk/Gallery/GalleryCard.vue
components/rmrk/Gallery/PaginatedCardList.vue
components/shared/gallery/Gallery.vue
queries/subsquid/general/collectionCuratedList.graphql
utils/carousel.ts

fix: images on carousel, spotlight, explorer, and gallery card

---

components/search/SearchSuggestion.vue
tests/cache.spec.ts
tests/ipfsUtils.spec.ts
utils/cachingStrategy.ts
utils/config/ipfs.ts

fix: images on search components

---

components/landing/SearchLanding.vue
styles/components/_search.scss

:bug: landing layout shapes

---

components/bsx/Gallery/Item/GalleryItem.vue
components/carousel/utils/useCarousel.ts
components/movr/Gallery/Item/GalleryItem.vue
components/rmrk/Gallery/GalleryCard.vue
components/rmrk/Gallery/GalleryItem.vue
components/unique/Gallery/Item/GalleryItem.vue
utils/carousel.ts
utils/fetch.ts
utils/ipfs.ts

fix: empty meta.image on carousel and remove pinata head request on gallery item

---

components/bsx/Create/CreateToken.vue
locales/en.json

🔧 bsx classic mint no royalty

---

components/bsx/Gallery/Item/GalleryItem.vue
components/gallery/GalleryItem.vue
components/movr/Gallery/Item/GalleryItem.vue
components/rmrk/Gallery/GalleryItem.vue
components/shared/MessageNotify.vue
components/unique/Gallery/Item/GalleryItem.vue
locales/en.json

`?redesign=true&message=congrats`

🔧 GalleryItem redesign MessageNotify

---

queries/config/.graphqlconfig
utils/constants.ts

New rubick release `https://squid.subsquid.io/rubick/v/008/graphql`
ref kodadot/rubick#163 & kodadot/packages#83

✨ rubick 008 release

---

components/shared/MessageNotify.vue

continue https://github.com/kodadot/nft-gallery/pull/4650#issuecomment-1378993722

🔧 MessageNotify on right side

---

components/base/BaseCollectionForm.vue
components/bsx/Create/CreateCollection.vue
components/bsx/Create/CreateToken.vue
components/rmrk/Create/CreateCollection.vue
components/rmrk/Create/CreateToken.vue
components/rmrk/Create/CreativeMint.vue
components/rmrk/Create/SimpleMint.vue
components/unique/Create/CreateCollection.vue
components/unique/Create/CreateToken.vue

🔧 full width minting button

---

nuxt.config.js
package.json
plugins/sentry.ts
pnpm-lock.yaml

feat: Setup Sentry Session Replay

---

nuxt.config.js
package.json
pnpm-lock.yaml

chore: enable source maps for sentry

---

nuxt.config.js

ci: skip custom sentry on windows

---

components/identity/IdentityIndex.vue
components/identity/utils/useIdentity.ts

fix: reactive identity

---

components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
styles/global.scss
styles/themes/_dark.scss

fix: Explorer Pagination and View update 

---

package.json
pnpm-lock.yaml

:ambulance: bsx is down

---

components/identity/module/IdentityPopover.vue

fix: Popup on links in cards

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue

fix: Button states when not connected on gallery item

---

components/CookieBanner.vue
nuxt.config.js
package.json
plugins/pwa.ts
plugins/vueGtag.ts
pnpm-lock.yaml

fix: use workbox-window package

---

store/preferences.ts

🔧 collection small layout

---

components/gallery/GalleryItemAction/GalleryItemActionSection.vue
components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue

feat: Mobile Gallery Item: Full width on buy & Make Offer

---

components/shared/gallery/Gallery.vue

fix(sentry): type error about reading id

---

components/identity/module/IdentityLink.vue

(https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#4761 color identity mobile

---

components/gallery/GalleryItem.vue
components/gallery/GalleryItemMoreActionBtn.vue
nuxt.config.js
package.json
utils/config/ipfs.ts
utils/ipfs.ts

fix: cors when download an image

---

components/gallery/GalleryItem.vue

fix: Missing collection link

---

utils/ipfs.ts

fix: CarouselTypeNewestList: TypeError: undefined is not an object

---

components/gallery/GalleryItem.vue
components/gallery/GalleryItemButton/GalleryItemButton.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
components/identity/module/IdentityLink.vue
components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
libs/ui/src/components/NeoButton/NeoButton.scss
libs/ui/src/components/NeoButton/NeoButton.vue
libs/ui/src/components/NeoDropdown/NeoDropdown.vue
libs/ui/src/index.ts
plugins/icons.ts

feat: setup fa icon for oruga

---

components/identity/utils/useIdentity.ts

refactor: remove `IDB` on identity

---

.github/workflows/e2e.yml

ci: retry flaky test

---

components/bsx/Offer/OfferList.vue
components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
queries/subsquid/bsx/offerListByNftId.graphql

- missing highest offer when own offer

🔧 show own offer

---

components/carousel/module/CarouselInfo.vue

🐛 chain on carousel nft cards

---

package.json
patches/@nuxt__webpack-edge@2.16.0-27720022.54e852f.patch
pnpm-lock.yaml

fix: patch hmr on nuxt bridge

---

components/landing/FeaturedArticles.vue

chore: Add the newest article on KodaDot landing page

---

components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue

fix: default activity tab category on item

---

layouts/explore-layout.vue

#4867 remove footer from explore

---

components/navbar/NavbarExploreOptions.vue

fix: Rename Gallery to Items

---

utils/config/ipfs.ts

feat: image beta on localhost and non-production

---

components/explore/ExploreChain.vue
components/explore/ExploreSort.vue

feat: bring existing query to chain and sort

---

utils/constants.ts

🚑  deny malicious rmrk user

---

locales/en.json
locales/fr.json

Fix: typos

---

components/navbar/ChainSelectDropdown.vue

fix displayed rmrk to kusama

---

components/media/type/VideoMedia.vue
libs/ui/src/components/MediaItem/type/ImageMedia.vue
libs/ui/src/components/NeoNftCard/NeoNftCard.scss
libs/ui/src/components/NeoNftCard/NeoNftCard.vue
styles/components/_carousel.scss

fix: NFT cards explore + landing

---

components/common/ConnectWallet/ConnectWalletModal.vue
components/common/ConnectWallet/WalletMenuItem.vue
styles/components/_connect-wallet.scss

fix: icons in wallet dialog redesign

---

components/landing/EsCarbonless.vue
components/rmrk/Create/CreateToken.vue
components/rmrk/Create/CreativeMint.vue
components/rmrk/Create/SimpleMint.vue
pages/carbonless.vue
tests/urlTransform.spec.ts
utils/urlTransformer.ts

🔧 rmrk gallery item path

---

components/Navbar.vue
components/bsx/Create/CreateToken.vue
components/media/PreviewMediaResolver.vue
package.json
pnpm-lock.yaml
utils/cachingStrategy.ts
utils/idbStore.ts

refactor: remove idb-keyval

---

plugins/pwa.ts

fix: check serviceWorker in navigator

---

components/carousel/utils/useCarouselSpotlight.ts
queries/collectionCuratedList.graphql
queries/subsquid/general/collectionLastList.graphql

> Just start from the top. 
We have an issue here so I ordered by newest created collection from given list

✨ spotlight curated list

---

nuxt.config.js
package.json
plugins/seoMetaGenerator.ts
pnpm-lock.yaml
tests/cypress/e2e/basicE2E.cy.ts
tests/cypress/e2e/components/identity.cy.ts
tests/cypress/e2e/explore.cy.ts
tests/cypress/e2e/opengraph-collection.cy.ts
tests/cypress/e2e/opengraph-item.cy.ts
tests/cypress/e2e/rmrk-simple-mint.cy.ts

fix: twitter-opengraph

---

plugins/vueTippy.ts

https://user-images.githubusercontent.com/9414378/218304931-2ffec63c-cdb9-459d-8e07-5858ad4e580a.mov

feat: hide tooltip on scroll

---

components/shared/form/BasicInput.vue
tests/cypress/e2e/create-collection.cy.ts

fix: readd checkValidity()

---

libs/ui/src/components/IdentityItem/IdentityItem.vue

fix: Wrong redirect to a profile

---

components/gallery/GalleryItem.vue
components/shared/MessageNotify.vue

`/bsx/gallery/{id}?message=congrats`

🔧 galleryItem congrats message errors

---

components/explore/ExploreGrid.vue
components/explore/ExploreIndex.vue

✨ quick & not dirty explore grid layout size

---

components/Navbar.vue
components/bsx/Offer/MyOffer.vue
components/bsx/Offer/OfferTable.vue
components/carousel/utils/useCarousel.ts
components/generative/CongratsView.vue
components/landing/CuratedList.vue
components/rmrk/Gallery/History.vue
components/rmrk/Gallery/Holder/Holder.vue
components/rmrk/Profile/Sales.vue
components/spotlight/SpotlightTable.vue

🔧 nuxt-link prefix

---

utils/mixins/infiniteScrollMixin.ts

fix: Infinity scroll bit broken

---

components/carousel/CarouselIndex.vue
components/search/SearchSuggestion.vue

There are some error and warnings on the console in the dev environment.
https://beta.kodadot.xyz/

fix: remove error warning

---

components/navbar/ProfileDropdown.vue

fix: Remove Transform and Teleport (Statemine) from Profile on Kusama

---

layouts/explore-layout.vue
pages/_prefix/collection/_id.vue

chore: prepare new collection

---

composables/usePrefix.ts
pages/_prefix/detail/_id/index.vue
pages/_prefix/explore/collectibles.vue
pages/_prefix/explore/items.vue
pages/_prefix/gallery/_id/index.vue
utils/mixins/prefixMixin.ts

fix: Network select in explorer is showing kusama while on bsx

---

libs/ui/src/components/NeoNftCard/NeoNftCard.scss
styles/components/_carousel.scss

fix: Gradient overflow

---

FIRST_TIME.md

✨ FIRST_TIME composition api

---

.gitignore
.vscode/extension.json

better workspace with extension recommendations

✨ vscode devs workspace

---

components/gallery/GalleryItem.vue
layouts/explore-layout.vue
styles/components/_connect-wallet.scss
styles/global.scss

fix: Separator height

---

components/search/SearchBar.vue

fix: Keyboard shortcut K on landing should trigger active input

---

pnpm-lock.yaml

🔧 pnpm build

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue

Note: 0 USD being shown due to rounding decisions with USD (value is 0.44)

fix: 5061 highest offer gallery item

---

styles/components/_search.scss

fix: 5050 search bar styling 

---

components/explore/ExploreSort.vue

fix: 5099 sort by button variant

---

styles/components/_carousel.scss
utils/carousel.ts

fix: Not showing collection on cards

---

components/collectionDetailsPopover/CollectionDetailsPopover.vue
libs/ui/src/components/NeoNftCard/NeoNftCard.vue

Hover collection card on explore page

---

composables/useLocalStorage.ts

Might be needed (#5057)
```ts
const walletProvider = useLocalStorage('wallet')
```

✨ useLocalStorage composable

---

components/navbar/CreateDropdown.vue

fix: Create Waifu leads to normal collection on mobile

---

components/carousel/utils/useCarouselSpotlight.ts

fix: Put Denver waifu to spotlight on landing

---

components/gallery/GalleryItem.vue
libs/ui/src/components/MediaItem/type/ImageMedia.vue

fix: unequal height image on explorer

---

components/gallery/GalleryItemDescription.vue
components/gallery/useGalleryItem.ts
components/rmrk/service/scheme.ts

fix: properties and mediaUri on gallery detail

---

components/rmrk/Gallery/History.vue
components/rmrk/Gallery/Holder/Holder.vue

🐛 holders/flippers redirect link

---

components/search/SearchBar.vue

fix: Search bar focus after hitting enter

---

components/shared/gallery/BreadcrumbsFilter.vue

fix: Search tag when searching nothing

---

components/collection/CollectionList.vue
components/explore/tab/TabOnExplore.vue
components/items/ItemsGrid/ItemsGrid.vue
components/search/types.ts
components/shared/BreadcrumbsFilter.vue
components/shared/gallery/Gallery.vue

feat: Show search term on collection

---

styles/components/_o-tooltip.scss

#5200 date popup changes

---

components/search/Search.vue
components/search/SearchBar.vue

fix: pressed enter two times to search on landing page

---

styles/components/_carousel.scss

#5232 slider overflow

---

components/rmrk/Gallery/Layout.vue
plugins/pinia.ts

🔧 user page preferences layout

---

components/explore/FilterMenuButton.vue

🔧 explore page preferences sidebaropen

---

components/explore/FilterMenuButton.vue
components/explore/MobileFilter.vue
components/rmrk/Gallery/Holder/Holder.vue
components/rmrk/Gallery/Layout.vue
stores/preferences.ts

- fix mistyped preferences store actions

fix preferences store actions

---

utils/constants.ts

fix: Disable RMRK2 for kodadot.xyz

---

components/collection/CollectionList.vue
components/explore/DesktopControls.vue
components/shared/DynamicGrid.vue

fix: Remove grid option from collections

---

components/search/Search.vue

fix: Search dropdown redirect

---

libs/ui/src/components/NeoNftCard/NeoNftCard.vue

#5230 collection popover area issue

---

components/common/ConnectWallet/ConnectWalletModal.vue
components/common/ConnectWallet/WalletMenuItem.vue
locales/de.json
locales/en.json
locales/es.json
styles/components/_connect-wallet.scss

feat(ui): add wallet connect auth tips

---

components/TheFooter.vue
styles/layouts/_footer.scss

fix: Unable to fill footer form

---

styles/layouts/_footer.scss

fix: Mobile footer content

---

styles/layouts/_footer.scss

- subscribe input on footer
- remove some unnecessary `!important` attributes in CSS

fix: subscribe input on footer

---

components/items/ItemsGrid/ItemsGrid.vue

fix: Explorer items doesnot reappear when untick buy now

---

components/explore/SidebarFilter.vue

this issue was mentioned by @roiLeo 
https://github.com/kodadot/nft-gallery/pull/5235#pullrequestreview-1335927496
tested on chrome/firefox/safari work well
https://user-images.githubusercontent.com/16473062/226096875-df77ab25-8654-40c6-be76-d7b1fdb732d3.mp4
https://user-images.githubusercontent.com/16473062/226096878-72e57414-9e41-467b-bfa0-0156d9b5ab72.mp4

fix(ui): sidebar collapse animation issue

---

tests/cypress/e2e/create-collection.cy.ts

test: insufficient funds on create collection rmrk

---

components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
queries/subsquid/bsx/offerHighest.graphql

🔧 gallery item highest offer

---

layouts/explore-layout.vue

fix: spacing collection detail

---

components/collection/CollectionHeader/CollectionBanner.vue

fix: Stroke around pfp collection

---

components/collection/CollectionInfo.vue

🔧 collection redesign description markdown

---

components/items/ItemsGrid/ItemsGrid.vue

#5346 empty search result

---

components/items/ItemsGrid/useItemsGrid.ts
components/items/ItemsGrid/utils/useSearchParams.ts

fix: Own filter collection

---

styles/global.scss

fix(ui): add theme text color for <strong>

---

components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
queries/subsquid/bsx/offerListByNftId.graphql

#5376 order of offers

---

styles/components/_o-tabs.scss

#5365 double border fix

---

utils/notification.ts

fix: Hide error message for user

---

ACTIVITY.md

repotracker first

---

components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
styles/global.scss

fix: Hover bg on nav links

---

components/carousel/module/CarouselMedia.vue

#5436 dancing cards fix

---

package.json
pnpm-lock.yaml
utils/constants.ts

Vuex Options has marck

---

components/chart/PriceChart.vue

#5419 grid color

---

styles/global.scss

#4314 height issue

---

components/collection/activity/events/eventRow/common.ts

fix: Listing nfts on rmrk2 in activity tab

---

components/collection/activity/ownerInsightsTabs/HolderTab.vue

https://user-images.githubusercontent.com/128157824/229352655-63ff631c-755d-4716-aa9f-a01cd7a2d1d5.mp4

feat: sort holders by the most owned NFTs in activity

---

components/explore/ExploreSort.vue

https://user-images.githubusercontent.com/128157824/229132971-2ab8b143-55d3-4b73-b771-04b06619631f.mp4

feat: sorting by price on collection items page

---

components/items/ItemsGrid/ItemsGrid.vue

✨ explore items scrollTopButton

---

components/chart/PriceChart.vue

#5499 Playing with stepsize on chart

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/rmrk2_bug.yml
app/router.scrollBehavior.js
components/CookieBanner.vue
components/chart/PriceChart.vue
components/collection/CollectionInfo.vue
components/collection/activity/events/eventRow/common.ts
components/collection/activity/ownerInsightsTabs/HolderTab.vue
components/explore/ExploreSort.vue
components/gallery/GalleryItemDescription.vue
components/items/ItemsGrid/ItemsGrid.vue
components/items/ItemsGrid/ItemsGridImage.vue
components/massmint/OnBoarding.vue
components/redirect/RedirectModal.vue
components/redirect/useRedirectModal.ts
components/shared/collapse/DescriptionWrapper.vue
components/unique/Collection/Item/CollectionItem.vue
composables/useListInfiniteScroll.ts
libs/ui/src/components/MediaItem/MediaItem.vue
libs/ui/src/components/MediaItem/type/ImageMedia.vue
libs/ui/src/components/NeoNftCard/NeoNftCard.vue
locales/en.json
package.json
pnpm-lock.yaml
styles/components/_toast.scss
styles/global.scss
utils/constants.ts

waiting for
- https://github.com/kodadot/nft-gallery/pull/5429

Merge me when this day ends

---

.github/renovate.json
package.json

ci: adjust major version for node

---

components/collection/CollectionInfo.vue

fix: collection description/info not refresh after search

---

components/chart/PriceChart.vue

fix: Time travel in charts

---

locales/en.json

fix: Stats: HOT - grammar mistake

---

composables/transaction/transactionBurn.ts

:ambulance: do not kill burn on unknown offer

---

middleware/prefix.ts

fix: Switch chain to rmrk2 on rmrk2.kodadot.xyz

---

components/common/ConnectWallet/ConnectWalletModal.vue
utils/config/whitelist.ts

It will redirect you to `rmrk2.(domain)` after you log in with the address in whitelist.

fix: Add whitelist for rmrk2.kodadot.xyz

---

components/TheFooter.vue
locales/en.json

#5560 update footer links

---

components/shared/ScrollTopButton.vue
styles/components/_scroll-to-top-button.scss

#5539 button up fix

---

components/collection/HeroButtons.vue

fix: Copy link should be on the item page

---

components/Navbar.vue

fix: Menu on mobile broken

---

components/common/ConnectWallet/useConnectWallet.ts
components/gallery/GalleryItemPreviewer.vue

fix: Line in the middle after opening wallet dialog

---

components/collection/activity/events/Events.vue
locales/en.json

#5548 empty state

---

components/collection/CollectionCard.vue
components/rmrk/service/scheme.ts

fix: get images on explorer collectibles for ksm

---

components/collection/activity/OwnerInsights.vue
components/collection/activity/ownerInsightsTabs/FlipperTab.vue
components/collection/activity/ownerInsightsTabs/HolderTab.vue
components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue

⚡️ Activity: lazy load owner insights

---

components/common/IdentityForm.vue

Same stuff done on polkadot-js app

🔧 identityForm inputs length

---

components/explore/ExploreChain.vue
components/explore/ExploreSort.vue
components/search/Search.vue
components/search/SearchSuggestion.vue
composables/useListInfiniteScroll.ts
composables/useReplaceUrl.ts

fix: Remove appending ?page=1

---

components/items/ItemsGrid/ItemsGrid.vue

fix: no margin bottom on collection items

---

components/carousel/utils/useCarousel.ts

fix: Show rmrk2 on landing - beta.kodadot.xyz

---

components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue

feat: larger height of gallery tab item container on mobile

---

components/collection/activity/ownerInsightsTabs/FlipperTab.vue
locales/en.json

empty flippers tip

---

styles/global.scss

fix: Overflow content on tag input while minting nft

---

composables/usePrefix.ts

fix: Transfer doing weird thing

---

reviewpad.yml

This pull requests only runs the summarization of pull requests when pull requests are opened!

chore: update reviewpad.yml

---

composables/collectionActivity/helpers.ts

🚸 keep real flippers only

---

components/CookieBanner.vue
package.json
plugins/vue-gtag.client.ts
pnpm-lock.yaml

yet another test ⬆️ 
I'm pretty sure nuxt3 plugins doesn't work with `nuxt-edge`

🔧 gtag plugin

---

package.json
pnpm-lock.yaml

Sorting KSM chains

---

package.json
pnpm-lock.yaml

Sorted KSM chains

---

components/gallery/GalleryItemDescription.vue
locales/en.json

`/ksm/gallery/13328952-54bbd380dc3baaa27b-EVRSOULS-Ranger-00000922`
`/rmrk/gallery/17483893-9AFFD71D65E3DBBF29-KODA_VILLA-KODA_VILLAGE_2-0000000000000002`

feat: Show rmrk version in item description

---

libs/ui/src/components/NeoTooltip/NeoTooltip.scss

`/rmrk/gallery/15172750-4A43156FE23E061C03-SNK-BATBASILISK-0000000000000024`
`/bsx/gallery/3268254081-19`

fix: tab alignment

---

nuxt.config.js

fix: default title seo.

---

utils/constants.ts

🔧 hide nsfw collection

---

package.json
pnpm-lock.yaml
utils/cachingStrategy.ts

unused package `fake-indexeddb`

➖ remove unused dependency

---

components/base/SubmitButton.vue

🔧 Hotfix SubmitButton.vue

---

nuxt.config.js
package.json
plugins/vuex-persist.ts
pnpm-lock.yaml

➖ remove vuex-persist dep

---

libs/ui/src/components/NeoButton/NeoButton.vue
libs/ui/src/components/NeoInput/NeoInput.vue

🔧 NeoInput default IconPack

---

components/explore/ExploreSort.vue
locales/en.json
utils/constants.ts

Closes #6226 
Tested on `/rmrk/collection/08C79124CAC59DC643-BOREDBARRO?collectionId=08C79124CAC59DC643-BOREDBARRO&sort=instance_ASC`

🔧 sort by Sequence

---

layouts/error.vue

- vue3 composition api
- remove box background

🔧 error layout

---

components/Navbar.vue
components/TheFooter.vue
components/carousel/module/CarouselMedia.vue
components/common/ConnectWallet/ConnectWalletModal.vue
components/gallery/GalleryItemDescription.vue
components/gallery/UnlockableTag.vue
components/identity/module/IdentityPopoverHeader.vue
components/identity/module/IdentitySocial.vue
components/landing/FeaturedArticles.vue
components/media/type/UnknownMedia.vue
components/rmrk/Profile/ProfileDetail.vue
components/shared/BlockExplorerLink.vue
components/shared/Error.vue
components/shared/LinkResolver.vue
components/shared/format/ExternalLink.vue
components/teleport/Teleport.vue
layouts/error.vue
libs/ui/src/components/CardArticle/CardArticle.vue
libs/ui/src/components/MediaItem/type/UnknownMedia.vue
pages/_prefix/transfer.vue

chore: introduce no-follow links

---

nuxt.config.js
static/robots.txt
utils/constants.ts

fix: Robots.txt is invalid

---

components/rmrk/Create/ArweaveUploadSwitch.vue

fix: UI - Settings - Minting - Arweave UI information popup

---

components/collection/drop/DropContainer.vue
package.json
pnpm-lock.yaml

- :arrow_up: @paraspell/sdk
- :zap: enable teleport

:ambulance: ParaKek

---

utils/constants.ts

🔧 new apollo clients

---

package.json
pnpm-lock.yaml
script/substack.json

chore: bump paraspell

---

components/rmrk/Gallery/History.vue

🔧 History table To link

---

components/carousel/utils/useCarouselSpotlight.ts

✨ toku nft in spotlight

---

nuxt.config.js

fix: sentry hide source map

---

components/Navbar.vue
components/navbar/NotificationBoxButton.vue
components/navbar/ShoppingCartButton.vue

🔧 sidebar closeBurgerMenu

---

nuxt.config.js

hi, let's try to disable sentry until we find what the rootcause is?

ci: disable sentry on build

---

components/bsx/Collection/ChartContainer.vue
components/rmrk/Gallery/Flipper.vue
components/rmrk/Gallery/Holding.vue
components/rmrk/Profile/ProfileActivity.vue
components/shared/chart/chartMixin.ts
components/shared/modals/keyboardShortcutsModal.vue
utils/mixins/apiUrlMixin.ts
utils/mixins/assetMixin.ts
utils/mixins/authMixin.ts
utils/mixins/prefixMixin.ts
utils/mixins/txMixin.ts
utils/mixins/useApiMixin.ts

- daily part of #4750
🎉 50 files to go

🔧 vue3 composition

---

libs/static/src/indexers.ts
utils/constants.ts

- ref https://github.com/kodadot/nft-gallery/pull/5699#issuecomment-1674592625

🔧 new snek release

---

components/shared/format/BasicMoney.vue
components/shared/format/Money.vue

- part of #4750
- close #3355 
<s>⚠️ ⚠️ ⚠️ </s>

🔧 Vue3 composition Money component

---

components/rmrk/Gallery/GalleryCardList.vue

🔧 GalleryCardList vue3

---

components/bsx/format/TokenMoney.vue
components/shared/format/BasicMoney.vue
components/shared/format/Money.vue

🔧 Money prop

---

components/shared/Loader.vue

🔧 canCancel Loader

---

package.json
pnpm-lock.yaml
utils/mixins/chainMixin.ts
utils/mixins/subscribeMixin.ts

➖ vue-class-component peerdependencies

---

components/shared/DropUpload.vue

Tested on `/snek/gallery/488018416-2` with glb file
- closes #7180 
@preschian https://github.com/kodadot/nft-gallery/commit/ab45b06c49d36f88bca0a963c0580b8b023abd84 ?

🔧 DropUpload accept files

---

libs/ui/src/components/NeoCarousel/NeoCarousel.vue

🔧 carousel indicator background

---

utils/chart.ts

sry my bad 😢 
a wrong refactor commit in #7123

revert: refactor for-loop with forEach

---

components/collection/HeroButtons.vue
components/collection/unlockable/UnlockableHeroButtons.vue
components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
components/massmint/modals/DeleteModal.vue
components/massmint/modals/MissingInfoModal.vue
components/massmint/modals/ReviewModal.vue
components/profile/ProfileDetail.vue
components/shared/OnRampModal.vue
components/shared/QRCode.vue
components/shared/modals/ModalWrapper.vue
libs/ui/src/components/NeoModal/NeoModal.story.vue
package.json
pnpm-lock.yaml

🔧 NeoModal QRCode

---

components/carousel/CarouselTypeLatestSales.vue
components/carousel/CarouselTypeNewestList.vue
components/carousel/utils/useCarouselEvents.ts
components/landing/LandingPage.vue

- https://github.com/kodadot/nft-gallery/issues/7034#issuecomment-1717333668

🔧 landing carousel

---

components/carousel/utils/useCarouselSpotlight.ts
composables/useGraphql.ts
middleware/prefix.global.ts
middleware/redirects.global.ts

ref: https://nuxt.com/docs/guide/directory-structure/middleware

refactor: migration of nuxt route middleware  

---

components/transfer/Transfer.vue

fix: Rename Transfer Page Chain names

---

pages/blog/index.vue

- ref #7375 
Blog view article button not working

🔧 nuxt-link tag blog view article

---

components/collection/drop/DropContainer.vue
components/collection/voteDrop/DropContainer.vue

🔧 drop page

---

components/collection/utils/useCollectionDetails.ts
components/collectionDetailsPopover/CollectionDetailsPopover.vue
components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue

- multiple fixes
- ref #7375 
> [access NFT -> Scroll down to More from this Collection](https://github.com/kodadot/nft-gallery/assets/36627808/fe741b10-017d-4721-9bfe-48baa8dd181d)

🔧 gallery item collection detail popover

---

components/identity/module/IdentityPopover.vue
components/identity/utils/useIdentityStats.ts

🔧 Identity Popover

---

components/collection/CollectionGrid.vue
components/collection/unlockable/UnlockableContainer.vue
components/identity/utils/useIdentityStats.ts
components/search/SearchSuggestion.vue
nuxt.config.js

🔧 Identity stats

---

components/create/CreateCollection.vue
components/create/CreateNft.vue

🔧 deposit row spacing

---

components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
components/rmrk/Gallery/Holder/Holder.vue

🔧 burn & delist

---

components/items/ItemsGrid/useItemsGrid.ts

fix: resolve merge conflict

---

components/search/SearchBar.vue
pnpm-lock.yaml

🔧 search collection hide suggestion

---

libs/ui/src/components/NeoPagination/NeoPagination.vue

🔧 pagination default icon pack

---

CONTRIBUTING.md

Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

Netlify Deploy Button for Kodadot-app #1397

---

components/common/ConnectWallet/WalletMenuItem.vue
components/common/NotificationBox/NotificationBoxModal.vue
components/identity/IdentityItem.vue

- close #7615 
- fix eslint/reviewdog

🔧 Identity NuxtLink

---

assets/styles/components/_gallery-item.scss
components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
libs/ui/src/components/NeoDropdown/NeoDropdown.scss
libs/ui/src/components/NeoTabs/NeoTabs.scss
libs/ui/src/components/NeoTooltip/NeoTooltip.scss
libs/ui/src/components/NeoTooltip/NeoTooltip.vue

🔧 NeoTooltip color

---

nuxt.config.js

- close #7681 
- close #6969 (nice 😎 )
`// TODO: create a new sitemap page only for blog posts`

🔧 seo blog pages

---

components/transfer/Transfer.vue
utils/format/balance.ts

fix: Rounding in Tranfer (change decimals)

---

libs/ui/src/components/NeoNftCard/NeoNftCard.scss

fix: Alignment of cards in explorer

---

nuxt.config.ts

👷‍♂️ 
- close #7754 
- remove unused stuff

⬆️ nuxt version

---

components/common/listingCart/ListingCartModal.vue
components/common/shoppingCart/ShoppingCartModal.vue
components/landing/SignupBanner.vue
libs/ui/src/components/NeoButton/NeoButton.scss

fix: cart action button

---

components/create/CreateNft.vue

🔧 create nft min price 0.01

---

components/drops/DropCard.vue

🔧 dropcard skeleton

---

components/collection/drop/GenerativePreview.vue

fix: Generative mints at mobile

---

components/collection/HeroButtons.vue
components/create/CreateNft.vue
composables/transaction/transactionBurn.ts
composables/transaction/types.ts

- close #7875 
note @preschian made some changes regarding #7908

🔧 burn collection all chains

---

components/carousel/utils/useCarouselEvents.ts

follow-up: https://github.com/kodadot/nft-gallery/pull/7991#issuecomment-1803693264

Expand event limit for generative on landing

---

components/shared/filters/modules/AdvancedFilter.vue

fix: Add bottom margin to the burger menu

---

utils/gallery/abstractCalls.ts

🔧 uniq legacy burn

---

components/collection/voteDrop/DropContainer.vue
components/create/CreateCollection.vue
components/rmrk/service/scheme.ts
composables/autoTeleport/useAutoTeleportTransition.ts

🔧 lint code

---

libs/static/package.json
pnpm-lock.yaml

⬆️ libs/static

---

libs/ui/src/components/NeoCarousel/NeoCarousel.vue

- close #8058 
- Tested on `/ksm/gallery/17829944-3289d9f38266576b1c-AMERICAS2_S01EPISODES-EPISODE_24_LEDC-00000010`

🔧 carousel icon pack

---

assets/styles/layouts/_footer.scss
components/TheFooter.vue

Improvements
Closes #7906
https://github.com/kodadot/nft-gallery/assets/19692986/ebc1b75d-545c-4e8a-a183-d5787b1b179a
@exezbcz cc

Footer improvements

---

assets/styles/global.scss
assets/styles/layouts/_main-navigation.scss
assets/styles/pages/create.scss
components/blog/BlogPost.vue
components/collection/CollectionHeader/CollectionBanner.vue
components/collection/unlockable/UnlockableCollectionBanner.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
components/migrate/landing/content/Index.vue
components/migrate/landing/header/Faq.vue
components/shared/view/InfoBox.vue
nuxt.config.ts

Bugfix
Closes #8060 
cc @exezbcz

use only 400 and 700 font-weight

---

libs/ui/src/components/MediaItem/type/ImageMedia.vue

Bugfix
Closes #8062 
cc @exezbcz

padding around images

---

components/carousel/CarouselTypeGenerative.vue

:facepalm: landing has hardcode generative art

---

components/collection/unlockable/UnlockableCollectionInfo.vue

🔧 drops view collection button

---

components/drops/DropCard.vue
components/drops/useDrops.ts

fix: disabled drop

---

components/collection/drop/GenerativePreview.vue

🔧 generate drop button

---

components/collection/drop/TokenImportButton.vue
nuxt.config.ts

| before | after |
| <img width="878" alt="Screenshot 2023-11-25 at 4 18 56 PM" src="https://github.com/kodadot/nft-gallery/assets/734428/0701b3b7-8894-4863-b466-4306681672d9"> | <img width="763" alt="Screenshot 2023-11-25 at 4 19 07 PM" src="https://github.com/kodadot/nft-gallery/assets/734428/6a1ab083-4ea3-4b26-bfc8-290e2bded499"> |

fix: chunk paraspell sdk

---

nuxt.config.ts

Hi @kodadot/internal-dev, is it safe to adjust the config with this? I constantly reload every time I start dev mode 🤣

chore: prevent reload on development mode

---

libs/ui/src/components/NeoCheckbox/NeoCheckbox.story.vue
libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue

🔧 NeoCheckbox story

---

components/carousel/CarouselTypeGenerative.vue
components/collection/unlockable/UnlockableLandingMobileBanner.vue
components/collection/unlockable/UnlockableLandingTag.vue
composables/popularCollections/constants.ts

- fix landing link
- add to generative carousel
- add to sidebar filter

🔧 add new live drop

---

components/collection/CollectionInfo.vue
components/collection/utils/useCollectionDetails.ts
queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql

🔧 show collection royalty

---

components/collection/unlockable/UnlockableCollectionInfo.vue

fix: view collection on drops should not open new window

---

components/collection/drop/HolderOfGenerative.vue

[8a3cf6e](https://github.com/kodadot/nft-gallery/pull/8596/commits/8a3cf6e1b7f2fd259d42d6c24aafc5f5600b9841)

beta update

---

components/collection/drop/HolderOfGenerative.vue

Show minted drop for current user

Hotfix: minted generative

---

locales/en.json

fix: Top collections mobile

---

components/landing/LandingPage.vue

fix: Shuffle landing strips

---

tests/transactionMintStatemine.spec.ts

toHuman -> toNumber

---

components/landing/LandingPage.vue

🔧 landing newestlist margin top

---

components/explore/ExploreSort.vue
locales/en.json

💅 sort by highestSale DESC

---

libs/ui/src/components/NeoButton/NeoButton.scss

fix: button active hover state on collection filter

---

components/carousel/utils/useCarouselSpotlight.ts

🔧 ahp landing collection spotlight

---

tests/e2e/footer.spec.ts

Test/Change tutorial URL on footer test

---

components/Navbar.vue
components/collection/HeroButtons.vue

🔧 navbar search square btn

---

components/carousel/CarouselIndex.vue
components/carousel/CarouselTypeLatestSales.vue
components/carousel/CarouselTypeNewestList.vue
components/carousel/module/CarouselInfo.vue
components/carousel/utils/useCarouselEvents.ts
components/landing/LandingPage.vue

fix: load-carousel-early

---

libs/static/src/chains.ts

fix: Make default chain AHP

---

components/carousel/module/CarouselInfo.vue

➖ whitespace in carouselInfo

---

utils/drop.ts

:tada: new drop is christmas

---

libs/ui/src/components/MediaItem/type/ImageMedia.vue

do not alter blob urls

---

libs/static/src/endpoints.ts

:zap: deprecate parity nodes on dot and ahp

---

utils/drop.ts

:zap: show christmas city on landing

---

components/carousel/utils/useCarouselSpotlight.ts

Add Christimas City to Ahp Spotlight

---

components/migrate/landing/content/Ready.vue

itemCount is owned nfts

---

package.json
pnpm-lock.yaml

PR features new useful features, code refactoring to reduce Package size and optimizations. Plug and Play as no breaking changes were introduced.
The ParaSpell✨ team wishes the KodaDot team happy holidays 🎉 and new year.
-

ParaSpell XCM SDK v5->v11

---

composables/transaction/mintToken/utils.ts

minimumLastIndexUsed => 0

---

assets/styles/components/_content-markdown.scss
components/shared/Markdown.vue

🔧 markdown paragraph spacing

---

queries/subsquid/general/collectionStatsById.graphql

🔧 collection stats listed no burned

---

components/collection/drop/Generative.vue

Previous drop required delay, this is not a case anymore

:wastebasket: remove delay

---

components/drops/useDrops.ts
utils/drop.ts

:wrench: future drop date

---

utils/drop.ts

Bad month index on FUTURE_DROP_DATE

:bug: month index is from 0 to 11

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/bug_assetshub.yml
.github/ISSUE_TEMPLATE/bug_minting.yml
.github/ISSUE_TEMPLATE/bug_rmrk2.yml

related with https://github.com/kodadot/ops-internal/issues/1265

fix: GitHub Issue Report Template - Payout link review

---

components/items/ItemsGrid/useItemsGrid.ts
components/items/ItemsGrid/utils/useSearchParams.ts

fix: Search by number not working

---

components/collection/drop/HolderOfCollection.vue

🔧 link holder collection id

---

components/items/ItemsGrid/useItemsGrid.ts

trigger 'buy-now' filter when sorting by price

---

composables/autoTeleport/useAutoTeleportTransitionDetails.ts

fix: Auto teleport active 

---

components/MessageNotify.vue
components/buy/Buy.vue
components/common/ShareDropdown.vue
composables/transaction/types.ts
composables/useTransaction.ts
utils/notification.ts

fix: Share link in success message 

---

libs/ui/package.json
pnpm-lock.yaml

set oruga to 7

---

libs/ui/src/components/NeoButton/NeoButton.scss

fix: neo button text conflicts

---

composables/useTransaction.ts

- close #8872 while debuging another issue

🔧 undefined consola

---

libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue

<s>⚠️ check console warning</s>
- close #8832 
don't mind overlay I was testing around

🔧 NeoSkeleton color

---

components/collection/drop/modal/paid/MintOverview.vue

🔧 mint drop modal

---

components/massmint/EditPanel.vue

🔧 massmint modal price

---

components/drops/useDrops.ts

fix: minting drop for the second time

---

components/collection/utils/useCollectionDetails.ts
components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
queries/subsquid/general/nftById.graphql

fix: List NFT floor price button doesn't work

---

components/search/SearchSuggestion.vue
libs/ui/src/components/NeoTable/NeoTable.vue

- related with #8850
- show only ranking link for rmrk
- fix table header class

🔧 search suggestion ranking link

---

components/drops/DropCard.vue

🔧 drop ended

---

components/common/listingCart/shared/ListingCartPriceInput.vue

- close #8880 
- refactoring input

🔧 input number price listing modal

---

components/search/SearchSuggestion.vue

- close #8883 
untill better fix

🔧 hotfix top collection loading

---

components/chart/PriceChart.vue

🔧 price acitvity dropdown

---

components/gallery/GalleryItem.vue
components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue

fix: Remove offers since we donot have them anymore

---

components/collection/activity/events/Events.vue
components/collection/activity/events/eventRow/EventRowDesktop.vue
components/collection/activity/events/eventRow/EventRowTablet.vue
components/collection/activity/utils.ts
components/common/IdentityForm.vue
components/identity/IdentityIndex.vue
components/identity/module/IdentityChain.vue
components/shared/BreadcrumbsFilter.vue
components/shared/filters/SidebarFilter.vue
components/shared/filters/modules/IdentityVerficationFilter.vue
composables/useIdentity.ts
locales/en.json
queries/subsquid/general/identities.graphql
stores/activityFilters.ts

feat: Show traders with identities in collection

---

components/massmint/OverviewTable.vue

fix: Massmint price on ahp being multiplied

---

composables/transaction/mintCollection/transactionMintCollectionStatemine.ts

fix: Supply has been set but shows unlimited on collection page

---

utils/drop.ts

:wrench: the usual

---

utils/drop.ts

:wrench: drop date

---

components/collection/drop/GenerativeLayout.vue
components/collection/drop/MintSection.vue

feat: "See listings" in drop page

---

assets/styles/global.scss
components/chart/PriceChart.vue
components/collection/activity/ownerInsightsTabs/FlipperTab.vue
components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
components/collection/collectionInfoLine.vue
components/collection/drop/GenerativePreview.vue
components/collection/unlockable/CountdownTimer.vue
components/collection/unlockable/ImageSlider.vue
components/common/NotificationBox/NotificationBoxModal.vue
components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
components/common/itemTransfer/ItemTransferModal.vue
components/common/listingCart/shared/ListingCartItemDetails.vue
components/common/shoppingCart/ShoppingCartItemRow.vue
components/create/Confirm/ConfirmMintItem.vue
components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
components/landing/topCollections/TopCollectionsItem.vue
components/navbar/NavbarExploreOptions.vue
components/transfer/Transfer.vue

style: whitespace-nowrap

---

components/collection/CollectionHeader/CollectionBanner.vue
components/collection/unlockable/UnlockableLandingTag.vue
locales/en.json

feat: migrate button on collection page

---

assets/styles/global.scss
components/migrate/steps/Sign.vue
components/migrate/steps/SignLoader.vue
components/migrate/steps/SignLoader1.vue
components/migrate/steps/SignLoader2.vue
components/migrate/steps/SignLoader3.vue
composables/useMigrate.ts

style: signing on migration page

---

components/drops/DropCard.vue
components/drops/DropCardSkeleton.vue
components/drops/Drops.vue
components/drops/useDrops.ts

fix: Skeleton for drops

---

assets/styles/global.scss
components/base/MediaItem.vue
components/collection/drop/GenerativePreview.vue
components/collection/drop/modal/paid/MintOverview.vue
components/collection/unlockable/CountdownTimer.vue
components/collection/unlockable/ImageSlider.vue
components/common/NotificationBox/NotificationBoxModal.vue
components/common/autoTeleport/AutoTeleportPopover.vue
components/common/listingCart/ListingCartMini.vue
components/common/listingCart/shared/ListingCartPriceInput.vue
components/common/shoppingCart/ShoppingCartModal.vue
components/create/Confirm/PriceItem.vue
components/create/CreateNftPreview.vue
components/massmint/EditPanel.vue
components/migrate/steps/Index.vue
components/profile/CollectionFilter.vue
components/shared/filters/MobileFilter.vue

refactor: remove background-color on global.scss

---

assets/styles/components/_search.scss
assets/styles/components/_toast.scss
assets/styles/global.scss
assets/styles/pages/create.scss
components/collection/activity/FilterFloatButton.vue
components/explore/FilterMenuButton.vue
components/shared/modals/ModalBody.vue
components/shared/view/SelectableImage.vue

🔧 pointer-events to tailwind

---

utils/drop.ts

Updating to the new drop

---

utils/drop.ts

:bug: forgot to update the drop date

---

components/collection/activity/events/eventRow/common.ts
components/common/NotificationBox/useNotification.ts
components/transfer/Transfer.vue
composables/massmint/useMassMint.ts

- close #9033 
- fixed notification colors too

🔧 undefined bg colors

---

components/profile/CollectionFilter.vue
components/profile/ProfileDetail.vue

fix: stroke in profile collection filter and mobile tabs 

---

components/shared/TransactionLoader.vue
components/transfer/Transfer.vue

fix: Transfer transaction loader modal broken 

---

components/balance/MultipleBalances.vue
components/common/ConnectWallet/WalletAsset.vue
components/common/ConnectWallet/WalletAssetIdentity.vue
components/common/ConnectWallet/WalletAssetMenu.vue
components/common/ConnectWallet/WalletAssetSetIdentity.vue
components/identity/IdentityItem.vue
locales/en.json

feat: Profile sidebar improvements

---

components/shared/filters/MobileFilter.vue

fix: Collection profile mobile filter missing styles 

---

components/common/itemTransfer/ItemTransferModal.vue

feat: Transfer nfts  show fees

---

components/collection/HeroButtonAddNfts.vue
components/create/CreateLanding.vue
components/create/CreateNft.vue
components/massmint/Massmint.vue
composables/useCollectionDropdown.ts

https://github.com/kodadot/nft-gallery/assets/44554284/deec916b-8ebc-4727-aba7-68ca72465928

feat: "Add NFTs" in collection dropdown flow improvement

---

components/collection/drop/MintSection.vue
components/collection/unlockable/utils/useUnlockableTag.ts

🔧 drop collection path

---

components/common/autoTeleport/AutoTeleportModal.vue
components/search/SearchSuggestion.vue
pages/blog/index.vue

🔧 is-block to tailwind

---

components/collection/activity/events/eventRow/EventRowDesktop.vue
components/collection/activity/events/eventRow/EventRowTablet.vue
components/gallery/GalleryItemDescription.vue
components/profile/activityTab/HistoryRow.vue
components/shared/format/BasicMoney.vue
components/shared/format/Money.vue
components/shared/format/PriceRange.vue

🔧 is-inline-block to tailwind

---

package.json
pnpm-lock.yaml

The latest ParaSpell version introduces many useful features 🧰:
- AssetHubs can now share any currency with connected Parachains (Eg. USDT USDC PINK)
- Parachains with xTokens connected to AssetHubs are now able to transfer any supported currency via MultiAssetTransfer functionality.
- Support for 3 new Parachains - Phala, Khala & Collectives
- API Parameter in Builder is now optional! (eg. you can use Builder().to('PolkadotAssetHub') and SDK will automatically use WS port for you!
PR introduces a breaking change where Builder now has to be imported asynchronously for XCM scenarios. This does not affect KodaDot which already …

Update ParaSpell SDK 3.1.1->4.0.1

---

assets/styles/global.scss
components/Navbar.vue
components/navbar/CreateDropdown.vue
components/navbar/ShoppingCartButton.vue
composables/useViewport.ts

🐞 Bug
https://github.com/kodadot/nft-gallery/assets/44554284/3d1e77e4-0ed5-4f2e-a8bb-385a2c589bec
❤️‍🩹 Fixed
https://github.com/kodadot/nft-gallery/assets/44554284/fc92e74f-633f-4765-80c4-466c8362b3d2

fix: Cart not opening as a menu item

---

components/shared/SkeletonLoader.vue
components/shared/modals/ModalBody.vue
locales/en.json

https://github.com/kodadot/nft-gallery/assets/44554284/402bd95d-4d32-403c-a80a-da69eaca61b6

feat: Loading modal copy variations 

---

components/shared/OnRampModal.vue
package.json
pnpm-lock.yaml
tests/e2e/navigation.spec.ts

fix: parentnode

---

components/shared/modals/ModalBody.vue

fix: Modal title changing according to loading text

---

components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
locales/en.json

🔧 delist title modal signing

---

libs/ui/package.json
libs/ui/src/components/MediaItem/type/ImageMedia.vue
libs/ui/src/components/NeoAvatar/NeoAvatar.vue
libs/ui/src/components/TheImage/TheImage.vue
pnpm-lock.yaml

ci: histoire model-viewer

---

utils/drop.ts

:wrech: florist drop

---

components/carousel/CarouselTypeGenerative.vue
locales/en.json

fix: generative art strip

---

components/profile/CollectionFilter.vue

fx: Collection filter dropdown checkbox 

---

components/common/autoTeleport/AutoTeleportActionButton.vue

fix: Modal action button not taking up the entire space

---

components/teleport/Teleport.vue

fix: Teleport page issues 

---

components/collection/unlockable/UnlockableCollectionBanner.vue

fix drop banner container padding

---

services/fxart.ts

chore: fxart base url

---

components/collection/CollectionHeader/CollectionBanner.vue

Test case:
- https://deploy-preview-9292--koda-canary.netlify.app/ahp/collection/89
- https://deploy-preview-9292--koda-canary.netlify.app/ahp/collection/84
- My fix has changed UI

fix: collection icon

---

components/search/Search.vue
components/search/SearchBar.vue

https://github.com/kodadot/nft-gallery/assets/44554284/724f96a7-f866-4e34-a3c1-a1ac1d4dcde7

fix: Mobile search focus on icon press

---

assets/styles/abstracts/_theme.scss
assets/styles/global.scss
components/drops/CreateDropCard.vue
components/explore/ExploreSort.vue
components/profile/OrderByDropdown.vue
components/teleport/Teleport.vue
components/teleport/TeleportTabs.vue
libs/ui/histoire.config.ts
libs/ui/src/components/NeoSelect/NeoSelect.scss
libs/ui/src/scss/_theme.scss
libs/ui/src/scss/tailwind.scss
libs/ui/src/scss/variable.scss
nuxt.config.ts
tailwind.config.ts

page's light and dark modes should function as usual without any issues.

use default theme class (light / dark)

---

CONTRIBUTING.md
content/blog/first-time.md

Codespaces for starting dev env instantly, with no dependeny issues

Codespaces in quickstart #9308

---

components/drops/useDrops.ts

fix: ended drops

---

components/drops/CreateDropCard.vue
content/blog/kodadots-drop-page-explained.md

fix: Change link: Create your own drop page

---

components/shared/SigningModal/SigningModal.vue
composables/useTransactionEstimatedTime.ts
locales/en.json

https://github.com/kodadot/nft-gallery/assets/44554284/eb1bd55e-cd70-411d-8e30-8d323cbc77b2

feat: more  accurate estimate of waiting time

---

components/drops/DropCardSkeleton.vue
components/landing/HeroBanner.vue

fix: Landing mobile option to zoom out

---

components/create/CreateNft.vue

fix: Swap collection and blockchain fields in minting

---

.github/workflows/playwright.yml
components/balance/MultipleBalances.vue
components/gallery/GalleryItemDescription.vue
components/profile/ProfileEmptyResult.vue
components/shared/OnRampModal.vue
tests/e2e/custom.ts
tests/e2e/fixtures.ts
tests/e2e/footer.spec.ts
tests/e2e/galleryitem.spec.ts
tests/e2e/navigation.spec.ts
tests/e2e/profile.spec.ts
tests/e2e/share.spec.ts
tests/e2e/sidebar.spec.ts
tests/e2e/transfer.spec.ts

Sharding and some small tests/improvements

---

components/buy/Buy.vue

Let's simplify things a bit 
Subscribe **on modal open**
Unsubscribe **on modal close** and **on confirm**

fix(buy modal): price change subscription

---

components/collection/drop/PaidGenerative.vue
components/collection/drop/modal/PaidMint.vue
components/shared/modals/ModalBody.vue

feat: Paid Mint modal, skeleton title to "Uploading data to IPFS"

---

composables/useTransaction.ts

option to disable success notification

---

components/carousel/CarouselTypeDrops.vue
components/drops/DropCard.vue
components/drops/useDrops.ts
components/landing/HeroBanner.vue
services/fxart.ts

perf: featured drops

---

components/teleport/Teleport.vue
components/transfer/Transfer.vue

- close #9276
https://github.com/kodadot/nft-gallery/assets/9987732/d0e826b5-4928-45bc-b3e8-3de28b0ec716

🔧 input number hide error icon

---

components/collection/drop/HolderOfGenerative.vue
components/drops/useDrops.ts
components/gallery/GalleryItemHolderOf.vue
composables/drop/useGenerativeDropMint.ts
services/fxart.ts
utils/drop.ts

fix: remaining nfts

---

components/collection/drop/GenerativeLayout.vue
components/collection/drop/GenerativePreview.vue
components/collection/drop/PaidGenerative.vue
components/common/party/CursorParty.vue
composables/party/types.ts
composables/party/useCursorParty.ts
composables/party/useParty.ts
package.json
pnpm-lock.yaml

❗️ update `PARTY_SOCKET_HOST` inside `composables/party/useParty.ts` with a deploy url from kodadot 

feat: PartyKit integration on drop page

---

queries/subsquid/general/holderOfCollectionById.graphql

fix: Can we lift minting per one address for holderOf

---

libs/static/src/indexers.ts
utils/constants.ts
utils/websocket.ts

feat: rmrk stellate endpoint

---

components/carousel/CarouselTypeDrops.vue
components/drops/DropCard.vue

#9473 dynamic carousel for drops

---

locales/en.json

fix: Missing locale when listing

---

components/collection/drop/CursorParty.vue
components/common/party/CursorParty.vue
components/common/party/Cusor.vue
composables/party/useCursorParty.ts
composables/party/useParty.ts

feat: Party kit showing funds for user that are not connected

---

components/collection/drop/GenerativePreview.vue
components/collection/drop/Phase.vue

feat: notice for drop page

---

components/collection/activity/events/eventRow/EventTag.vue
components/profile/activityTab/HistoryRow.vue
queries/subsquid/general/allEventsByProfile.graphql
queries/subsquid/rmrk/allEventsByProfile.graphql

fix: Video thumbnail not showing on profile activity

---

components/items/ItemsGrid/useItemsGrid.ts

feat: Unfold collapsed cards on profile page

---

assets/styles/components/_nft-card.scss
components/collection/drop/GenerativeLayout.vue
components/collection/drop/ItemsGrid.vue
components/items/ItemsGrid/ItemsGrid.vue
components/items/ItemsGrid/ItemsGridImage.vue
components/items/ItemsGrid/useItemsGrid.ts
components/profile/OrderByDropdown.vue
components/shared/nftCard/NftCard.vue
components/shared/nftCard/NftCardSkeleton.vue
components/shared/nftCard/NftMediaInfo.vue
components/shared/nftCard/types.ts
layouts/unlockable-mint-layout.vue
locales/en.json
queries/subsquid/ahk/nftListWithSearch.graphql
queries/subsquid/general/nftListWithSearch.graphql

feat: Recent generative nft mints in drop page

---

locales/en.json

Generative drops heading

---

components/collection/CollectionInfo.vue

Fix-NAN-in-collection-info

---

components/collection/drop/MintButton.vue
components/collection/drop/PaidGenerative.vue

fix: location check for drop

---

tests/e2e/transfer.spec.ts

Fix transfer test

---

package.json
pnpm-lock.yaml

Updates ParaSpell XCM SDK to latest version.
We have recently switched to Monorepo with our tools so there were some changes introduced. 
There were only minor maintenance changes introduced to SDK meanwhile.
- No

Update ParaSpell to -> v4.1.1

---

components/collection/drop/GenerativePreview.vue

fix Reviewdog error

---

components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue

close modal on cancel

---

components/profile/ProfileActivitySummery.vue
queries/subsquid/general/profileStatsById.graphql

fix: profile stats

---

components/carousel/CarouselTypeDrops.vue

fix: increase limit drops on landing

---

components/common/listingCart/ListingCartModal.vue

https://github.com/kodadot/nft-gallery/assets/44554284/31bf4d72-c357-4977-a22d-309dcdf9d5ba

fix: Listing cart modal open on page load

---

locales/en.json

fix: Migrator: Add Link

---

tests/e2e/footer.spec.ts

Fix footer test

---

components/collection/drop/GenerativePreview.vue

remove debounced watch

---

utils/drop.ts

- add-sailwings-echo-leadlight-refraction-motifs

added SailWings, Echo, LeadLight, Refraction and Motifs

---

components/collection/drop/GenerativeLayout.vue
components/collection/drop/GenerativePreview.vue
components/collection/drop/HolderOfGenerative.vue
components/collection/drop/MintButton.vue
components/collection/drop/PaidGenerative.vue
components/collection/drop/Phase.vue
components/collection/drop/requirement/PrivateMintRequirements.vue
components/collection/drop/types.ts
components/drops/useDrops.ts
composables/collectionActivity/useCollectionActivity.ts
composables/drop/useGenerativeDropMint.ts
composables/drop/useHolderOfCollection.ts
pages/[prefix]/drops/[id].vue
stores/drop.ts
tests/e2e/footer.spec.ts

@prury  affected areas are 
1. requirements for drop
2. mint button (enabled/disabled) and label
all should work perfect both on holder of drop ([reflection](https://deploy-preview-9709--koda-canary.netlify.app/ahk/drops/reflection)) and others ([monotifs](https://deploy-preview-9709--koda-canary.netlify.app/ahk/drops/monotifs) / [refraction](https://deploy-preview-9709--koda-canary.netlify.app/ahp/drops/refraction))
1. label of mint button for `holder` drop was wrong
2.  count refs were wrong inside `isHolderAndEligible` in `MintButton`. making the button disabled wrongly

Holder of composable

---

utils/drop.ts

added Convergente to landing

---

libs/ui/src/components/NeoStepper/NeoStepper.vue
tests/e2e/drops.spec.ts

fix: infinity recursive on drops page holder

---

composables/drop/useHolderOfCollection.ts

fix: fetch if holder_of exists

---

components/collection/drop/modal/PaidMint.vue
components/collection/drop/modal/paid/MintOverview.vue
components/common/autoTeleport/AutoTeleportActionButton.vue

feat: Massmint confirmation modal loading wheel

---

components/carousel/utils/useCarouselEvents.ts
utils/drop.ts

fix: genart carousel

---

components/common/shoppingCart/ShoppingCartItemRow.vue

style: fix text cut in cart sidebar

---

components/Navbar.vue
components/navbar/NotificationBoxButton.vue
components/navbar/ShoppingCartButton.vue

fix: dropdown alignment style

---

locales/en.json

items holding in profile

---

components/drops/Drops.vue
locales/en.json

fix: Add to Calendar text

---

components/drops/calendar/DropsCalendar.vue
components/drops/useDrops.ts
components/drops/utils.ts

fix: Drop not considering timezone

---

components/drops/DropCard.vue
components/drops/DropCardSkeleton.vue
composables/collectionActivity/useCollectionActivity.ts

fix: Skeleton Drop Card not updated to v2

---

components/codeChecker/PreviewCard.vue

small visuals

---

components/codeChecker/CodeChecker.vue
components/codeChecker/issueHint/NoWebGl.vue
locales/en.json

I have made up the tip  content, please check

check webgl

---

components/drops/Drops.vue

change active order

---

components/collection/drop/GenerativeLayout.vue

fix: Latest NFT mints wont load at drop page

---

components/TheFooter.vue
tests/e2e/footer.spec.ts

feat: Change footer in pure text

---

tests/e2e/drops.spec.ts

Drop test small refactor

---

components/landing/topCollections/TopCollectionsCard.vue

feat: Grey negative indicators

---

components/collection/unlockable/UnlockableCollectionInfo.vue

fix: More Space on mobile drop page

---

components/profile/ProfileActivitySummeryV3.vue
components/profile/ProfileDetailV3.vue

Changed stats font size from 20px (`text-xl`) to 18px (`text-lg')

Profile V3 smol adjustments

---

assets/styles/layouts/_main-navigation.scss
components/Navbar.vue

fix: burguer menu options overlapping with Navbar on 640-1024px width

---

components/CookieBanner.vue

fix: Ux friendly cookie popup mobile

---

composables/useTeleport.ts

https://github.com/kodadot/nft-gallery/assets/44554284/6da3912d-6451-4f13-8fdf-38a9d4e6238b

fix: Can't retry cancelled teleport singing

---

composables/drop/massmint/useDropMassMint.ts

fix: Minting more than 1 NFT on the drop - gives you all random NFTs?

---

libs/static/package.json
pnpm-lock.yaml

- **:arrow_up: static deps**
- **:wrench: lockfile;**

Deploy of @kodadot/static

---

libs/static/src/indexers.ts

SubSquid made new urls for indexers :))

:label: :wrench: new types for basick indexer

---

components/teleport/Teleport.vue

feat: Auto-reload balance after Teleport

---

libs/static/package.json
pnpm-lock.yaml

fix: https://github.com/kodadot/nft-gallery/pull/10026
related https://github.com/kodadot/nft-gallery/pull/10013/files

fix: build

---

components/drops/calendar/DropsCalendar.vue

filter out live drops

---

components/gallery/GalleryItemButton/GalleryItemButton.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
components/gallery/useGalleryItem.ts

feat: download option for gen art

---

components/drops/utils.ts

fix: Calendar still showing wrong timezone

---

components/collection/HeroButtons.vue
composables/useSocialShare.ts
locales/en.json
utils/constants.ts

feat: Share collection - as frame and other options

---

components/profile/activityTab/HistoryRow.vue

- @prury please review
- @JustLuuuu

show only image in profile activity

---

components/collection/drop/GenerativeLayout.vue
components/common/EmptyResult.vue

style: fix dropdown overflow issue on drop page

---

components/gallery/GalleryItem.vue

test case: https://canary.kodadot.xyz/ahp/gallery/115-2404190282

fix: Open in New Tab not working

---

tests/e2e/createnft.spec.ts

:test_tube: Lower deposit on AssetHub Kusama

---

components/why-koda/HeroSection.vue
components/why-koda/SectionItem.vue
locales/en.json

fix: Small responsivity issue on Why Koda? page

---

components/TheFooter.vue

feat: Why koda footer highlight

---

libs/static/src/chains.ts

fix: Autoteleport after rfc - lowering deposits and fees

---

components/collection/drop/MintButton.vue

fix: Rounding USD to two decimals

---

STYLE_GUIDE.md
pages/sustainability.vue
tests/TESTSUITE.md

chore: fix typos

---

components/CookieBanner.vue

- 1. transition was not working
- 2. removing the transition fixed the issue

fix: New CookieBanner causing blank screen

---

utils/drop.ts

chore: massmint hdd

---

components/profile/ProfileDetail.vue
components/profile/create/stages/Select.vue
locales/en.json

fix: Button size in create new profile

---

components/profile/create/stages/Introduction.vue
components/shared/modals/ModalBody.vue

https://github.com/kodadot/nft-gallery/assets/44554284/32d91e3a-07fd-4bc9-8008-5b1b2c9c447b

fix: Modal Not looking right

---

components/profile/ProfileActivitySummery.vue
components/profile/follow/UserRow.vue

fix: Followers UX improvements

---

libs/ui/src/components/NeoButton/NeoButton.scss

fix: animated button hover state

---

components/profile/activityTab/Activity.vue

fix: Align center in profile activity

---

components/profile/follow/Modal.vue

close before unmount

---

components/profile/create/Modal.vue
components/profile/create/stages/Form.vue
services/profile.ts

fix disabled submit profile button

---

components/codeChecker/validate.ts

graceful handle of url check

---

components/landing/FarcasterMintNotificationBanner.vue
script/farcasterLiveMint.json

fix: New warpcast mint landing notif

---

components/codeChecker/CodeChecker.vue
components/codeChecker/codechecker.config.js
components/codeChecker/types.ts
components/codeChecker/utils.ts
components/codeChecker/validate.ts

Expand web gl check to all js files

---

components/profile/create/Modal.vue
locales/en.json
utils/notification.ts

https://github.com/kodadot/nft-gallery/assets/44554284/f4c5e55b-fee7-42b6-9b4f-055ce8858b61

feat: Confirm connection - information notif

---

composables/massmint/massMintHelpers.ts

fix: Mass mint wrong pricing

---

components/profile/create/Modal.vue
composables/useProfile.ts

fix: Profile Creation modal appears for already created profiles

---

components/profile/CollectionFilter.vue
composables/useProfile.ts

fix: Profile image/button state is lost when network changes

---

components/common/ConnectWallet/WalletAssetIdentity.vue
components/identity/IdentityItem.vue

feat: PFP in confirm modal

---

components/landing/topCollections/TopCollections.vue

fix: Top Collection buttons got reduced

---

components/collection/drop/PaidGenerative.vue

fix: close modal reset drops state

---

components/common/ConnectWallet/WalletAssetIdentity.vue
components/identity/module/IdentityLink.vue
components/identity/module/IdentityPopoverHeader.vue
components/profile/ProfileDetail.vue
components/transfer/Transfer.vue
locales/en.json

fix: Address copied to clipboard

---

libs/static/src/endpoints.ts

IBP node stopped working at all

:ambulance: change RPC provider on AHP

---

components/CookieBanner.vue
components/Navbar.vue
components/navbar/CookiesButton.vue
components/navbar/ProfileDropdown.vue
components/settings/UserData.vue
composables/useCookies.ts
locales/en.json
nuxt.config.ts
pages/settings.vue

feat: Cookie options

---

components/collection/drop/GenerativePreview.vue

fix: Changing counter resizes windows

---

components/profile/ProfileDetail.vue
components/profile/create/openProfileModal.ts
components/profile/follow/UserRow.vue
libs/ui/src/components/NeoModalExtend/plugin.ts

fix: try to follow someone without having a profile setup

---

components/shared/ProfileAvatar.vue

fix: Gallery item shadow

---

nuxt.config.ts

fix: wallet connect default project id

---

components/collection/drop/MintButton.vue

fix: Timezones on Drop again not working?

---

components/navbar/NavbarExploreOptions.vue

fix: Explore card - reorder networks

---

components/profile/ProfileDetail.vue

fix: Create profile when not connected

---

components/drops/BasicDropCard.vue
components/drops/DropCardSkeleton.vue

feat: Fixed aspect ratio to 1:1 for drop cards

---

components/collection/drop/MintStepper.vue

fix: inputting zero should default to 1

---

components/profile/ProfileDetail.vue
components/profile/create/stages/Form.vue
components/profile/follow/Tab.vue
components/profile/follow/UserRow.vue
utils/account.ts

feat: create and follow profiles on Base

---

components/collection/drop/MintStepper.vue
libs/ui/src/components/NeoStepper/NeoStepper.vue

fix: Prevent user from adding comma on drops

---

pages/[prefix]/drops/[id].vue
services/fxart.ts
services/profile.ts
utils/chain.ts
utils/config/ipfs.ts
utils/env.ts

fix: `koda.art` is using beta workers

---

components/profile/ProfileDetail.vue

fix: Adjust profiles for mobile

---

services/fxart.ts
services/profile.ts
utils/config/ipfs.ts

seems auto-imports don't work in tests 
ref https://github.com/kodadot/nft-gallery/pull/10322#issuecomment-2178211251

fix: auto-import not working in tests 

---

components/common/Notification.vue

🔧 notification break all word

---

components/codeChecker/CodeChecker.vue
components/codeChecker/issueHint/NotUsingExternalResources.vue
components/codeChecker/massPreview/Capture.vue
components/codeChecker/massPreview/utils.ts
components/codeChecker/types.ts
components/codeChecker/utils.ts
components/codeChecker/validate.ts
locales/en.json

feat: Add new check to code-checker

---

components/why-koda/HeroSection.vue

issue with vite-svg-loader on local dev env

🔧 dev console warnings

---

components/base/MediaItem.vue
components/carousel/module/CarouselMedia.vue
components/common/ConnectWallet/WalletAssetNfts.vue
components/gallery/GalleryItem.vue
components/gallery/GalleryItemDescription.vue
components/rmrk/Gallery/GalleryCard.vue
components/shared/nftCard/NftCard.vue

feat: Mental shift from gen art tag to normal png tag

---

composables/collectionActivity/useCollectionActivity.ts

https://github.com/kodadot/nft-gallery/assets/44554284/61e7f4ab-d8a4-44bf-9d13-2de75cb18c28

fix: Collection Activity on AHP not loading or taking a long time to load

---

components/collection/drop/CollectedByAvatar.vue

fix: hover card does not load the correct name

---

components/profile/create/SelectImageField.vue
components/profile/create/stages/Form.vue
locales/en.json

fix: Limit image size when upload images to profile

---

locales/en.json

fix: Change `buy now` to listed

---

components/profile/ProfileDetail.vue

fix: Profile followed by images small improvements

---

components/common/ConnectWallet/ConnectEvm.vue
components/shared/AddressChecker.vue
utils/account.ts
utils/config/wallets/BaseDotsamaWallet.ts

fix: App will crash when EVM wallet from talisman is provided

---

nuxt.config.ts

- Noticed that clarity was enabled on dev env , should be enabled only on production / beta,

feat: disable `clarity` on `dev` env

---

components/shared/Avatar.vue
plugins/vueHtmlSecure.ts

fix: Security Hotspot warning

---

components/common/autoTeleport/AutoTeleportModal.vue

fix: full height modal on mobile if needed / weird scrolling behaviour on nova wallet

---

components/profile/ProfileActivitySummery.vue
components/profile/ProfileBannerSkeleton.vue
components/profile/ProfileDetail.vue

💅 mobile profile responsiveness

---

package.json
pnpm-lock.yaml

- 
-
The following PR features ParaSpell v5.6.0 which brought many useful features such as custom multilocations, customizable xcm version, Polkadot<>Kusama bridge and many more..
Along with features it brought many safety advancements such updating every package used in SDK to latest version.
-

Update ParaSpell to v5.6.0

---

assets/styles/components/_gallery-item.scss
components/common/ShareDropdown.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue

refactor: square gallery icons

---

components/items/ItemsGrid/ItemsGridImage.vue
components/items/ItemsGrid/ItemsGridImageTokenEntity.vue

fix: List for sale and add to cart buttons

---

.github/actions/pnpm-install/action.yml

chore(actions): update pnpm/action-setup to v4 and pnpm to 9.4.0

---

components/profile/ProfileDetail.vue
components/shared/ProfileAvatar.vue

fix: Profile: If follower doesnot have profile picture leave that Polkadot wallet picture

---

components/base/MediaItem.vue
components/common/ConnectWallet/WalletAssetNfts.vue

Image tags were coming from `Recent NFTs` 

Image tag overlaying sidebar

---

components/landing/DomainChangeNotificationBanner.vue
components/landing/HeroBanner.vue
locales/en.json
utils/env.ts

Expected result:
On `koda.art`
On `beta.kodadot.xyz` `kodadot.xyz` `canary.kodadot.xyz` ...

feat: koda art announcement message on landing

---

components/common/successfulModal/ShareSocialsSection.vue
composables/useSocialShare.ts
locales/en.json

fix: Better wording when sharing profile on X/Telegram

---

pages/drop-checker/[chain]/[collection-id].vue
services/fxart.ts

https://deploy-preview-10634--koda-canary.netlify.app/drop-checker/ahp/158

fix: fetch drop by collection id

---

components/collection/drop/GenerativePreview.vue
locales/en.json

This reverts commit 5d686a4456f70876d87852cdf0bfe6eb35332ff3.

Revert Drop loader

---

composables/useTeleport.ts

fix: Remove information hash

---

locales/en.json

fix: Wording change - congrats modal

---

tests/e2e/drops.spec.ts

fix: Failing test

---

.husky/pre-commit
package.json
pnpm-lock.yaml

chore: update lint-staged

---

package.json
pnpm-lock.yaml

-
-
XCM SDK version 5.7.0 introduces updates to PolkadotJS libs (All updated to the latest version) and Snowbridge implementation. More info on Snowbridge implementation can be found in our [docs](https://paraspell.github.io/docs/sdk/xcmPallet.html#ecosystem-bridges)
This update does not introduce any breaking changes.
The update was tested on the localhost version of the Koda project and teleport worked fine in all 4 scenarios.
With kind regards,
Team ParaSpell✨

Update ParaSpell to v5.7.0

---

components/collection/unlockable/UnlockableCollectionBanner.vue

fix: use img tag avatar drop page

---

components/shared/TransactionSteps/TransactionSteps.vue

https://github.com/user-attachments/assets/683e19c0-a205-4f4d-8018-b1fc69cf144f

fix: autoteleport signing dialog broken?

---

QA.md

Anything missing @kodadot/internal ?

:memo: QA.md

---

.github/workflows/playwright.yml
components/common/ConnectWallet/MnemonicNotice.vue
playwright.config.ts
tests/e2e/explore.spec.ts

ci: adjust flaky test

---

components/common/ConnectWallet/MnemonicNotice.vue
composables/transaction/evm/useMetaTransaction.ts

@vikiival already added the missing `value` param,, tried with coinbase wallet and it is working as expected
@exezbcz which wallet did you use , can you try again ?
--------
just fixing a ts issue 
https://github.com/user-attachments/assets/1d615e63-60ad-4b6e-a8b5-32fd7be820f4

fix: Simulate transaction fail on paid mint

---

components/gallery/GalleryItemButton/GalleryItemButton.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
composables/transaction/transactionBurn.ts
composables/transaction/types.ts

`/base/gallery/0x61fa91bc4df01c199f2c9576a2fe10ea206a55e1-50`

feat: Support NFT burning on EVM

---

components/collection/CollectionHeader/CollectionBanner.vue

fix: Collection name broken

---

components/profile/ProfileDetail.vue

fix: prevent changing border color on hover for avatars in followed by section

---

components/profile/ProfileDetail.vue
utils/ipfs.ts

https://github.com/kodadot/nft-gallery/issues/10729#issuecomment-2272882865

fix: profile cover image quality

---

composables/useProfile.ts

fix: Landing `Create Profile` modal appearing for users with existing profile

---

components/codeChecker/CodeChecker.vue

fix: Code-checker: wrong links

---

utils/config/permission.config.ts

https://github.com/user-attachments/assets/b39866b5-d4a6-45bf-9a07-607f1c77ea90

fix: mantle disable create nft

---

components/collection/drop/modal/shared/SuccessfulDrop.vue

https://github.com/user-attachments/assets/b436c501-1527-4b82-9d29-9514d9bf038a
https://github.com/user-attachments/assets/380f793f-0885-4946-8c0a-62295da0ac6f

fix: View NFT link links wrong - MNT

---

components/common/ConnectWallet/ConnectWalletModal.vue
components/common/ConnectWallet/WalletTabs.vue

feat: Chain connect wallet limitation - styling followup

---

components/navbar/ProfileDropdown.vue

https://github.com/user-attachments/assets/fb6ffab3-9233-4915-87f2-26880dbc9966

fix: On wallet disconnect both wallet are shown

---

components/drops/calendar/DropsCalendar.vue

fix: Drop Calendar section is missing & mobile view a bit off 

---

components/explore/ExploreSort.vue

🔧 mobile collection filter position

---

components/shared/Avatar.vue

fix: unified evm avatar

---

components/common/ConnectWallet/WalletAssetIdentity.vue
components/landing/LandingPage.vue
components/profile/ProfileDetail.vue
components/shared/ProfileAvatar.vue
composables/useFetchProfile.ts
composables/useIdentity.ts
composables/useProfile.ts

https://github.com/user-attachments/assets/abbab74b-5cb5-432c-aa73-752f37d6df15
https://github.com/user-attachments/assets/004bca53-d369-4ccf-92a1-163ad45a582f

fix: Landing create modal still appearing with a profile

---

components/collection/drop/GenerativePreview.vue
components/drops/BasicDropCard.vue
nuxt.config.ts
services/ogi.ts

| drops preview | drops card |
| ![image](https://github.com/user-attachments/assets/9104733d-cff2-487b-831b-06ca63615889) | ![image](https://github.com/user-attachments/assets/4a77d34f-9fc4-42f6-839e-8409028461ed) |

feat: unlimited drops count

---

.github/push_release_beta.sh
.github/push_release_production.sh

I try to have more readable updates :)
Therefore I have updated script to match naming
- https://github.com/kodadot/nft-gallery/pull/10840

:technologist: name of release is (type): Month Year

---

components/drops/Drops.vue

https://github.com/user-attachments/assets/69a5e1db-cd49-47a3-9333-88a09ebec0cb

fix: Hide empty past drops section

---

components/drops/BasicDropCard.vue
components/drops/TimeTag.vue
components/drops/utils.ts

agreed with @exezbcz Time format in drop cards it's changing to `in 5h 30m`

fix: Drop card having overflow

---

components/collection/drop/GenerativePreview.vue
components/collection/drop/MintButton.vue
stores/drop.ts

https://github.com/user-attachments/assets/20dd6581-27ab-4a34-95e3-09c653a0fcb8

fix: Drop Mint button wrong action while loading

---

components/common/autoTeleport/AutoTeleportModal.vue

https://github.com/user-attachments/assets/8d2b6119-1454-409c-9d13-55d96e09b981

fix: Paid mint auto-teleport modal closing on retry

---

components/profile/ProfileDetail.vue
stores/profileOnboarding.ts

https://github.com/user-attachments/assets/8c197133-b39f-4803-bf47-e6ce7d51cfdf

fix: Onboarding profile creation modal shown multiple times per session

---

components/gallery/GalleryItemButton/GalleryItemButton.vue
components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
locales/en.json
utils/kodahash.ts

- feat: added `downloading image` toast
- test: `/ahp/gallery/93-51`
https://github.com/user-attachments/assets/8ceb45a7-9d20-4aab-b6e8-793b7d92726e

fix: bad quality genart Image downloading & NFT with gif not animating 

---

composables/useSocialShare.ts

feat: Preselect koda channel when sharing mint on warpcast

---

components/profile/ProfileDetail.vue

https://github.com/user-attachments/assets/af059cfc-d2bb-4f7d-a071-27185e07c298

fix: Profile page you can follow yourself

---

components/shared/filters/modules/AdvancedFilter.vue

feat: Remove Art view from Advanced

---

composables/useIdentity.ts

fix: Not Showing Name of the Artist

---

components/collection/CollectionInfo.vue
components/collection/HeroButtons.vue
components/collection/utils/useCollectionDetails.ts

fix: Collection view: Show artist as Creator

---

components/profile/activityTab/OfferRow.vue
components/profile/activityTab/Offers.vue

fix: single select offers filter

---

tests/e2e/collection.spec.ts

fix: collection advanced filter test

---

components/profile/create/stages/Form.vue

🔧 create profile twitter icon

---

middleware/redirects.global.ts

- close #10682 
- tested using `/ahp/profile` while connected
- fix missing ts types

✨ middleware profile page redirect

---

components/offer/MakeOffer.vue

fix: Offer modal closing weirdly

---

components/offer/OfferPriceInput.vue

feat: Visible second currency in the offer creation modal

---

utils/drop.ts

:ambulance: making default as 64 items

:wrench: use 64 as a default

---

components/shared/AddressChecker.vue

fix: Transfer wrong address network warning

---

components/profile/activityTab/Offers.vue

fix: Clicking on incoming offers - weird linking

---

components/carousel/module/CarouselAgnostic.vue

https://github.com/user-attachments/assets/cc8d930a-5295-4e72-987f-d7bbd1f4a604
https://github.com/user-attachments/assets/45508d4e-4b67-4a3d-920c-f2acdd2e68bc

fix: Drop calendar: white fog on pictures

---

components/offer/MakeOffer.vue
composables/transaction/transactionOffer.ts

The user balance should be higher than `offer price` plus `offer making cost 0.05DOT`

fix: offer total amount

---

composables/drop/useGenerativeDropMint.ts

fix: Base: Minted NFT - didnot get successfull mint preview

---

components/Navbar.vue
middleware/prefix.global.ts
middleware/redirects.global.ts
utils/config/permission.config.ts

fix: Weird redirect after removing RMRK

---

composables/transaction/transactionMintDrop.ts

fix: evm transaction invalid value

---

components/collection/drop/AddFundsModal.vue
components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue
components/collection/drop/modal/paid/MintOverview.vue
components/common/autoTeleport/AutoTeleportActionButton.vue
components/common/autoTeleport/utils.ts
components/drops/useDrops.ts
composables/useDeposit.ts

@JustLuuuu @exezbcz @kodadot/internal-dev  need help testing , let me know if it still doesn't work 
Did some testing , will continue doing more tomorrow

fix: Autoteleport does incorrect calculations

---

components/gallery/GalleryItemAction/GalleryItemAction.vue

🔧 list action

---

components/bsx/Create/RoyaltyForm.vue
locales/en.json

fix: Royalty Rate (%) - not intiutive in Create

---

composables/transaction/evm/useMetaTransaction.ts

https://github.com/user-attachments/assets/53b82e8c-da75-4e2b-8248-166ccc93d4a4

fix: Evm wallet chain not reacting to prefix change

---

composables/transaction/evm/useMetaTransaction.ts

fix: Cancelled Evm drop transaction showing long message

---

components/common/ConnectWallet/ConnectEvm.vue
components/common/ConnectWallet/ConnectSubstrate.vue
components/common/ConnectWallet/ConnectWalletModal.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
utils/config/chain.config.ts

fix: Make offers on EVM

---

components/base/MediaItem.vue
components/profile/ProfileDetail.vue
components/shared/ProfileAvatar.vue
libs/ui/src/components/MediaItem/type/ImageMedia.vue

fix: Avatar image does not fit

---

components/collection/drop/GenerativePreview.vue
components/drops/BasicDropCard.vue

since this https://github.com/kodadot/private-workers/pull/226/commits/b24d37487e2695731b0a19f1a96cb7d20a28b8ab was added

fix: Unlimited does not work on AssetHub drops

---

components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue
components/collection/drop/modal/PaidMint.vue
composables/drop/massmint/useDropMassMint.ts

if the mint is not ready show the modal loading otherwise throw error message
https://github.com/user-attachments/assets/2b8e7679-7ed1-4622-a3b2-144fbab0ac3d

fix: Error encountered message: when clicked on mint

---

components/common/autoTeleport/AutoTeleportActionButton.vue
components/shared/OnRampModal.vue
composables/useModalManager.ts
libs/ui/src/components/NeoModal/NeoModal.vue

feat: Offramp modal replace confirmation

---

components/navbar/ConnectedProfile.vue
libs/ui/src/components/NeoModal/NeoModal.vue
tests/e2e/sidebar.spec.ts

fix: Sidebar interactions test failing

---

composables/massmint/useMassMint.ts
queries/subsquid/general/collectionForMint.graphql

collection `lastIndexUsed` which is used to calculate the nft `id` was missing
https://github.com/user-attachments/assets/ba62789b-df33-4e2f-a40e-31e8034b1e56

fix: Massmint not working

---

components/massmint/Massmint.vue

fix: massmint cancelled transaction showing success notification

---

components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
queries/subsquid/ahk/nftById.graphql
queries/subsquid/general/nftById.graphql
queries/subsquid/ksm/nftById.graphql
queries/subsquid/rmrk/nftById.graphql
types/index.ts

fix: only collection issuer can edit NFT

---

components/profile/ProfileDetail.vue

fix: Profile interactions test

---

components/collection/EditModal.vue
components/collection/HeroButtonEditCollection.vue

feat: Collection Edit: Support Name Update and Description Update

---

components/common/ConnectWallet/WalletAssetMenu.vue
locales/en.json

feat: Swap Landing link

---

components/gallery/GalleryItemAction/GalleryItemAction.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTrade.vue
locales/en.json
stores/atomicSwaps.ts
utils/config/permission.config.ts

feat: Swaps in Gallery Item follow up

---

components/common/ChainDropdown.vue
components/profile/CollectionFilter.vue
components/swap/GridListFilters.vue

fix: inconsistent styling in swap page

---

components/swap/Preview.vue

fix: Sidebar is not sticky after navbar

---

components/items/ItemsGrid/ItemsGridImage.vue
components/items/ItemsGrid/useAtomicSwapAction.ts

fix: Swap item appearing as selected in Collection Grid

---

components/common/Notification.vue
components/swap/review.vue
locales/en.json
utils/notification.ts

fix: swap successful redirect

---

components/swap/review.vue

fix: Swaps Landing Blank Review page

---

components/massmint/OverviewTable.vue

fix: Mass mint overview table styles

---

components/gallery/GalleryItem.vue
components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
components/gallery/GalleryItemTabsPanel/types.ts
components/trade/makeOffer/MakeOfferModal.vue
composables/useTransactionNotification.ts
stores/preferences.ts
tests/e2e/galleryitem.spec.ts

feat: Auto-select `offers` Tab after Creating Offer

---

components/base/MediaItem.vue
components/common/CartItemDetails.vue
components/common/ConnectWallet/ReconnectWalletModal.vue
components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
components/common/shoppingCart/ShoppingCartItemRow.vue
components/create/Confirm/ConfirmMintItem.vue
components/profile/CollectionFilter.vue
components/series/SeriesTable.vue
components/shared/filters/modules/PopularCollections.vue
components/swap/PreviewItem.vue
components/transfer/Transfer.vue
components/transfer/TransferConfirmModal.vue

🔧 bulma image size to tailwind

---

components/collection/drop/HolderOfGenerative.vue
components/collection/drop/PaidGenerative.vue
components/common/userCart/UserCartModal.vue
components/shared/SigningModal/SigningModal.vue
composables/autoTeleport/useAutoTeleportActionButton.ts
composables/autoTeleport/useAutoTeleportTransitionDetails.ts
composables/autoTeleport/utils.ts
composables/transaction/transactionMintDrop.ts
composables/transaction/types.ts
composables/useCollectionAbi.ts
composables/useTransaction.ts
utils/transactionExecutor.ts

-  fix: wagmi setup error
-  fix: 429 too many requests error
-  fix: evm simulate transaction action not working

fix: Evm Token Transfer Modal error

---

composables/useChainRedirect.ts

https://github.com/user-attachments/assets/ca2cb996-49a9-4eba-a633-fd268a5ec6ab

fix: Collection page can't change prefix

---

libs/ui/src/components/MediaItem/type/ImageMedia.vue

fix: Swap Item preview overflowing

---

components/search/SearchBar.vue
components/shared/modals/ModalWrapper.vue
components/shared/nftCard/NftCard.vue
components/shared/nftCard/NftCardSkeleton.vue

part of https://github.com/kodadot/nft-gallery/issues/9013

🔧 is-square & is-invisible bulma to tailwind

---

components/massmint/descriptionTabs.ts
composables/massmint/parsers/parseCsv.ts
public/massmint/template.csv

feat: Support CSV description file type to have on-chain attributes

---

components/gallery/useGalleryItem.ts

fix: Gallery item token refetch with wrong params

---

composables/transaction/utils.ts

- fix:  accept swap action validation

fix:  accept swap action validation

---

components/trade/TradeActivityTable.vue
composables/useTrades.ts

fix: Empty swap table with valid swaps

---

tests/e2e/chain-redirect.spec.ts
tests/e2e/custom.ts
tests/e2e/prefix.spec.ts

feat: collection e2e tests follow up

---

libs/ui/src/components/MediaItem/type/ImageMedia.vue

- related to https://github.com/kodadot/nft-gallery/pull/11293

fix: Squashed profile picture

---

components/trade/TradeExpirationSelector.vue

fix: Expiration dropdown position

---

components/shared/AddressInput.vue
components/swap/landing.vue

There is already an error handler for this case but occur another bug. Let me know if it's ok to keep the original error message and disabled button. @exezbcz

fix: stop user from inputting their own address

---

composables/useTrades.ts

fix: What is soon visible on website? - swap visibility duration

---

assets/styles/global.scss

fix: Missing header content of table

---

components/massmint/Massmint.vue
components/massmint/modals/MissingInfoModal.vue

- closes #11320 i guess
- not tested

🔧 massmint missing names & numbers

---

components/TheFooter.vue
locales/all_lang.json
tests/e2e/footer.spec.ts

🔧 footer presskit

---

libs/ui/src/components/MediaItem/type/VideoMedia.vue

https://stackoverflow.com/questions/49930680/how-to-handle-uncaught-in-promise-domexception-play-failed-because-the-use
https://developer.chrome.com/blog/autoplay/

fix: Add video preview

---

components/profile/ProfileDetail.vue

feat: collection sorting same style as with other tabs on profile

---

components/gallery/GalleryItemDescription.vue
composables/useCollectionAttributes.ts
locales/en.json
queries/subsquid/general/nftAttributesListByCollection.graphql

/ahk/gallery/462-10
/ahk/gallery/462-8

feat: Enable Rarity Calculation Based on Attributes

---

components/codeChecker/massPreview/Canvas.vue
components/codeChecker/utils/index.ts
components/codeChecker/utils/processing.ts
services/cors-proxy.ts

feat: code checker support `loadTable`

---

components/collection/drop/CreatedBy.vue
components/profile/create/stages/Form.vue

🔧 profile creation remove avatar popover

---

components/profile/ProfileDetail.vue

fix: profile page `items` grid in `collections` tab

---

components/collection/unlockable/ImageSlider.vue
components/massmint/OnBoarding.vue
components/massmint/OnBoardingCard.vue
components/shared/DragDrop.vue
components/shared/view/InfoBox.vue
pages/blog/index.vue

refactor: deprecate ktheme usages

---

components/items/Items.vue
components/items/ItemsGrid/ItemsGrid.vue
components/items/ItemsGrid/useItemsGrid.ts
services/oda.ts

fix: duplicate fetch on itemsgrid

---

components/shared/gallery/NeoTag.vue

fix: Search in collection: Dark mode needs adjusting

---

components/swap/review.vue
components/trade/TradeExpirationSelector.vue

fix: Offer expiration dropdown menu misplacement
